using Content.Shared._RMC14.Medical.CryoCell;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Medical.CryoCell;

[GenerateTypedNameReferences]
public sealed partial class CryoCellWindow : DefaultWindow
{
    private CryoCellBui? _bui;

    public CryoCellWindow()
    {
        RobustXamlLoader.Load(this);

        PowerButton.OnPressed += _ => _bui?.TogglePower();
        AutoEjectButton.OnPressed += _ => _bui?.ToggleAutoEject();
        NotifyButton.OnPressed += _ => _bui?.ToggleNotify();
        EjectButton.OnPressed += _ => _bui?.Eject();
        EjectBeakerButton.OnPressed += _ => _bui?.EjectBeaker();
    }

    public void SetBui(CryoCellBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(CryoCellBuiState state)
    {
        var hasOccupant = state.Occupant != null;
        EmptyPanel.Visible = !hasOccupant;
        OccupantPanel.Visible = hasOccupant;

        if (!hasOccupant)
            return;

        OccupantNameLabel.Text = state.OccupantName ?? "";
        HealthBar.Value = state.Health;
        HealthBar.MaxValue = state.MaxHealth;
        HealthBarText.Text = $"{state.Health:F0}/{state.MaxHealth:F0}";

        TemperatureLabel.Text = $"{state.BodyTemperature:F1} K";

        PowerButton.Text = state.IsOperating
            ? Loc.GetString("rmc-cryocell-power-on")
            : Loc.GetString("rmc-cryocell-power-off");
        AutoEjectButton.Pressed = state.AutoEject;
        NotifyButton.Pressed = state.Notify;
        EjectBeakerButton.Disabled = !state.HasBeaker;
    }
}
