using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._RMC14.Cryostorage;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Cryostorage;

[GenerateTypedNameReferences]
public sealed partial class RMCCryoRecoveryWindow : DefaultWindow
{
    // Matches subdued RMC machine windows while keeping each player row visually distinct.
    private static readonly StyleBoxFlat PlayerPanelStyle = new()
    {
        BackgroundColor = Color.FromHex("#1A1A1A"),
        BorderColor = Color.FromHex("#3A3A3A"),
        BorderThickness = new Thickness(1),
    };

    private static readonly Color MutedText = Color.FromHex("#A8B0B8");

    private RMCCryoRecoveryBui? _bui;
    private RMCCryoRecoveryBuiState? _state;

    // Expansion is client-only presentation state; server state remains the authority for recoverable items.
    private readonly HashSet<NetEntity> _expandedPlayers = new();

    public RMCCryoRecoveryWindow()
    {
        RobustXamlLoader.Load(this);

        SearchBar.PlaceHolder = Loc.GetString("rmc-cryo-recovery-search-placeholder");
        SearchBar.OnTextChanged += _ => Render();
        SummaryLabel.Modulate = MutedText;
    }

    public void SetBui(RMCCryoRecoveryBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(RMCCryoRecoveryBuiState state)
    {
        _state = state;
        var players = state.Players.Select(player => player.Player).ToHashSet();
        _expandedPlayers.RemoveWhere(player => !players.Contains(player));
        Render();
    }

    private void Render()
    {
        PlayersContainer.DisposeAllChildren();

        var filter = SearchBar.Text.Trim();
        var visiblePlayers = 0;
        var visibleItems = 0;

        if (_state != null)
        {
            foreach (var player in _state.Players)
            {
                var playerMatches = Matches(player.Name, filter) || Matches(player.Job, filter);
                // Hidden item locations still participate in search so Requisitions can find a known slot/cache.
                var items = string.IsNullOrWhiteSpace(filter) || playerMatches
                    ? player.Items
                    : player.Items
                        .Where(item => Matches(item.Name, filter) || Matches(item.Location, filter))
                        .ToList();

                if (items.Count == 0)
                    continue;

                visiblePlayers++;
                visibleItems += items.Count;
                AddPlayer(player, items, _expandedPlayers.Contains(player.Player));
            }
        }

        SummaryLabel.Text = Loc.GetString(
            "rmc-cryo-recovery-summary",
            ("players", visiblePlayers),
            ("items", visibleItems));

        var hasItems = visibleItems > 0;
        EmptyPanel.Visible = !hasItems;
        ResultsScroll.Visible = hasItems;
    }

    private static bool Matches(string value, string filter)
    {
        return string.IsNullOrWhiteSpace(filter) ||
               value.Contains(filter, StringComparison.OrdinalIgnoreCase);
    }

    private void AddPlayer(RMCCryoRecoveryPlayerData player, List<RMCCryoRecoveryItemData> items, bool expanded)
    {
        var panel = new PanelContainer
        {
            Margin = new Thickness(0, 0, 0, 6),
            PanelOverride = PlayerPanelStyle,
        };

        var playerBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(8),
        };
        panel.AddChild(playerBox);

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
        };
        playerBox.AddChild(header);

        var playerEnt = player.Player;
        var expandButton = new Button
        {
            Text = expanded ? "v" : ">",
            MinWidth = 28,
            StyleClasses = { "ButtonSquare" },
            Margin = new Thickness(0, 0, 6, 0),
        };
        expandButton.OnPressed += _ =>
        {
            if (!_expandedPlayers.Remove(playerEnt))
                _expandedPlayers.Add(playerEnt);

            Render();
        };
        header.AddChild(expandButton);

        header.AddChild(new Label
        {
            Text = player.Name,
            StyleClasses = { "LabelKeyText" },
            VerticalAlignment = VAlignment.Center,
        });

        header.AddChild(new Label
        {
            Text = $"  {player.Job}",
            Modulate = MutedText,
            VerticalAlignment = VAlignment.Center,
        });

        header.AddChild(new Control { HorizontalExpand = true });

        header.AddChild(new Label
        {
            Text = Loc.GetString("rmc-cryo-recovery-item-count", ("count", items.Count)),
            Modulate = MutedText,
            Margin = new Thickness(0, 0, 6, 0),
            VerticalAlignment = VAlignment.Center,
        });

        var recoverAll = new Button
        {
            Text = Loc.GetString("rmc-cryo-recovery-recover-all"),
            MinWidth = 96,
            StyleClasses = { "ButtonSquare" },
        };
        recoverAll.OnPressed += _ => _bui?.RecoverAll(playerEnt);
        header.AddChild(recoverAll);

        if (!expanded)
        {
            PlayersContainer.AddChild(panel);
            return;
        }

        playerBox.AddChild(new HSeparator { Margin = new Thickness(0, 6, 0, 4) });

        foreach (var item in items)
        {
            AddItemRow(playerBox, player.Player, item);
        }

        PlayersContainer.AddChild(panel);
    }

    private void AddItemRow(BoxContainer parent, NetEntity player, RMCCryoRecoveryItemData item)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(34, 2, 0, 2),
        };

        row.AddChild(new Label
        {
            Text = item.Name,
            HorizontalExpand = true,
        });

        var recover = new Button
        {
            Text = Loc.GetString("rmc-cryo-recovery-recover"),
            MinWidth = 86,
            StyleClasses = { "ButtonSquare" },
        };
        var itemEnt = item.Item;
        recover.OnPressed += _ => _bui?.RecoverItem(player, itemEnt);
        row.AddChild(recover);

        parent.AddChild(row);
    }
}
