using System.Linq;
using Content.Shared._RMC14.Cryostorage;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Cryostorage;

[GenerateTypedNameReferences]
public sealed partial class RMCCryoRecoveryWindow : DefaultWindow
{
    private static readonly StyleBoxFlat PlayerPanelStyle = new(Color.FromHex("#172230"));
    private static readonly Color MutedBlue = Color.FromHex("#6F9BC0");

    private RMCCryoRecoveryBui? _bui;
    private RMCCryoRecoveryBuiState? _state;

    public RMCCryoRecoveryWindow()
    {
        RobustXamlLoader.Load(this);

        SearchBar.PlaceHolder = Loc.GetString("rmc-cryo-recovery-search-placeholder");
        SearchBar.OnTextChanged += _ => Render();
        SummaryLabel.Modulate = MutedBlue;
    }

    public void SetBui(RMCCryoRecoveryBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(RMCCryoRecoveryBuiState state)
    {
        _state = state;
        Render();
    }

    private void Render()
    {
        PlayersContainer.DisposeAllChildren();

        var filter = SearchBar.Text.Trim();
        var visiblePlayers = 0;
        var visibleItems = 0;

        if (_state != null)
        {
            foreach (var player in _state.Players)
            {
                var playerMatches = Matches(player.Name, filter) || Matches(player.Job, filter);
                var items = string.IsNullOrWhiteSpace(filter) || playerMatches
                    ? player.Items
                    : player.Items
                        .Where(item => Matches(item.Name, filter) || Matches(item.Location, filter))
                        .ToList();

                if (items.Count == 0)
                    continue;

                visiblePlayers++;
                visibleItems += items.Count;
                AddPlayer(player, items);
            }
        }

        SummaryLabel.Text = Loc.GetString(
            "rmc-cryo-recovery-summary",
            ("players", visiblePlayers),
            ("items", visibleItems));

        var hasItems = visibleItems > 0;
        EmptyPanel.Visible = !hasItems;
        ResultsScroll.Visible = hasItems;
    }

    private static bool Matches(string value, string filter)
    {
        return string.IsNullOrWhiteSpace(filter) ||
               value.Contains(filter, StringComparison.OrdinalIgnoreCase);
    }

    private void AddPlayer(RMCCryoRecoveryPlayerData player, List<RMCCryoRecoveryItemData> items)
    {
        var panel = new PanelContainer
        {
            Margin = new Thickness(0, 0, 0, 8),
            PanelOverride = PlayerPanelStyle,
        };

        var playerBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(8),
        };
        panel.AddChild(playerBox);

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 6),
        };
        playerBox.AddChild(header);

        header.AddChild(new Label
        {
            Text = player.Name,
            StyleClasses = { "LabelKeyText" },
        });

        header.AddChild(new Label
        {
            Text = $"  {player.Job}",
            Modulate = MutedBlue,
        });

        header.AddChild(new Control { HorizontalExpand = true });

        header.AddChild(new Label
        {
            Text = Loc.GetString("rmc-cryo-recovery-item-count", ("count", items.Count)),
            Modulate = MutedBlue,
            Margin = new Thickness(0, 0, 6, 0),
        });

        var recoverAll = new Button
        {
            Text = Loc.GetString("rmc-cryo-recovery-recover-all"),
            MinWidth = 96,
            StyleClasses = { "ButtonSquare" },
        };
        var playerEnt = player.Player;
        recoverAll.OnPressed += _ => _bui?.RecoverAll(playerEnt);
        header.AddChild(recoverAll);

        foreach (var item in items)
        {
            AddItemRow(playerBox, player.Player, item);
        }

        PlayersContainer.AddChild(panel);
    }

    private void AddItemRow(BoxContainer parent, NetEntity player, RMCCryoRecoveryItemData item)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 2, 0, 2),
        };

        row.AddChild(new Label
        {
            Text = item.Location,
            MinWidth = 145,
            Modulate = MutedBlue,
        });

        row.AddChild(new Label
        {
            Text = item.Name,
            HorizontalExpand = true,
        });

        var recover = new Button
        {
            Text = Loc.GetString("rmc-cryo-recovery-recover"),
            MinWidth = 86,
            StyleClasses = { "ButtonSquare" },
        };
        var itemEnt = item.Item;
        recover.OnPressed += _ => _bui?.RecoverItem(player, itemEnt);
        row.AddChild(recover);

        parent.AddChild(row);
    }
}
