using Content.Shared.CCVar;
using Content.Shared._RMC14.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Content.Client._RMC14.UserInterface;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccessibilityTab : Control
{
    // RMC14
    private ConfirmationWindow? _postDeathChatMuteConfirmation;
    // RMC14

    public AccessibilityTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(CCVars.ChatEnableColorName, EnableColorNameCheckBox);
        Control.AddOptionCheckBox(CCVars.AccessibilityColorblindFriendly, ColorblindFriendlyCheckBox);
        Control.AddOptionCheckBox(CCVars.ReducedMotion, ReducedMotionCheckBox);
        Control.AddOptionPercentSlider(CCVars.ChatWindowOpacity, ChatWindowOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleTextOpacity, SpeechBubbleTextOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleSpeakerOpacity, SpeechBubbleSpeakerOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleBackgroundOpacity, SpeechBubbleBackgroundOpacitySlider);
        Control.AddOptionCheckBox(CCVars.ChatAutoFillHighlights, AutoFillHighlightsCheckBox);
        Control.AddOptionColorSlider(CCVars.ChatHighlightsColor, HighlightsColorSlider);

        Control.AddOptionCheckBox(RMCCVars.RMCUseAlternateSprites, RMCUseAlternateSpritesCheckBox); // RMC14
        Control.AddOptionCheckBox(RMCCVars.RMCChatSquadColorMode, RMCChatSquadColorModeCheckBox); // RMC14
        Control.AddOptionCheckBox(RMCCVars.RMCXenoAbilityPreviews, XenoAbilityPreviewsCheckBox); // RMC14
        Control.AddOptionCheckBox(RMCCVars.RMCMarineEquipmentPreviews, MarineEquipmentPreviewsCheckBox); // RMC14

        Control.AddOptionCheckBox(CCVars.AccessibilityClientCensorNudity, CensorNudityCheckBox);

        // RMC14
        var postDeathChatMute = Control.AddOptionCheckBox(RMCCVars.RMCPostDeathChatMute, RMCPostDeathChatMuteCheckBox);
        postDeathChatMute.ImmediateValueChanged += OnPostDeathChatMuteChanged;
        // RMC14

        Control.Initialize();
    }

    // RMC14
    private void OnPostDeathChatMuteChanged(bool enabled)
    {
        if (enabled)
            return;

        RMCPostDeathChatMuteCheckBox.Pressed = true;
        Control.ValueChanged();

        if (_postDeathChatMuteConfirmation is { IsOpen: true })
            return;

        var window = new ConfirmationWindow();
        _postDeathChatMuteConfirmation = window;
        window.Setup(
            Loc.GetString("rmc-ui-options-post-death-chat-mute-confirmation-title"),
            Loc.GetString("rmc-ui-options-post-death-chat-mute-confirmation-text"),
            Loc.GetString("rmc-ui-options-post-death-chat-mute-confirmation-accept"),
            Loc.GetString("rmc-ui-options-post-death-chat-mute-confirmation-deny"));

        window.AcceptButton.OnPressed += _ =>
        {
            RMCPostDeathChatMuteCheckBox.Pressed = false;
            Control.ValueChanged();
            window.Close();
        };
        window.DenyButton.OnPressed += _ => window.Close();
        window.OnClose += () => _postDeathChatMuteConfirmation = null;
        window.OpenCentered();
    }
    // RMC14
}

