using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Admin;

[GenerateTypedNameReferences]
public sealed partial class RMCSquadsTab : Control
{
    public RMCSquadsTab()
    {
        RobustXamlLoader.Load(this);
    }
}
