using Content.Shared._RMC14.Xenonids.HiveTeam;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RMC14.Xenonids.HiveTeam;

[GenerateTypedNameReferences]
public sealed partial class HiveTeamWindow : DefaultWindow
{
    public HiveTeamWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(
        HiveTeamsComponent teams,
        List<(NetEntity Entity, string Name, EntProtoId? ProtoId)> allXenos,
        Func<EntProtoId?, Texture?> getTexture,
        Action<int, NetEntity> onSetLeader,
        Action<int> onRemoveLeader,
        Action<int, NetEntity> onAddMember,
        Action<int, NetEntity> onRemoveMember,
        Action<int, int> onSetRole)
    {
        TopRow.DisposeAllChildren();
        BottomRow.DisposeAllChildren();

        for (var i = 0; i < HiveTeamsComponent.TeamCount; i++)
        {
            HiveTeamEntry? entry = i < teams.Teams.Count ? teams.Teams[i] : null;
            var panel = new HiveTeamPanelControl();
            panel.HorizontalExpand = true;
            panel.VerticalExpand = true;
            panel.Populate(i, entry, allXenos, getTexture, onSetLeader, onRemoveLeader, onAddMember, onRemoveMember, onSetRole);

            if (i < 2)
                TopRow.AddChild(panel);
            else
                BottomRow.AddChild(panel);
        }
    }
}
