using Content.Client._RMC14.Xenonids.UI;
using Content.Shared._RMC14.Xenonids.Watch;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client._RMC14.Xenonids.HiveTeam;

[GenerateTypedNameReferences]
public sealed partial class XenoPickerWindow : DefaultWindow
{
    private readonly List<(XenoChoiceControl Control, string Name)> _entries = new();

    public XenoPickerWindow()
    {
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += OnSearch;
    }

    public void Populate(
        List<(NetEntity Entity, string Name, EntProtoId? ProtoId)> xenos,
        Func<EntProtoId?, Texture?> getTexture,
        Action<NetEntity> onPicked)
    {
        Container.DisposeAllChildren();
        _entries.Clear();

        foreach (var xeno in xenos)
        {
            var control = new XenoChoiceControl();
            control.Set(xeno.Name, getTexture(xeno.ProtoId));
            var captured = xeno;
            control.Button.OnPressed += _ =>
            {
                onPicked(captured.Entity);
                Close();
            };
            Container.AddChild(control);
            _entries.Add((control, xeno.Name));
        }
    }

    private void OnSearch(LineEditEventArgs args)
    {
        foreach (var (control, name) in _entries)
        {
            control.Visible = string.IsNullOrWhiteSpace(args.Text) ||
                              name.Contains(args.Text, StringComparison.OrdinalIgnoreCase);
        }
    }
}
