using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Content.Client._RMC14.Roles.FindParasite;

[GenerateTypedNameReferences]
public sealed partial class FindParasiteWindow : DefaultWindow
{
    public FindParasiteWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("xeno-ui-find-parasite-title");
    }
}
