- type: job
  parent: RMCSurvivorParaBase
  id: RMCSurvivorParaTeamLeader
  name: rmc-job-name-para-team-leader
  ranks:
    RMCRankParaSergeant: [ ]
  supervisors: rmc-job-supervisors-commander
  startingGear: RMCGearParaTeamLeader
  icon: RMCJobIconParaTeamLeader
  playTimeTracker: RMCJobSurvivorMilitary
  spawnMenuRoleName: Royal Paramarine Team Leader (Survivor)
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - RoyalMarines
            - TSE
        - type: RMCSurvivor
        - type: Skills
          preset: RMCSkillPresetParaLeader
        - type: RMCAllowSuitStorage
        - type: IntelRescueSurvivorObjective
        - type: MotionDetectorTracked
        - type: MarineOrders
        - type: RMCPointing
        - type: CommandAccent
        - type: RMCTrackable
        - type: SquadLeader
          icon:
            sprite: _RMC14/Interface/Hud_Icons/TSE/paramarines.rsi
            state: rcm_para_sectionleader
        - type: TacticalMapIcon
          icon:
            sprite: /Textures/_RMC14/Interface/TacMap_Icons/tse.rsi
            state: rcm_sectionleader
          background:
            sprite: /Textures/_RMC14/Interface/TacMap_Icons/tse.rsi
            state: background_para
        - type: AssignSquad
          squad: SquadPara
        - type: JobPrefix
          prefix: rmc-job-prefix-para-team-leader
  hidden: true

- type: startingGear
  parent: RMCGearParaBase
  id: RMCGearParaTeamLeader
  equipment:
    id: RMCIDRoyalParamarinesTeamLeader
    head: RMCHeadParaBeretLead
    ears: RMCHeadsetParaTeamLead
    outerClothing: RMCArmorParaVest
    back: RMCSatchelLightpackFilledPara

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointParaTeamLeader
  name: paramarine team leader spawn point
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorParaTeamLeader
  - type: Sprite
    state: surv_tse

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconParaTeamLeader
  icon:
    sprite: _RMC14/Interface/Hud_Icons/TSE/paramarines.rsi
    state: rcm_para_sectionleader
