- type: job
  parent: CMSurvivor
  id: RMCSurvivorCommanderNewVaradero
  name: rmc-job-name-survivor-commander-new-varadero
  description: cm-job-description-commanding-officer
  playTimeTracker: RMCJobSurvivorCO
  ranks:
    RMCRankLieutenantColonel: []
  startingGear: RMCGearSurvivorCommanderNewVaradero
  supervisors: cm-job-supervisors-marine-high-command
  roleWeight: 0.25
  icon: "RMCJobIconSurvivorCommanderNewVaradero"
  hasIcon: true
  spawnMenuRoleName: UNMC Commander (NV Survivor)
  accessGroups:
  - Colony
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetCommander
    - type: MarineOrders
    - type: RMCPointing
    - type: CommandAccent
    - type: InnateCommandSpeech
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: NpcFactionMember
      factions:
      - UNMC
      - Civilian
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: xo
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_unmc
    - type: JobPrefix
      prefix: rmc-job-prefix-survivor-varadero-commander
    - type: AssignSquad
      whitelist:
        tags:
        - RMCSquadUNMC
  hidden: true
  useLoadoutOfJob: RMCSurvivorCommandingOfficer # for inheritance

- type: startingGear
  id: RMCGearSurvivorCommanderNewVaradero
  equipment:
    ears: RMCHeadsetMarineNV
    jumpsuit: CMJumpsuitBO
    head: RMCHeadCapFlippable
    outerClothing: RMCCoatServiceFolded
    shoes: CMBootsBlackFilled
    back: CMSatchelLiaisonSecure
    belt: RMCMatebaBeltForeconFilled # TODO RMC14: M1911 CO Variant (PR #9863). Mateba for now since both guns are about equal in power
    id: CMIDCardGold
    pocket1: RMCPouchSurvivalFill
    pocket2: RMCPouchGeneralLarge
  storage:
    pocket2:
    - CMClipboard
    - CMPenFountain
    back:
    - CMSheetMetal20

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSurvivorCommanderNewVardero
  name: new varadero commanding officer spawn point
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorCommanderNewVaradero
  - type: Sprite
    state: co_spawn

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconSurvivorCommanderNewVaradero
  icon:
    sprite: _RMC14/Interface/job_icons/UNMC/other.rsi
    state: hudsquad_nv_co
