- type: job
  parent: CMSurvivorScientist
  id: RMCSurvivorNewVaraderoXenobiologist
  name: cm-job-name-survivor-new-varadero-xenobiologist
  description: cm-job-description-survivor
  playTimeTracker: CMJobSurvivorScientist
  startingGear: RMCGearSurvivorNewVaraderoXenobiologist
  greeting: rmc-job-greeting-varadero
  spawnMenuRoleName: New Varadero Xenobiologist (NV Survivor)
  accessGroups:
  - ColonistMedical
  special:
  - !type:AddComponentSpecial
    components:
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: Skills
      preset: RMCSkillPresetSurvivorResearcher
    - type: NpcFactionMember
      factions:
      - UNMC
      - Civilian
      - WeYa
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: goon_sci
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_pmc
    - type: JobPrefix
      prefix: rmc-job-prefix-survivor-new-varadero-xenobiologist
    - type: Language
      spokenLanguages:
      - Spanish
      - English
      understoodLanguages:
      - Spanish
      - English
      currentLanguage: English
      defaultLanguage: English
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetNVXenobiologist
  useLoadoutOfJob: CMSurvivorScientist # for inheritance

- type: startingGear
  id: RMCGearSurvivorNewVaraderoXenobiologist
  equipment:
    ears: RMCHeadsetDistressWeYa
    shoes: CMBootsBlackFilled
    id: RMCIDCardColonistScientist
    pocket1: RMCPouchSurvivalFill
  storage:
    back:
    - CMSheetMetal20

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorNewVaraderoXenobiologist
  name: survivor new varadero xenobiologist spawn point
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorNewVaraderoXenobiologist
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv

- type: entity
  parent: RMCGearSurvivorPresetUNMC
  id: RMCSurvivorPresetNVXenobiologist
  name: varadero xenobiologist preset
  categories: [ HideSpawnMenu ]
  components:
  - type: EntityPreset
    randomOutfits:
    - [ CMHandsLatex, RMCSatchelChemistry, CMUtilityVest, RMCJumpsuitCivilianScientist, RMCGlassesReagentHUDGlasses, RMCMaskSWAT ]
    - [ CMHandsBrown, RMCLabcoatScience, CMJumpsuitResearch, CMMaskSterile, RMCGlassesReagentHUDGlasses, CMSatchel ]
    randomGearOther:
    -
      - [ RMCMotionDetector ]
      - [ RMCGrenadeCustomMetalFoam ]
      - [ RMCGrenadeCustomWeedkiller ]
      - [ RMCThermalTarpV2Folded ]
