- type: job
  parent: CMJobBase
  id: RMCPMCSynthetic
  name: rmc-job-name-pmc-synth
  description: rmc-job-description-pmc-synth
  playTimeTracker: RMCJobPMCSynthetic
  ranks:
    RMCRankWeYaPMCSynthetic: [ ]
  startingGear: RMCGearPMCSynthetic
  icon: "RMCJobIconPMCSynthetic"
  joinNotifyCrew: false
  accessGroups:
  - RMCWeYa
  spawnMenuRoleName: WEYA PMC Synthetic
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WeYa
    - type: Language
      spokenLanguages:
      - English
      - French
      - Japanese
      - Russian
      - Scandinavian
      - German
      - Chinese
      - Spanish
      understoodLanguages:
      - English
      - French
      - Japanese
      - Russian
      - Scandinavian
      - German
      - Chinese
      - Spanish
      currentLanguage: English
      defaultLanguage: English
    - type: LanguageLearning
      learnableLanguages:
      - Xeno
      firstContactLanguages:
      - Xeno
      comprehensionThreshold: 0.8
      learningRange: 8.0
      baseWordLearningRate: 0.05
    - type: JobPrefix
      prefix: rmc-job-prefix-pmc-synth
    - type: RMCTrackable
    - type: MeleeWeapon
      soundHit:
        path: /Audio/_RMC14/Weapons/synthpunch1.ogg
        params:
          variation: 0.15
          volume: -1
      angle: 30
      animation: WeaponArcFist
      attackRate: 1
      damage:
        types:
          Blunt: 35
    - type: Synth
    - type: AssignSquad
      whitelist:
        tags:
        - RMCSquadPMC
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: pmc_syn
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_pmc
  hidden: true

- type: startingGear
  id: RMCGearPMCSynthetic
  equipment:
    head: ArmorHelmetPMCOfficer # Why the shit is the PMC beret a HELMET???
    ears: RMCHeadsetDistressPMC
    # eyes: RMCGogglesMeson // TODO RMC14 mesons
    back: RMCPMCSyntheticSmartpack
    belt: RMCBeltMedicBagPMCFilled
    suitstorage: RMCScabbardMacheteFilled # TODO RMC14 maintenance jack
    jumpsuit: RMCJumpsuitVeteranPMCSynth
    outerClothing: RMCArmorM4PMCSynthFilled
    shoes: RMCBootsPMCFilled
    id: CMIDCardPMC
    pocket1: RMCPouchToolsSocFilledSynthetic
    pocket2: RMCPouchConstructionFillLowGrade
  storage:
    back:
    - RMCUniversalRecorder

- type: playTimeTracker
  id: RMCJobPMCSynthetic
