using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Construction;

[GenerateTypedNameReferences]
public sealed partial class RMCConstructionWindow : DefaultWindow
{
    public RMCConstructionWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
