using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.LinkAccount;

[GenerateTypedNameReferences]
public sealed partial class LinkAccountWindow : DefaultWindow
{
    public LinkAccountWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
