using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Chemistry.SmartFridge;

[GenerateTypedNameReferences]
public sealed partial class RMCSmartFridgeSection : Control
{
    public RMCSmartFridgeSection()
    {
        RobustXamlLoader.Load(this);
    }
}
