using Content.Shared._RMC14.Dropship.Weapon;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Dropship.Weapon.FireMission;

[GenerateTypedNameReferences]
public sealed partial class DropshipFireMissionCreateScreen : PanelContainer
{
    public event Action<string>? FireMissionNameEntered;

    public DropshipFireMissionCreateScreen()
    {
        RobustXamlLoader.Load(this);
        FireMissionNameInput.OnTextEntered += OnFireMissionNameEntered;
    }

    private void OnFireMissionNameEntered(LineEdit.LineEditEventArgs args)
    {
        var enteredText = args.Text;

        if (string.IsNullOrWhiteSpace(enteredText))
            return;

        FireMissionNameEntered?.Invoke(enteredText);
        FireMissionNameInput.Clear();
    }

    public void RefreshFireMissions(List<FireMissionData> fireMissions)
    {
        FireMissionsListContainer.RemoveAllChildren();

        var displayId = 1;
        foreach (var fm in fireMissions)
        {
            var label = new RichTextLabel
            {
                Text = $"FM {displayId}. {fm.Name}",
                HorizontalAlignment = HAlignment.Center,
            };

            FireMissionsListContainer.AddChild(label);
            displayId++;
        }
    }
}
