using System.Linq;
using System.Numerics;
using Content.Client.Message;
using Content.Shared._RMC14.Dropship.Weapon;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Dropship.Weapon.FireMission;

[GenerateTypedNameReferences]
public sealed partial class DropshipFireMissionViewScreen : PanelContainer
{
    private const int MaxWeapons = 4;

    public DropshipFireMissionViewScreen()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(FireMissionData fireMission, List<WeaponDisplayInfo> weapons, int minTiming, int maxDuration)
    {
        FireMissionGrid.RemoveAllChildren();

        FireMissionTitle.SetMarkupPermissive($"Firemission: {fireMission.Name}");
        AddRow("Weapon:", weapons.Select(w => w.Name).ToList());
        AddRow("Ammunition:", weapons.Select(w => $"{w.Ammo} / {w.MaxAmmo}").ToList());
        AddRow("Consumption:", weapons.Select(w => w.AmmoConsumption.ToString()).ToList());
        AddRow("", new List<string>());

        for (var timing = minTiming - 1; timing < maxDuration; timing++)
        {
            var weaponTexts = new List<string>();

            foreach (var weapon in weapons)
            {
                var text = "-";

                foreach (var offset in weapon.Offsets)
                {
                    if (offset.Step != timing)
                        continue;

                    if (offset.Offset.HasValue)
                        text = offset.Offset.Value.ToString();

                    break;
                }

                weaponTexts.Add(text);
            }

            AddRow((timing + 1).ToString(), weaponTexts);
        }
    }

    private void AddRow(string infoText, List<string> weaponTexts)
    {
        FireMissionGrid.AddChild(new RichTextLabel
        {
            Text = $"{infoText}",
            HorizontalAlignment = HAlignment.Right,
            MinSize = new Vector2(0, 18),
            ModulateSelfOverride = Color.FromHex("#00FF36"),
        });

        FireMissionGrid.AddChild(new PanelContainer()
        {
            MinSize = new Vector2(15, 0),
            VerticalExpand = true,
        });

        for (var i = 0; i < MaxWeapons; i++)
        {
            var text = i < weaponTexts.Count
                ? weaponTexts[i]
                : string.Empty;

            FireMissionGrid.AddChild(new RichTextLabel
            {
                Text = $"{text}",
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
                MinSize = new Vector2(0, 18),
                ModulateSelfOverride = Color.FromHex("#00FF36"),
            });
        }
    }
}
