using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._RMC14.Marines.ControlComputer;

[GenerateTypedNameReferences]
public sealed partial class MedalsPanelWindow : DefaultWindow
{
    public MedalsPanelWindow()
    {
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(GiveMedalsTab, Loc.GetString("rmc-medal-panel-tab-give-medals"));
        TabContainer.SetTabTitle(ViewMedalsTab, Loc.GetString("rmc-medal-panel-tab-view-medals"));
    }
}
