# Freelancer Rifleman
- type: job
  parent: CMJobBase
  id: CMFreelancerRifleman
  name: rmc-job-name-freelancer-standard
  description: rmc-ghost-role-information-freelancer-friendly-description
  playTimeTracker: RMCJobFreelancerStandard
  ranks:
    RMCRankFLFreelancer: []
  startingGear: RMCGearFreelancerStandard
  icon: RMCJobIconFreelancerStandard
  joinNotifyCrew: false
  accessGroups:
  - Colony
  - RMCWeYa
  spawnMenuRoleName: Freelancer (Standard)
  special:
  - !type:AddComponentSpecial
    components:
    - type: EquipSurvivorPreset
      preset: RMCPresetFreelancerStandard
    - type: NpcFactionMember
      factions:
      - WeYa
    - type: Skills
      preset: RMCSkillPresetFreelancerRifleman
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: rmc-job-prefix-freelancer-standard
  hidden: true

- type: entity
  id: RMCRandomHumanoidFreelancerStandardHostile
  name: freelancer ghost role rifleman
  suffix: Spawner, Player, Hostile
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Head/Hats/beret_freelancer.rsi
    state: icon
  - type: RandomHumanoidSpawner
    settings: RMCFreelancerStandard

- type: entity
  id: RMCRandomHumanoidFreelancerStandardFriendly
  name: freelancer ghost role rifleman
  suffix: Spawner, Player, Friendly
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Head/Hats/beret_freelancer.rsi
    state: icon
  - type: RandomHumanoidSpawner
    settings: RMCFreelancerStandardFriendly

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: RMCFreelancerStandard
  components:
  - type: GhostRole
    name: rmc-ghost-name-freelancer-hostile-standard
    description: rmc-ghost-role-information-freelancer-hostile-description
    rules: rmc-ghost-role-information-freelancer-rules
    reregister: false
    job: CMFreelancerRifleman
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobRifleman
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: SquadFreelancer

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: RMCFreelancerStandardFriendly
  components:
  - type: GhostRole
    name: rmc-ghost-name-freelancer-friendly-standard
    description: rmc-ghost-role-information-freelancer-friendly-description
    rules: rmc-ghost-role-information-freelancer-rules
    reregister: false
    job: CMFreelancerRifleman
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobRifleman
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: SquadFreelancer

- type: startingGear
  id: RMCGearFreelancerStandard
  equipment:
    gloves: RMCHandsVeteran
    jumpsuit: RMCJumpsuitFreelancer
    outerClothing: CMArmorFreelancer
    shoes: RMCBootsSPPFilled
    id: RMCIDCardFreelancer
    ears: RMCHeadsetDistressDukes
    pocket1: RMCPouchFirstAidERTFill
    back: RMCSatchelLightpackFreelancerStandard

- type: playTimeTracker
  id: RMCJobFreelancerStandard

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconFreelancerStandard
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: free_rfn

- type: entity # trying to do precise randomization via presets would result in this file being 500 lines long, but it's close enough. 12.5% for machinegunner and 18% for shotgunner and 68% for rifleman which should be within +-5% of parity percentage
  id: RMCPresetFreelancerStandard
  name: freelancer preset
  categories: [ HideSpawnMenu ]
  components:
  - type: SurvivorPreset
    randomOutfits:
    - [ RMCCE2BeltFilled, RMCWeaponRifleM54CE2, CMMagazineRifleM54CE2HT, CMMagazineRifleM54CE2HT, RMCPouchExplosiveFilledPlasticExplosives ]
    - [ RMCCE2BeltFilled, RMCWeaponRifleM54CE2, CMMagazineRifleM54CE2HT, CMMagazineRifleM54CE2HT, RMCPouchExplosiveFilledPlasticExplosives ]
    - [ RMCWeaponShotgunType23, RMCPouchExplosiveFilledPlasticExplosives, RMCM276ShotgunShellLoadingRigFillFreelancer, CMGrenadeFragOld, CMGrenadeFragOld, CMGrenadeFragOld, CMGrenadeFragOld, RMCGrenadeIED, RMCGrenadeIED, CMGrenadeSmoke ] # TODO RMC14: Incend IED, /obj/item/storage/firstaid/regular/response
    - [ RMCWeaponShotgunType23, RMCPouchExplosiveFilledPlasticExplosives, RMCM276ShotgunShellLoadingRigFillFreelancer, CMGrenadeFragOld, CMGrenadeFragOld, CMGrenadeFragOld, CMGrenadeFragOld, RMCGrenadeIED, RMCGrenadeIED, CMGrenadeSmoke ]
    - [ RMCWeaponShotgunType23, RMCPouchExplosiveFilledPlasticExplosives, RMCM276ShotgunShellLoadingRigFillFreelancer, CMGrenadeFragOld, CMGrenadeFragOld, CMGrenadeFragOld, CMGrenadeFragOld, RMCGrenadeIED, RMCGrenadeIED, CMGrenadeSmoke ]
    - [ RMCPouchExplosiveFilledC4SPP, CMGrenadeFragOld, CMGrenadeFragOld, RMCSlugBeltFilled, WeaponShotgunCustomBuilt ]
    - [ RMCPouchExplosiveFilledC4SPP, CMGrenadeFragOld, CMGrenadeFragOld, CMBeltMarineBuckshot, WeaponShotgunM357 ]
    - [ RMCPouchExplosiveFilledC4SPP, CMGrenadeFragOld, CMGrenadeFragOld, RMCIncendiarySlugBeltFilled, RMCWeaponShotgunHG3712 ]
    - [ RMCPouchExplosiveFilledC4SPP, CMGrenadeFragOld, CMGrenadeFragOld, CMBeltMarineBuckshot, WeaponShotgunM890]
    - [ RMCPouchExplosiveFilledC4SPP, CMGrenadeFragOld, CMGrenadeFragOld, RMCMAR40BeltFilled, WeaponRifleMAR40 ]
    - [ RMCPouchExplosiveFilledC4SPP, CMGrenadeFragOld, CMGrenadeFragOld, RMCMAR40BeltFilled, RMCWeaponRifleMAR30 ]
    - [ RMCPouchExplosiveFilledC4SPP, CMGrenadeFragOld, CMGrenadeFragOld, RMCMAR50BeltFilled, RMCWeaponMar50LMG ]
    - [ RMCPouchExplosiveFilledC4SPP, CMGrenadeFragOld, CMGrenadeFragOld, RMCBeltMarineMK1, RMCWeaponRifleM54CMK1 ]
    - [ RMCPouchExplosiveFilledC4SPP, CMGrenadeFragOld, CMGrenadeFragOld, RMCFP9000BeltFilled, RMCWeaponSMGFP9000 ]
    - [ RMCPouchExplosiveFilledC4SPP, CMGrenadeFragOld, CMGrenadeFragOld, RMCM17BeltFilled, RMCWeaponRifleM16 ]
    - [ RMCPouchExplosiveFilledC4SPP, CMGrenadeFragOld, CMGrenadeFragOld, RMCType64BeltFilled, RMCWeaponSMGType64 ]
    primaryWeapons: # no easy way to code this without adding 500 more lines to this file
    - [ RMCHeadCapFreelancer ]
    - [ RMCHeadBeanie ]
    - [ CMHeadBandRed ]
    - [ CMHeadBandTan ]
    - [ RMCArmorHelmetSkullcap ]
