using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.Marines.GroundsideOperations;

[GenerateTypedNameReferences]
public sealed partial class GroundsideOperationsConsoleWindow : DefaultWindow
{
    public GroundsideOperationsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        GroundAnnouncementText.Placeholder = new Rope.Leaf(Loc.GetString("rmc-goc-groundside-placeholder"));
        TabContainer.SetTabTitle(OverwatchTab, Loc.GetString("rmc-goc-tab-overwatch"));
        TabContainer.SetTabTitle(CommandMonitorTab, Loc.GetString("rmc-goc-tab-command-monitor"));
        TabContainer.SetTabTitle(ExecutiveTab, Loc.GetString("rmc-goc-tab-executive"));
        TabContainer.SetTabTitle(EmergencyTab, Loc.GetString("rmc-goc-tab-emergency"));
        TabContainer.SetTabTitle(OrdnanceTab, Loc.GetString("rmc-goc-tab-ordnance"));
    }
}
