using Content.Client._RMC14.UserInterface.Crt;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Marines.GroundsideOperations;

[GenerateTypedNameReferences]
public sealed partial class GroundsideOperationsConsoleWindow : DefaultWindow
{
    public event Action? OnTimeRefresh;

    private float _timeRefreshAccumulator;

    public GroundsideOperationsConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        ExecutiveNavigationButton.OnPressed += _ => ShowPage(GroundsideOperationsPage.Executive);
        EmergencyNavigationButton.OnPressed += _ => ShowPage(GroundsideOperationsPage.Emergency);
        OrdnanceNavigationButton.OnPressed += _ => ShowPage(GroundsideOperationsPage.Ordnance);

        ShowPage(GroundsideOperationsPage.Executive);
    }

    public void SetButtonState(
        RMCCrtActionButton button,
        bool disabled,
        bool danger = false,
        string? iconState = null)
    {
        button.Disabled = disabled;
        button.Tone = danger ? RMCCrtTone.Danger : RMCCrtTone.Default;
        if (iconState != null)
            button.IconState = iconState;
    }

    private void ShowPage(GroundsideOperationsPage page)
    {
        ExecutivePage.Visible = page == GroundsideOperationsPage.Executive;
        EmergencyPage.Visible = page == GroundsideOperationsPage.Emergency;
        OrdnancePage.Visible = page == GroundsideOperationsPage.Ordnance;

        StyleNavigationButton(ExecutiveNavigationButton, page == GroundsideOperationsPage.Executive);
        StyleNavigationButton(EmergencyNavigationButton, page == GroundsideOperationsPage.Emergency);
        StyleNavigationButton(OrdnanceNavigationButton, page == GroundsideOperationsPage.Ordnance);
    }

    private static void StyleNavigationButton(RMCCrtActionButton button, bool selected)
    {
        button.Pressed = selected;
        button.Selected = selected;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _timeRefreshAccumulator += args.DeltaSeconds;
        if (_timeRefreshAccumulator < 0.25f)
            return;

        _timeRefreshAccumulator = 0;
        OnTimeRefresh?.Invoke();
    }

    private enum GroundsideOperationsPage
    {
        Executive,
        Emergency,
        Ordnance,
    }
}
