using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Marines.GroundsideOperations;

[GenerateTypedNameReferences]
public sealed partial class GroundsideOperationsLandingZoneWindow : DefaultWindow
{
    public GroundsideOperationsLandingZoneWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
