using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorEntry : Control
{
    public CMAutomatedVendorEntry()
    {
        RobustXamlLoader.Load(this);
    }
}

