using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Mapping;

[GenerateTypedNameReferences]
public sealed partial class MappingActionsButton : Button
{
    public MappingActionsButton()
    {
        RobustXamlLoader.Load(this);
    }
}

