using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Mapping;

[GenerateTypedNameReferences]
public sealed partial class MappingSpawnButton : Control
{
    public MappingPrototype? Prototype;

    public MappingSpawnButton()
    {
        RobustXamlLoader.Load(this);
    }
}
