using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Comms;

[GenerateTypedNameReferences]
public sealed partial class EncryptionCipherComputerWindow : FancyWindow
{
    public event Action<string>? SetInput;
    public event Action<int>? ChangeSetting;
    public event Action? PrintOutput;

    public string InputCode
    {
        get => InputLineEdit.Text ?? "";
        set => InputLineEdit.Text = value;
    }

    public int CipherSetting
    {
        get => int.TryParse(SettingLabel.Text, out var s) ? s : 0;
        set => SettingLabel.Text = value.ToString();
    }

    public string DecipheredWord
    {
        get => WordLabel.Text ?? "";
        set => WordLabel.Text = value;
    }

    public string StatusMessage
    {
        get => StatusLabel.Text ?? "Ready for input";
        set => StatusLabel.Text = value;
    }

    public EncryptionCipherComputerWindow()
    {
        RobustXamlLoader.Load(this);

        SetInputButton.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(InputLineEdit.Text))
            {
                SetInput?.Invoke(InputLineEdit.Text.ToUpper());
            }
        };

        DecreaseButton.OnPressed += _ => ChangeSetting?.Invoke(-1);
        IncreaseButton.OnPressed += _ => ChangeSetting?.Invoke(1);

        PrintButton.OnPressed += _ => PrintOutput?.Invoke();
    }
}
