using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Comms;

[GenerateTypedNameReferences]
public sealed partial class EncryptionCoderComputerWindow : FancyWindow
{
    public string LastSubmittedCode
    {
        get => LastSubmittedCodeLabel.Text ?? "None";
        set => LastSubmittedCodeLabel.Text = value;
    }

    public int KnownLetters
    {
        get => int.TryParse(KnownLettersLabel.Text, out var i) ? i : 0;
        set => KnownLettersLabel.Text = value.ToString();
    }

    public string ClarityDescription
    {
        get => ClarityDescriptionLabel.Text ?? "unknown";
        set => ClarityDescriptionLabel.Text = value;
    }

    public EncryptionCoderComputerWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
