using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Power;

[GenerateTypedNameReferences]
public sealed partial class RMCPowerMonitorStorageRow : PanelContainer
{
    public RMCPowerMonitorStorageRow()
    {
        RobustXamlLoader.Load(this);
    }
}
