using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Power;

[GenerateTypedNameReferences]
public sealed partial class RMCPowerMonitorWindow : DefaultWindow
{
    public RMCPowerMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        TabContainer.SetTabTitle(ApcTab, Loc.GetString("rmc-power-monitor-apcs"));
        TabContainer.SetTabTitle(StorageTab, Loc.GetString("rmc-power-monitor-storage"));
    }
}
