using Content.Shared.NPC.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RMC14.Xenonids.Hive;

[GenerateTypedNameReferences]
public sealed partial class HiveAllianceWindow : DefaultWindow
{
    public HiveAllianceWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(
        List<(ProtoId<NpcFactionPrototype> Id, string Name, bool Allied)> factions,
        List<(NetEntity Entity, string Name, bool Allied)> hives,
        Action<ProtoId<NpcFactionPrototype>, bool> onSetFactionAlly,
        Action<NetEntity, bool> onSetHiveAlly)
    {
        FactionsContainer.DisposeAllChildren();
        foreach (var (id, name, allied) in factions)
        {
            FactionsContainer.AddChild(BuildEntry(name, allied, isAllied => onSetFactionAlly(id, isAllied)));
        }

        HivesContainer.DisposeAllChildren();
        foreach (var (entity, name, allied) in hives)
        {
            HivesContainer.AddChild(BuildEntry(name, allied, isAllied => onSetHiveAlly(entity, isAllied)));
        }
    }

    private static Control BuildEntry(string name, bool allied, Action<bool> onToggled)
    {
        var checkBox = new CheckBox
        {
            Text = name,
            Pressed = allied,
            Margin = new Thickness(2, 1, 2, 1),
        };
        checkBox.OnToggled += args => onToggled(args.Pressed);

        return checkBox;
    }
}
