- type: job
  parent: CMSurvivor
  id: RMCSurvivorSPPSOFBase
  name: rmc-job-name-soro-sof-base
  description: rmc-job-description-soro-sof
  ranks:
    RMCRankSPPRyadovoy: []
  supervisors: cm-job-supervisors-sl
  accessGroups:
  - Colonist
  joinNotifyCrew: false
  startingGear: RMCGearSPPSOFBase
  hasIcon: true
  greeting: rmc-job-greeting-soro-sof
  playTimeTracker: RMCJobSurvivorMilitary
  spawnMenuRoleName: SPP SOF (Sorokyne Special Survivor - Base)
  useLoadoutOfJob: CMSurvivor
  basePlaytimeTracker: true
  abstract: true
  hidden: true

- type: startingGear
  id: RMCGearSPPSOFBase
  equipment:
    jumpsuit: RMCJumpsuitSPPSOF
    outerClothing: RMCArmorSPPSOFFilled
    back: RMCSatchelLightpackBlack
    shoes: RMCBootsSPPFilled
    head: RMCArmorHelmetSPPSOF
    gloves: RMCHandsVeteranSPP
    suitstorage: RMCWeaponRifleType77
    belt: RMCBeltHolsterPistolSPPT73
    id: RMCIDSPP
    ears: RMCHeadsetSPPSOFCrashland
    pocket1: RMCPouchFirstAidSplintsGauzeOintment
    pocket2: RMCPouchFlareR44Filled
  storage:
    back:
    - CMSheetMetal20
