using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Dropship.Fabricator;

[GenerateTypedNameReferences]
public sealed partial class DropshipFabricatorWindow : DefaultWindow
{
    public DropshipFabricatorWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
