using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.AntiAir;

[GenerateTypedNameReferences]
public sealed partial class RMCAlmayerAntiAirWindow : DefaultWindow
{
    public RMCAlmayerAntiAirWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
