using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Photocopier;

[GenerateTypedNameReferences]
public sealed partial class PhotocopierWindow : Control
{
    public PhotocopierWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

