using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.Photocopier;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Photocopier;

[GenerateTypedNameReferences]
public sealed partial class PhotocopierWindow : FancyWindow
{
    public PhotocopierWindow()
    {
        RobustXamlLoader.Load(this);
    }
    public void UpdateState(PhotocopierUiState state)
    {
        var paperName = state.PaperName;
        var canCopy = state.CanCopy;
        var isPaperInserted = state.IsPaperInserted;
        EjectButton.Disabled = !isPaperInserted;
        CopyButton.Disabled = !canCopy || !isPaperInserted;
        Copy2Button.Disabled = !canCopy || !isPaperInserted;
        Copy3Button.Disabled = !canCopy || !isPaperInserted;
        Copy5Button.Disabled = !canCopy || !isPaperInserted;
        Copy10Button.Disabled = !canCopy || !isPaperInserted;
        PaperName.Text = paperName;
        if (isPaperInserted)
        {
            PaperStatusLabel.Text = "INSERTED";
            PaperStatusLabel.FontColorOverride = Color.Green;
        }
        else
        {
            PaperStatusLabel.Text = "EMPTY";
            PaperStatusLabel.FontColorOverride = Color.Red;
        }
    }
}

