using Content.Shared._RMC14.GMRequest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.GMRequest;

[GenerateTypedNameReferences]
public sealed partial class GMRequestWindowEntry : BoxContainer
{
    public GMRequestWindowEntry(GMRequestLog log)
    {
        RobustXamlLoader.Load(this);

        Time.Text = log.Time.ToLongTimeString();
        Username.Text = log.SenderName;
        Entity.Text = log.EntityName;
        Message.Text = log.Message;
        Claimant.Text = log.ClaimName ?? "";
    }
}
