using System.Numerics;
using System.Linq;
using Content.Shared._RMC14.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.UserInterface.Systems.Ghost.Controls;

[GenerateTypedNameReferences]
public sealed partial class RMCGhostTargetWindow : DefaultWindow
{
    [Dependency] private readonly EntityManager _entityManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private readonly Dictionary<NetEntity, RMCGhostTargetEntry> _targets = new();
    private readonly List<RMCGhostTargetSection> _sections = new();
    private readonly Dictionary<string, RMCGhostTargetSectionControl> _sectionControls = new();
    private readonly Dictionary<ButtonKey, RMCGhostTargetButton> _buttons = new();
    private readonly Dictionary<Collapsible, bool> _expansionStates = new();
    private readonly List<NetEntity> _targetDisplayOrder = new();
    private string _searchText = string.Empty;
    private StyleBoxTexture _ghostnadoButtonStyle = default!;

    private static readonly Color TguiGoodButtonColor = Color.FromHex("#4e9121");
    private static readonly Color TguiGoodButtonHoverColor = Color.FromHex("#9ade6d");
    private static readonly Color TguiGoodButtonDisabledColor = Color.FromHex("#29451a");
    private static readonly Color TguiTransparentButtonHoverColor = Color.FromHex("#737373");

    public event Action<NetEntity>? WarpClicked;
    public event Action? OnRefreshClicked;

    public RMCGhostTargetWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        SetWindowBackgroundColor();
        SearchBar.OnTextChanged += OnSearchTextChanged;
        SearchBar.OnTextEntered += _ => WarpToMostRelevantSearchResult();

        GhostnadoButton.Disabled = true;
        SetupSearchBarStyle();
        GhostnadoButton.ModulateSelfOverride = Color.White;
        RefreshButton.ModulateSelfOverride = Color.White;
        GhostnadoButton.OnPressed += _ => WarpToMostFollowed();
        RefreshButton.OnPressed += _ => OnRefreshClicked?.Invoke();
        OnOpen += SearchBar.GrabKeyboardFocus;
        OnClose += ClearContent;
        SetupGhostnadoButtonColors();
        SetupRefreshButtonHover();
    }

    public void UpdateContent(
        NetEntity self,
        IEnumerable<RMCGhostTargetEntry> targets,
        IEnumerable<RMCGhostTargetSection> sections)
    {
        _targets.Clear();
        foreach (var target in targets)
        {
            if (target.Entity != self)
                _targets[target.Entity] = target;
        }

        _sections.Clear();
        _sections.AddRange(sections);
        Reconcile();
        UpdateGhostnadoButtonState();
    }

    public void ClearContent()
    {
        _targets.Clear();
        _sections.Clear();
        _sectionControls.Clear();
        _buttons.Clear();
        _expansionStates.Clear();
        _targetDisplayOrder.Clear();
        ContentContainer.RemoveAllChildren();
        UpdateGhostnadoButtonState();
    }

    private void Reconcile()
    {
        var spriteSystem = _entityManager.System<SpriteSystem>();
        var activeSections = new HashSet<string>();
        var activeButtons = new HashSet<ButtonKey>();
        var orderedTargets = new HashSet<NetEntity>();
        _targetDisplayOrder.Clear();

        var position = 0;
        foreach (var section in _sections)
        {
            if (!HasContent(section))
                continue;

            ReconcileSection(
                section,
                ContentContainer,
                string.Empty,
                false,
                position++,
                spriteSystem,
                activeSections,
                activeButtons,
                orderedTargets);
        }

        foreach (var key in _buttons.Keys.Where(key => !activeButtons.Contains(key)).ToArray())
        {
            var button = _buttons[key];
            button.Parent?.RemoveChild(button);
            _buttons.Remove(key);
        }

        foreach (var path in _sectionControls.Keys
                     .Where(path => !activeSections.Contains(path))
                     .OrderByDescending(path => path.Length)
                     .ToArray())
        {
            var collapsible = _sectionControls[path].Collapsible;
            collapsible.Parent?.RemoveChild(collapsible);
            _expansionStates.Remove(collapsible);
            _sectionControls.Remove(path);
        }

        UpdateVisibleButtons();
        UpdateVisibleCollapsibles();
    }

    private void ReconcileSection(
        RMCGhostTargetSection section,
        Container parent,
        string parentPath,
        bool isSubsection,
        int position,
        SpriteSystem spriteSystem,
        HashSet<string> activeSections,
        HashSet<ButtonKey> activeButtons,
        HashSet<NetEntity> orderedTargets)
    {
        var path = GetSectionPath(parentPath, section.Key);
        activeSections.Add(path);

        if (!_sectionControls.TryGetValue(path, out var control))
        {
            control = new RMCGhostTargetSectionControl(_resourceCache, isSubsection);
            _sectionControls[path] = control;
            _expansionStates[control.Collapsible] = section.IsExpandedByDefault;
            control.Heading.OnToggled += args =>
            {
                if (string.IsNullOrEmpty(_searchText))
                    _expansionStates[control.Collapsible] = args.Pressed;
            };
        }

        Reparent(control.Collapsible, parent);
        control.Collapsible.SetPositionInParent(position);
        control.Update(section, GetSectionTitle(section), CountAllEntries(section));

        var buttonPosition = 0;
        foreach (var targetId in section.Targets)
        {
            if (!_targets.TryGetValue(targetId, out var target))
                continue;

            if (orderedTargets.Add(targetId))
                _targetDisplayOrder.Add(targetId);

            var key = new ButtonKey(path, targetId);
            activeButtons.Add(key);
            if (!_buttons.TryGetValue(key, out var button))
            {
                button = new RMCGhostTargetButton(_resourceCache);
                button.TargetPressed += targetEntity => WarpClicked?.Invoke(targetEntity);
                _buttons[key] = button;
            }

            Reparent(button, control.Targets);
            button.SetPositionInParent(buttonPosition++);
            button.Update(target, spriteSystem, SectionUsesColoredTargets(section.Key.Kind));
            button.Visible = ButtonIsVisible(button);
        }

        var childPosition = 0;
        foreach (var child in section.Children)
        {
            if (!HasContent(child))
                continue;

            ReconcileSection(
                child,
                control.Children,
                path,
                true,
                childPosition++,
                spriteSystem,
                activeSections,
                activeButtons,
                orderedTargets);
        }
    }

    private bool HasContent(RMCGhostTargetSection section)
    {
        return section.Targets.Any(_targets.ContainsKey) ||
               section.Children.Any(HasContent);
    }

    private int CountAllEntries(RMCGhostTargetSection section)
    {
        var count = section.Targets.Count(_targets.ContainsKey);
        foreach (var child in section.Children)
            count += CountAllEntries(child);

        return count;
    }

    private static string GetSectionPath(string parentPath, RMCGhostTargetSectionKey key)
    {
        return $"{parentPath}/{(byte) key.Kind}:{key.Prototype}:{key.Entity}";
    }

    private static void Reparent(Control control, Container parent)
    {
        if (control.Parent == parent)
            return;

        control.Parent?.RemoveChild(control);
        parent.AddChild(control);
    }

    private static string GetSectionTitle(RMCGhostTargetSection section)
    {
        if (!string.IsNullOrEmpty(section.Title))
            return section.Title;

        return string.IsNullOrEmpty(section.TitleLocId.Id)
            ? string.Empty
            : Loc.GetString(section.TitleLocId);
    }

    private static bool SectionUsesColoredTargets(RMCGhostTargetSectionKind kind)
    {
        return kind switch
        {
            RMCGhostTargetSectionKind.Others or
            RMCGhostTargetSectionKind.Dead or
            RMCGhostTargetSectionKind.WarpPoints or
            RMCGhostTargetSectionKind.Ghosts => false,
            _ => true,
        };
    }

    private void UpdateGhostnadoButtonState()
    {
        GhostnadoButton.Disabled = GetMostFollowedEntry() == null;
        UpdateGhostnadoButtonColor();
    }

    private void WarpToMostFollowed()
    {
        if (GetMostFollowedEntry() is { } entry)
            WarpClicked?.Invoke(entry.Entity);
    }

    private void WarpToMostRelevantSearchResult()
    {
        if (string.IsNullOrEmpty(_searchText))
            return;

        NetEntity? mostRelevant = null;
        var bestMatchRank = int.MaxValue;
        var bestFollowerCount = -1;
        foreach (var targetId in _targetDisplayOrder)
        {
            if (!_targets.TryGetValue(targetId, out var entry))
                continue;

            var matchRank = GetSearchMatchRank(entry, _searchText);
            if (matchRank == int.MaxValue ||
                matchRank > bestMatchRank ||
                matchRank == bestMatchRank && entry.FollowerCount <= bestFollowerCount)
            {
                continue;
            }

            mostRelevant = targetId;
            bestMatchRank = matchRank;
            bestFollowerCount = entry.FollowerCount;
        }

        if (mostRelevant is { } target)
            WarpClicked?.Invoke(target);
    }

    private RMCGhostTargetEntry? GetMostFollowedEntry()
    {
        RMCGhostTargetEntry? mostFollowed = null;
        var mostFollowers = 0;
        foreach (var entry in _targets.Values)
        {
            if (entry.IsWarpPoint || entry.FollowerCount <= mostFollowers)
                continue;

            mostFollowed = entry;
            mostFollowers = entry.FollowerCount;
        }

        return mostFollowed;
    }

    private bool ButtonIsVisible(RMCGhostTargetButton button)
    {
        return EntryMatchesSearch(button.Entry);
    }

    private bool EntryMatchesSearch(RMCGhostTargetEntry entry)
    {
        return string.IsNullOrEmpty(_searchText) ||
               GetSearchMatchRank(entry, _searchText) != int.MaxValue;
    }

    private static int GetSearchMatchRank(RMCGhostTargetEntry entry, string searchText)
    {
        if (entry.DisplayName.Equals(searchText, StringComparison.OrdinalIgnoreCase))
            return 0;

        if (entry.DisplayName.StartsWith(searchText, StringComparison.OrdinalIgnoreCase))
            return 1;

        if (entry.DisplayName.Contains(searchText, StringComparison.OrdinalIgnoreCase))
            return 2;

        if (entry.DisplayJob?.Contains(searchText, StringComparison.OrdinalIgnoreCase) == true)
            return 3;

        return int.MaxValue;
    }

    private void UpdateVisibleButtons()
    {
        foreach (var button in _buttons.Values)
            button.Visible = ButtonIsVisible(button);
    }

    private void UpdateVisibleCollapsibles()
    {
        UpdateVisibleCollapsibles(ContentContainer);
    }

    private bool UpdateVisibleCollapsibles(Container container)
    {
        var anyVisible = false;
        var searchEmpty = string.IsNullOrEmpty(_searchText);
        foreach (var child in container.Children)
        {
            if (child is Collapsible collapsible)
            {
                var body = collapsible.Body as CollapsibleBody;
                var hasVisibleContent = body != null && UpdateVisibleCollapsibles(body);
                var visible = searchEmpty || hasVisibleContent;
                collapsible.Visible = visible;
                collapsible.BodyVisible = searchEmpty
                    ? _expansionStates.TryGetValue(collapsible, out var expanded) && expanded
                    : hasVisibleContent;
                anyVisible |= visible;
            }
            else if (child is RMCGhostTargetButton button)
            {
                anyVisible |= button.Visible;
            }
            else if (child is Container childContainer)
            {
                anyVisible |= UpdateVisibleCollapsibles(childContainer);
            }
        }

        return anyVisible;
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text.Trim();
        UpdateVisibleButtons();
        UpdateVisibleCollapsibles();
        GhostScroll.SetScrollValue(Vector2.Zero);
    }

    private void SetupGhostnadoButtonColors()
    {
        _ghostnadoButtonStyle = RMCGhostTargetStyles.CreateRoundedBox(_resourceCache, TguiGoodButtonDisabledColor);
        _ghostnadoButtonStyle.SetContentMarginOverride(StyleBox.Margin.Horizontal, 6);
        GhostnadoButton.StyleBoxOverride = _ghostnadoButtonStyle;
        GhostnadoButton.OnMouseEntered += _ => UpdateGhostnadoButtonColor();
        GhostnadoButton.OnMouseExited += _ => UpdateGhostnadoButtonColor();
        GhostnadoButton.OnButtonDown += _ => UpdateGhostnadoButtonColor(pressed: true);
        GhostnadoButton.OnButtonUp += _ => UpdateGhostnadoButtonColor();
    }

    private void SetupRefreshButtonHover()
    {
        var styleBox = RMCGhostTargetStyles.CreateRoundedBox(_resourceCache, Color.Transparent);
        styleBox.SetContentMarginOverride(StyleBox.Margin.All, 0);
        RefreshButton.StyleBoxOverride = styleBox;
        RefreshButton.OnMouseEntered += _ => styleBox.Modulate = TguiTransparentButtonHoverColor;
        RefreshButton.OnMouseExited += _ => styleBox.Modulate = Color.Transparent;
    }

    private void SetupSearchBarStyle()
    {
        var border = RMCGhostTargetStyles.CreateRoundedBox(_resourceCache, Color.FromHex("#4b4b4b"));
        border.SetContentMarginOverride(StyleBox.Margin.All, 1);
        SearchBorder.PanelOverride = border;

        var background = RMCGhostTargetStyles.CreateRoundedBox(
            _resourceCache,
            Color.FromHex("#111111"),
            inset: true);
        background.SetContentMarginOverride(StyleBox.Margin.Horizontal, 5);
        background.SetContentMarginOverride(StyleBox.Margin.Vertical, 2);
        SearchBar.StyleBoxOverride = background;
    }

    private void UpdateGhostnadoButtonColor(bool pressed = false)
    {
        _ghostnadoButtonStyle.Modulate = GhostnadoButton.Disabled
            ? TguiGoodButtonDisabledColor
            : pressed || GhostnadoButton.IsHovered
                ? TguiGoodButtonHoverColor
                : TguiGoodButtonColor;
    }

    private void SetWindowBackgroundColor()
    {
        if (GetChild(0) is not PanelContainer windowPanel)
            return;

        windowPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#262626"),
            BorderColor = Color.FromHex("#444444"),
            BorderThickness = new Thickness(1),
        };
    }

    private readonly record struct ButtonKey(string SectionPath, NetEntity Target);
}
