using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared._RMC14.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.UserInterface.Systems.Ghost.Controls;

[GenerateTypedNameReferences]
public sealed partial class RMCGhostTargetWindow : DefaultWindow
{
    [Dependency] private readonly EntityManager _entityManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private List<RMCGhostTargetSection> _sections = new();
    private readonly Dictionary<Collapsible, RMCGhostTargetSection> _collapsibleSections = new();
    private readonly Dictionary<Button, string> _buttonSearchTexts = new();
    private string _searchText = string.Empty;

    private static readonly Color TguiGoodButtonColor = Color.FromHex("#4e9121");
    private static readonly Color TguiGoodButtonHoverColor = Color.FromHex("#9ade6d");
    private static readonly Color TguiTransparentButtonHoverColor = Color.FromHex("#737373");
    private const float HoverLightnessPercent = 0.1f;

    public event Action<NetEntity>? WarpClicked;
    public event Action? OnRefreshClicked;

    public RMCGhostTargetWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        SetWindowBackgroundColor();
        SearchBar.OnTextChanged += OnSearchTextChanged;

        GhostnadoButton.Disabled = true;
        GhostnadoButton.OnPressed += _ => WarpToMostFollowed();
        RefreshButton.OnPressed += _ => OnRefreshClicked?.Invoke();
        SetupGhostnadoButtonColors();
        SetupRefreshButtonHover();
    }

    private void SetupGhostnadoButtonColors()
    {
        if (GhostnadoButton.StyleBoxOverride is not StyleBoxTexture styleBox)
            return;

        styleBox.Modulate = TguiGoodButtonColor;

        GhostnadoButton.OnMouseEntered += _ =>
        {
            styleBox.Modulate = TguiGoodButtonHoverColor;
        };

        GhostnadoButton.OnMouseExited += _ =>
        {
            styleBox.Modulate = TguiGoodButtonColor;
        };

        GhostnadoButton.OnButtonDown += _ =>
        {
            styleBox.Modulate = TguiGoodButtonHoverColor;
        };

        GhostnadoButton.OnButtonUp += _ =>
        {
            styleBox.Modulate = GhostnadoButton.IsHovered
                ? TguiGoodButtonHoverColor
                : TguiGoodButtonColor;
        };
    }

    private void SetupRefreshButtonHover()
    {
        var styleBox = new StyleBoxFlat
        {
            BackgroundColor = Color.Transparent,
        };
        RefreshButton.StyleBoxOverride = styleBox;

        RefreshButton.OnMouseEntered += _ =>
        {
            styleBox.BackgroundColor = TguiTransparentButtonHoverColor;
        };

        RefreshButton.OnMouseExited += _ =>
        {
            styleBox.BackgroundColor = Color.Transparent;
        };
    }

    private void SetWindowBackgroundColor()
    {
        if (GetChild(0) is not PanelContainer windowPanel)
            return;

        windowPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#262626"),
            BorderColor = Color.FromHex("#444444"),
            BorderThickness = new Thickness(1),
        };
    }

    public void UpdateSections(IEnumerable<RMCGhostTargetSection> sections)
    {
        _sections = sections
            .OrderBy(section => section.Index)
            .ToList();
        UpdateGhostnadoButtonState();
    }

    private void UpdateGhostnadoButtonState()
    {
        GhostnadoButton.Disabled = GetMostFollowedEntry() == null;
    }

    private void WarpToMostFollowed()
    {
        if (GetMostFollowedEntry() is not { } entry)
            return;

        WarpClicked?.Invoke(entry.Entity);
    }

    private RMCGhostTargetEntry? GetMostFollowedEntry()
    {
        RMCGhostTargetEntry? mostFollowed = null;
        var mostFollowers = 0;

        foreach (var entry in EnumerateEntries(_sections))
        {
            if (entry.IsWarpPoint || entry.FollowerCount <= mostFollowers)
                continue;

            mostFollowed = entry;
            mostFollowers = entry.FollowerCount;
        }

        return mostFollowed;
    }

    private static IEnumerable<RMCGhostTargetEntry> EnumerateEntries(IEnumerable<RMCGhostTargetSection> sections)
    {
        foreach (var section in sections)
        {
            foreach (var entry in section.Entries)
                yield return entry;

            foreach (var entry in EnumerateEntries(section.Children))
                yield return entry;
        }
    }

    public void Populate()
    {
        _collapsibleSections.Clear();
        _buttonSearchTexts.Clear();
        ContentContainer.DisposeAllChildren();
        AddContent();
        UpdateVisibleButtons();
        UpdateVisibleCollapsibles();
    }

    private void AddContent()
    {
        var spriteSystem = _entityManager.System<SpriteSystem>();

        foreach (var section in _sections.OrderBy(section => section.Index))
        {
            if (!HasContent(section))
                continue;

            AddSectionContent(section, ContentContainer, spriteSystem, false);
        }
    }

    private static bool HasContent(RMCGhostTargetSection section)
    {
        return section.Entries.Count > 0 || section.Children.Any(HasContent);
    }

    private void AddSectionContent(
        RMCGhostTargetSection section,
        Container parent,
        SpriteSystem spriteSystem,
        bool isSubsection)
    {
        var heading = CreateHeading(section, spriteSystem, CountAllEntries(section));
        var body = new CollapsibleBody
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 3, 0, 0),
        };

        var mainContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = false,
        };

        if (section.Entries.Count > 0)
        {
            var buttonGrid = CreateGroupContainer(body);
            foreach (var entry in section.Entries)
            {
                var button = CreateWarpButton(entry, spriteSystem, ButtonIsVisible);
                buttonGrid.AddChild(button);
            }

            mainContainer.AddChild(buttonGrid);
        }

        if (section.Children.Count > 0)
        {
            var childrenBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalExpand = false,
            };

            foreach (var child in section.Children.OrderBy(child => child.Index))
            {
                if (HasContent(child))
                    AddSectionContent(child, childrenBox, spriteSystem, true);
            }

            if (childrenBox.ChildCount > 0)
                mainContainer.AddChild(childrenBox);
        }

        body.AddChild(mainContainer);

        var collapsible = CreateCollapsible(heading, body, section, isSubsection);
        parent.AddChild(collapsible);

        _collapsibleSections[collapsible] = section;
    }

    private static int CountAllEntries(RMCGhostTargetSection section)
    {
        var count = section.Entries.Count;
        foreach (var child in section.Children)
            count += CountAllEntries(child);

        return count;
    }

    private CollapsibleHeading CreateHeading(RMCGhostTargetSection section, SpriteSystem spriteSystem, int totalCount)
    {
        var heading = new CollapsibleHeading($"{GetSectionTitle(section)} - ({totalCount})");
        heading.Label.StyleClasses.Add(StyleNano.StyleClassLabelSmall);
        heading.Label.FontOverride = _resourceCache.NotoStack("Bold", 10);
        heading.StyleBoxOverride = new StyleBoxTexture
        {
            Texture = spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/Nano/rounded_button.svg.96dpi.png"))),
            Modulate = section.HeaderColor,
            PatchMarginTop = 5,
            PatchMarginBottom = 5,
            PatchMarginLeft = 5,
            PatchMarginRight = 5,
            ContentMarginTopOverride = 3,
            ContentMarginLeftOverride = 5,
            ContentMarginRightOverride = 5,
            ContentMarginBottomOverride = 3,
            Padding = new Thickness(2),
        };

        heading.OnMouseEntered += _ =>
        {
            if (heading.StyleBoxOverride is StyleBoxTexture styleBox)
                styleBox.Modulate = AdjustLightness(styleBox.Modulate, HoverLightnessPercent);
        };

        heading.OnMouseExited += _ =>
        {
            if (heading.StyleBoxOverride is StyleBoxTexture styleBox)
                styleBox.Modulate = section.HeaderColor;
        };

        return heading;
    }

    private static string GetSectionTitle(RMCGhostTargetSection section)
    {
        if (!string.IsNullOrEmpty(section.Title))
            return section.Title;

        return string.IsNullOrEmpty(section.TitleLocId.Id)
            ? string.Empty
            : Loc.GetString(section.TitleLocId);
    }

    private static GridContainer CreateGroupContainer(CollapsibleBody body)
    {
        var groupContainer = new GridContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        body.OnResized += () =>
        {
            if (body.Width > 0)
                groupContainer.MaxGridWidth = body.Width;
        };

        return groupContainer;
    }

    private static string TruncateText(string text, int maxLength)
    {
        return text.Length > maxLength
            ? text[..maxLength] + "..."
            : text;
    }

    private Button CreateWarpButton(
        RMCGhostTargetEntry entry,
        SpriteSystem spriteSystem,
        Func<Button, bool> isVisibleCheck)
    {
        var buttonContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
            HorizontalExpand = true,
        };

        if (!entry.IsWarpPoint)
            AddIconsToButtonContainer(buttonContainer, entry, spriteSystem);

        var label = new Label
        {
            Text = TruncateText(entry.DisplayName, 15),
            HorizontalAlignment = Control.HAlignment.Left,
            ClipText = false,
            StyleClasses = { "LabelSmall" },
        };
        buttonContainer.AddChild(label);

        if (!entry.IsWarpPoint)
            AddGhostCounter(buttonContainer, entry.FollowerCount);

        var button = new Button
        {
            Name = entry.DisplayName,
            StyleBoxOverride = new StyleBoxTexture
            {
                Texture = spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/Nano/rounded_button.svg.96dpi.png"))),
                PatchMarginTop = 5,
                PatchMarginBottom = 5,
                PatchMarginLeft = 5,
                PatchMarginRight = 5,
                ContentMarginTopOverride = 3,
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginBottomOverride = 3,
                Padding = new Thickness(2),
            },
        };

        _buttonSearchTexts[button] = entry.SearchText;

        if (!entry.IsWarpPoint)
            button.ToolTip = GetTooltip(entry);

        button.AddChild(buttonContainer);
        button.OnPressed += _ => WarpClicked?.Invoke(entry.Entity);
        button.Visible = isVisibleCheck(button);

        button.OnMouseEntered += _ =>
        {
            if (button.StyleBoxOverride is StyleBoxTexture styleBox)
                styleBox.Modulate = AdjustLightness(styleBox.Modulate, HoverLightnessPercent);
        };

        button.OnMouseExited += _ =>
        {
            if (button.StyleBoxOverride is StyleBoxTexture styleBox)
                styleBox.Modulate = Color.White;
        };

        button.OnButtonDown += _ =>
        {
            if (button.StyleBoxOverride is StyleBoxTexture styleBox)
                styleBox.Modulate = Color.FromHex("#3e6c45");
        };

        button.OnButtonUp += _ =>
        {
            if (button.StyleBoxOverride is StyleBoxTexture styleBox)
                styleBox.Modulate = Color.White;
        };

        return button;
    }

    private static void AddIconsToButtonContainer(
        BoxContainer buttonContainer,
        RMCGhostTargetEntry entry,
        SpriteSystem spriteSystem)
    {
        if (entry.HealthIcon != null)
        {
            var healthIcon = new TextureRect
            {
                HorizontalAlignment = Control.HAlignment.Center,
                VerticalAlignment = Control.VAlignment.Center,
                Texture = spriteSystem.Frame0(entry.HealthIcon),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MinSize = new Vector2(13, 13),
                MaxSize = new Vector2(13, 13),
                Margin = new Thickness(0, 0, 4, 0),
            };
            buttonContainer.AddChild(healthIcon);
        }

        if (entry.TacticalIcon == null)
            return;

        var iconPanel = new PanelContainer
        {
            Margin = new Thickness(0, 0, 4, 0),
        };

        if (entry.TacticalBackground != null)
        {
            var backgroundView = new TextureRect
            {
                HorizontalAlignment = Control.HAlignment.Center,
                VerticalAlignment = Control.VAlignment.Center,
                Texture = spriteSystem.Frame0(entry.TacticalBackground),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MinSize = new Vector2(16, 16),
                MaxSize = new Vector2(16, 16),
            };
            iconPanel.AddChild(backgroundView);
        }

        var iconView = new TextureRect
        {
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
            Texture = spriteSystem.Frame0(entry.TacticalIcon),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            MinSize = new Vector2(16, 16),
            MaxSize = new Vector2(16, 16),
        };
        iconPanel.AddChild(iconView);

        buttonContainer.AddChild(iconPanel);
    }

    private void AddGhostCounter(BoxContainer buttonContainer, int followerCount)
    {
        if (followerCount <= 0)
            return;

        var ghostCounter = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalAlignment = Control.HAlignment.Right,
            VerticalAlignment = Control.VAlignment.Center,
            Margin = new Thickness(2, 0, 0, 0),
        };

        var ghostIcon = new TextureRect
        {
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
            TexturePath = "/Textures/_RMC14/Interface/ghost_counter.svg.96dpi.png",
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            MinSize = new Vector2(13, 13),
            MaxSize = new Vector2(13, 13),
        };
        ghostCounter.AddChild(ghostIcon);

        var ghostCount = new Label
        {
            Text = followerCount.ToString(),
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
            Margin = new Thickness(2, 0, 0, 0),
            StyleClasses = { "LabelSmall" },
        };
        ghostCounter.AddChild(ghostCount);

        buttonContainer.AddChild(ghostCounter);
    }

    private static string GetTooltip(RMCGhostTargetEntry entry)
    {
        var tooltipText = $"{Loc.GetString("rmc-ghost-target-window-tooltip-name", ("name", entry.DisplayName))}";
        if (entry.DisplayJob != null)
        {
            tooltipText += entry.TooltipJobKind == RMCGhostTargetTooltipJobKind.Caste
                ? $"\n{Loc.GetString("rmc-ghost-target-window-tooltip-caste", ("caste", entry.DisplayJob))}"
                : $"\n{Loc.GetString("rmc-ghost-target-window-tooltip-job", ("job", entry.DisplayJob))}";
        }

        if (entry.HealthPercent >= 0)
            tooltipText += $"\n{Loc.GetString("rmc-ghost-target-window-tooltip-health", ("health", entry.HealthPercent))}";

        return tooltipText;
    }

    private Collapsible CreateCollapsible(
        CollapsibleHeading heading,
        CollapsibleBody body,
        RMCGhostTargetSection section,
        bool isSubsection = false)
    {
        var collapsible = new Collapsible(heading, body)
        {
            Margin = isSubsection ? new Thickness(10, 4, 0, 4) : new Thickness(0, 4),
            HorizontalExpand = true,
        };

        if (section.IsExpandedByDefault)
            collapsible.BodyVisible = true;

        return collapsible;
    }

    private bool ButtonIsVisible(Button button)
    {
        if (string.IsNullOrEmpty(_searchText))
            return true;

        return _buttonSearchTexts.TryGetValue(button, out var searchText) &&
               searchText.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
    }

    private void UpdateVisibleButtons()
    {
        UpdateVisibleButtonsRecursive(ContentContainer);
    }

    private void UpdateVisibleButtonsRecursive(Container container)
    {
        foreach (var child in container.Children)
        {
            if (child is Collapsible collapsible)
            {
                var body = collapsible.GetChild(1) as CollapsibleBody;
                if (body != null)
                    UpdateVisibleButtonsRecursive(body);
            }
            else if (child is Button button)
            {
                button.Visible = ButtonIsVisible(button);
            }
            else if (child is Container childContainer)
            {
                UpdateVisibleButtonsRecursive(childContainer);
            }
        }
    }

    private void UpdateVisibleCollapsibles()
    {
        UpdateVisibleCollapsibles(ContentContainer);
    }

    private bool UpdateVisibleCollapsibles(Container container)
    {
        var anyVisible = false;
        var searchEmpty = string.IsNullOrEmpty(_searchText);

        foreach (var child in container.Children)
        {
            if (child is Collapsible collapsible)
            {
                var body = collapsible.GetChild(1) as CollapsibleBody;
                var hasVisibleContent = body != null && UpdateVisibleCollapsibles(body);
                var visible = searchEmpty || hasVisibleContent;
                collapsible.Visible = visible;
                collapsible.BodyVisible = searchEmpty
                    ? _collapsibleSections.TryGetValue(collapsible, out var section) && section.IsExpandedByDefault
                    : hasVisibleContent;

                if (visible)
                    anyVisible = true;
            }
            else if (child is Button button)
            {
                anyVisible |= ButtonIsVisible(button);
            }
            else if (child is Container childContainer)
            {
                anyVisible |= UpdateVisibleCollapsibles(childContainer);
            }
        }

        return anyVisible;
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text;

        UpdateVisibleButtons();
        UpdateVisibleCollapsibles();
        GhostScroll.SetScrollValue(Vector2.Zero);
    }

    private static Color AdjustLightness(Color color, float percent)
    {
        var hsv = Color.ToHsv(color);
        if (percent > 0)
            hsv.Z = Math.Min(hsv.Z * (1f + percent), 1f);
        else
            hsv.Z *= 1f + percent;

        return Color.FromHsv(hsv);
    }
}
