using Robust.Client.AutoGenerated;
using Content.Client.Message;
using Content.Shared._RMC14.Dropship.AttachmentPoint;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Dropship.Weapon;

[GenerateTypedNameReferences]
public sealed partial class DropshipFiremissionEditScreen : PanelContainer
{
    private const int FontSize = 10;
    private const int MaxTiming = 12;
    private const int MinOffset = 0;
    private const int InfoColumnAmount = 2;

    private readonly Dictionary<int, List<DropshipFiremissionOffsetButton>> _buttonsByRow = new();

    public DropshipFiremissionEditScreen()
    {
        RobustXamlLoader.Load(this);

        PopulateButtonsAndRowNumbers(DropshipWeaponPointLocation.PortFore);
    }

    private void PopulateButtonsAndRowNumbers(DropshipWeaponPointLocation? weaponLocation = null)
    {
        CreateHeader("Offset");

        // Offsets change depending on weapon side
        var start = weaponLocation is null or DropshipWeaponPointLocation.StarboardFore or DropshipWeaponPointLocation.StarboardWing ? MinOffset : -OffsetGrid.Columns + InfoColumnAmount + 1;
        var end = weaponLocation is null or DropshipWeaponPointLocation.StarboardFore or DropshipWeaponPointLocation.StarboardWing ? OffsetGrid.Columns - InfoColumnAmount : MinOffset;

        var unsetFirst = start >= 0;

        if (unsetFirst)
            CreateHeader("UNSET");

        for (var i = start; i <= end; i++)
        {
            CreateHeader(i.ToString());
        }

        if (!unsetFirst)
            CreateHeader("UNSET");

        // First row is headers, start adding from row 1
        for (var row = 1; row <= MaxTiming; row++)
        {
            // Column 0: row number
            var rowLabel = new RichTextLabel
            {
                HorizontalAlignment = HAlignment.Right,
            };

            rowLabel.SetMarkupPermissive($"[font size={FontSize}][color=#00FF36]{row.ToString()}[/color][/font]");
            OffsetGrid.AddChild(rowLabel);

            // Starboard side of the ship has positive offsets and "unset" column on the left side
            if (weaponLocation is null or DropshipWeaponPointLocation.StarboardFore or DropshipWeaponPointLocation.StarboardWing)
            {
                CreateButton(row, null, true);
                for (var offset = MinOffset; offset < OffsetGrid.Columns - InfoColumnAmount; offset++)
                {
                    CreateButton(row, offset);
                }
            }
            // Port side of the ship has negative offsets and "unset" column on the right side
            else
            {
                for (var offset = -OffsetGrid.Columns + InfoColumnAmount; offset < MinOffset; offset++)
                {
                    CreateButton(row, offset + 1);
                }
                CreateButton(row, null, true);
            }
        }
    }

    private void SelectOffset(int row, int? offset, DropshipFiremissionOffsetButton button)
    {
        if (!_buttonsByRow.TryGetValue(row, out var rowButtons))
            return;

        foreach (var rowButton in rowButtons)
        {
            if (!rowButton.Pressed || rowButton == button)
                continue;

            rowButton.SetClickPressed(false);
        }

        button.SetClickPressed(true);
        // TODO: Add  selection logic here, raise event etc
        Logger.Info($"Selected row {row}, offset {offset}");
    }

    private void CreateButton(int row, int? offset, bool pressed = false)
    {
        var text = offset.HasValue ? offset.ToString() : "[ - ]";
        var button = new DropshipFiremissionOffsetButton();
        button.RichLabel.SetMarkupPermissive($"[font size={FontSize}][color=#00FF36]{text}[/color][/font]");

        button.SetOnPressed(_ => SelectOffset(row, offset, button));
        if (pressed)
            button.SetClickPressed(pressed);
        OffsetGrid.AddChild(button);

        if (!_buttonsByRow.TryGetValue(row, out var list))
        {
            list = [];
            _buttonsByRow[row] = list;
        }

        list.Add(button);
    }

    private void CreateHeader(string header)
    {
        var label = new RichTextLabel
        {
            HorizontalAlignment = HAlignment.Center,
        };
        label.SetMarkupPermissive($"[font size={FontSize}][color=#00FF36]{header}[/color][/font]");
        OffsetGrid.AddChild(label);
    }
}
