- type: job
  parent: CMSurvivor
  id: CMSurvivorHost
  name: cm-job-name-survivor
  description: cm-job-description-survivor
  startingGear: RMCGearHostSurvivorBase
  spawnMenuRoleName: Civilian Survivor (Xenonid Host)

- type: startingGear
  parent: RMCGearSurvivorBaseNoBackpack
  id: RMCGearHostSurvivorBase
  equipment:
    pocket1: RMCPouchSurvivalFillRadioOff

