- type: job
  parent: CMSurvivorFiorinaRiotOfficer
  id: RMCSurvivorFiorinaRiotInProgressCMBRiotControlMedicalTechnician
  name: rmc-job-name-bureau-riot-control-medical-technician
  description: cm-job-description-survivor
  playTimeTracker: CMJobSurvivorSecurity
  startingGear: RMCGearSurvivorFiorinaRiotInProgressCMBMedicalTechnician
  accessGroups:
  - ColonistSec
  ranks:
    RMCRankCMBMedicalTechnician: []
  spawnMenuRoleName: CMB Medical Technician (Fiorina Special Survivor)
  icon: "RMCJobIconCMBRiotInProgressMedicalTechnician"
  special:
  - !type:AddComponentSpecial
    components:
    - type: Language
      spokenLanguages:
      - Japanese
      - English
      understoodLanguages:
      - Japanese
      - English
      currentLanguage: English
      defaultLanguage: English
    - type: Skills
      preset: RMCSkillPresetSurvivorRiotControlMedicalTechnician
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Bureau
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetRiotInProgressCMBSpecialist
    - type: JobPrefix
      prefix: rmc-job-prefix-bureau-riot-control-medical-technician
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: medic
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_cmb
  greeting: rmc-job-greeting-riot-in-progress-CMB

- type: startingGear
  id: RMCGearSurvivorFiorinaRiotInProgressCMBMedicalTechnician
  equipment:
    belt: CMBeltMedicalFilled
    jumpsuit: RMCSwatCMBUniformSpearhead
    id: RMCIDCardCMBDeputySurvivor
    back: CMSatchelSecuritySurvivorFill
    outerClothing: RMCArmorPMCRiotCMB
    ears: RMCHeadsetDistressBureauDamaged
    eyes: RMCGlassesSecurityBlue
    gloves: RMCHandsVeteran
    shoes: RMCBootsPMCFilled
    pocket1: RMCPouchSurvivalBlackFilled
  storage:
    belt:
    - CMDefibrillator
    - CMHealthAnalyzer

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorFiorinaRiotInProgressCMBRiotControlMedicalTechnician
  name: cmb riot control medical technician spawn point
  suffix: special survivor, fiorina riot in progress
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorFiorinaRiotInProgressCMBRiotControlMedicalTechnician
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconCMBRiotInProgressMedicalTechnician
  icon:
    sprite: _RMC14/Interface/job_icons/CMB.rsi
    state: cmb_medt

- type: entity # ILRC Peacekeeper preset but replaced with statistically identical CMB gear
  id: RMCSurvivorPresetRiotInProgressCMBSpecialist
  name: riot in progress CMB specialist preset
  categories: [ HideSpawnMenu ]
  components:
    - type: EntityPreset
      primaryWeapons:
        - [ RMCPouchMagazineFilledM16, WeaponRifleM16, RMCArmorHelmetM10CMB ]
        - [ RMCPouchMagazineFilledM16, WeaponRifleM16, RMCArmorHelmetM10CMB ]
        - [ RMCPouchMagazineFilledM16, WeaponRifleM16, RMCArmorHelmetM10CMB ]
        - [ RMCPouchMagazineFilledM16, WeaponRifleM16, RMCArmorHelmetM10CMB ]
        - [ RMCPouchMagazineFilledM16, WeaponRifleM16, RMCArmorHelmetM10CMB ]
        - [ RMCPouchMagazineFilledM16, WeaponRifleM16, RMCArmorHelmetM10CMB ]
        - [ RMCPouchShotgunFilledBeanbag, RMCWeaponShotgunM890Riot, CMHeadBeretCMB ]
        - [ RMCPouchExplosiveFilledHIRR, RMCWeaponLauncherM85A1, CMHeadBeretCMB ]
        - [ RMCPouchMagazineFilledMP5, WeaponSMGMP5, RMCMotionDetectorCompact, RMCExplosiveBreachingCharge, RMCArmorHelmetM10CMB ]
        - [ RMCPouchMagazineFilledMP5, WeaponSMGMP5, RMCMotionDetectorCompact, RMCExplosiveBreachingCharge, RMCArmorHelmetM10CMB ]
      primaryWeaponChance: 1
