- type: job
  parent: RMCSyntheticColony
  id: RMCSyntheticColonyHybrisaExecBodyguard
  startingGear: RMCGearSyntheticColonistHybrisaExecBodyguard
  spawnMenuRoleName: Executive Bodyguard Synth (Hybrisa Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Language
      spokenLanguages:
      - English
      - French
      - Japanese
      - Russian
      - German
      - Chinese
      - Spanish
      understoodLanguages:
      - English
      - French
      - Japanese
      - Russian
      - German
      - Chinese
      - Spanish
      currentLanguage: English
      defaultLanguage: English
    - type: LanguageLearning
      learnableLanguages:
      - Xeno
      firstContactLanguages:
      - Xeno
      languages:
        Xeno:
          initialBoostedWordCount: 18
          initialBoostedWordComprehension: 0.4
      comprehensionThreshold: 0.8
      learningRange: 8.0
      baseWordLearningRate: 0.05
    - type: DemoSpecWhitelist
    - type: GrenadeSpecWhitelist
    - type: ScoutWhitelist
    - type: SniperWhitelist
    - type: PyroWhitelist
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: MeleeWeapon
      soundHit:
        path: /Audio/_RMC14/Weapons/synthpunch1.ogg
        params:
          variation: 0.15
          volume: -1
      angle: 30
      animation: WeaponArcFist
      attackRate: 1
      damage:
        types:
          Blunt: 35
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetHybrisaSynthExecBodyguard
    - type: Synth
  useLoadoutOfJob: RMCSyntheticColony # for inheritance

- type: startingGear
  parent: RMCGearSyntheticColonistBase
  id: RMCGearSyntheticColonistHybrisaExecBodyguard
  equipment:
    outerClothing: RMCHazardVestBlack
  inhand:
    - RMCScabbardMacheteFilled

- type: entity
  id: RMCSurvivorPresetHybrisaSynthExecBodyguard
  name: survivor synth hybrisa executive bodyguard preset
  categories: [ HideSpawnMenu ] # Todo random research notes, telebaton in backpack
  components:
  - type: EntityPreset
    randomOutfits:
    - [ RMCJumpsuitLiaisonExpensiveSuitDropPouch, RMCSatchelBlack, RMCBootsCorporate ]
    - [ RMCJumpsuitLiaisonExpensiveSuitBrownDropPouch, RMCSatchelBlack, CMBootsBrownFilled ]
    - [ RMCJumpsuitLiaisonExpensiveSuitJacketDropPouch, CMSatchelSecureStandard, RMCBootsPMCFilled ]
    - [ RMCJumpsuitLiaisonExpensiveSuitBrownJacketDropPouch, CMSatchelSecureStandard, RMCBootsCorporate ]
    - [ RMCJumpsuitLiaisonExpensiveSuitJacketOnlyDropPouch, RMCSatchelNorm, RMCBootsCorporate ]
    randomStartingGear:
      eyes:
      - CMGlassesSecurity
      - RMCGlassesSecurityBlue
