- type: job
  parent: RMCSyntheticColony
  id: RMCSyntheticColonyHybrisaExecBodyguard
  startingGear: RMCGearSyntheticColonistHybrisaExecBodyguard
  spawnMenuRoleName: Executive Bodyguard Synth (Hybrisa Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Language
      preset: RMCLanguagePresetSynthColonist
    - type: LanguageLearning
      preset: RMCLanguageLearningPresetSynthColonist
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetHybrisaSynthExecBodyguard
    - type: Synth
  useLoadoutOfJob: RMCSyntheticColony # for inheritance

- type: startingGear
  parent: RMCGearSyntheticColonistBase
  id: RMCGearSyntheticColonistHybrisaExecBodyguard
  equipment:
    outerClothing: RMCHazardVestBlack
  inhand:
    - RMCScabbardMacheteFilled

- type: entity
  id: RMCSurvivorPresetHybrisaSynthExecBodyguard
  name: survivor synth hybrisa executive bodyguard preset
  categories: [ HideSpawnMenu ] # Todo random research notes, telebaton in backpack
  components:
  - type: EntityPreset
    randomOutfits:
    - [ RMCJumpsuitLiaisonExpensiveSuitDropPouch, RMCSatchelBlack, RMCBootsCorporate ]
    - [ RMCJumpsuitLiaisonExpensiveSuitBrownDropPouch, RMCSatchelBlack, CMBootsBrownFilled ]
    - [ RMCJumpsuitLiaisonExpensiveSuitJacketDropPouch, CMSatchelSecureStandard, RMCBootsPMCFilled ]
    - [ RMCJumpsuitLiaisonExpensiveSuitBrownJacketDropPouch, CMSatchelSecureStandard, RMCBootsCorporate ]
    - [ RMCJumpsuitLiaisonExpensiveSuitJacketOnlyDropPouch, RMCSatchelNorm, RMCBootsCorporate ]
    randomStartingGear:
      eyes:
      - CMGlassesSecurity
      - RMCGlassesSecurityBlue
