- type: job
  parent: CMBureauDeputy
  id: CMBureauRiotEngineer
  access: [ CMAccessERT ]
  name: rmc-job-name-bureau-riot-control-engineer
  playTimeTracker: RMCJobBureauRiotEngineer
  startingGear: RMCGearBureauRiotEngineer
  spawnMenuRoleName: CMB Riot Control Breaching Technician

- type: entity
  parent: RMCRandomHumanoidBureauDeputy
  id: RMCRandomHumanoidBureauRiotEngineer
  name: bureau ghost role riot control engineer
  suffix: Spawner, Player, Friendly, Riot
  components:
  - type: RandomHumanoidSpawner
    settings: RMCBureauRiotEngineer

- type: randomHumanoidSettings
  parent: RMCBureauDeputy
  id: RMCBureauRiotEngineer
  components:
  - type: GhostRole
    name: rmc-ghost-name-bureau-riot-control-engineer
    job: CMBureauRiotEngineer
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobMilitaryPolice
      time: 18000 # 5 Hours
    - !type:RoleTimeRequirement
      role: CMJobCombatTech
      time: 18000 # 5 Hours

- type: startingGear
  id: RMCGearBureauRiotEngineer
  equipment:
    head: RMCArmorHelmetM10CMBVisorSWAT
    mask: RMCMaskSWAT
    eyes: RMCGlassesHUDSecurity
    ears: RMCHeadsetDistressBureau
    back: RMCSatchelLightpackWelderBlack
    gloves: RMCHandsVeteran
    jumpsuit: RMCSwatCMBUniform
    outerClothing: RMCArmorM4RMedium
    belt: CMBeltUtilityCombatFilled
    shoes: RMCBootsPMCFilled
    id: RMCIDCardCMBDeputy
    pocket1: RMCPouchToolsFill
    pocket2: RMCPouchConstructionFillFull
    suitstorage: RMCWeaponRifleM16A5
  storage:
    back:
    - RMCExplosiveBreachingChargeRubber
    - RMCExplosiveBreachingChargeRubber
    - CMSheetMetal50
    - CMSheetPlasteel30
    - CMCrowbar
    - RMCHandheldDistressBeaconCMB

- type: playTimeTracker
  id: RMCJobBureauRiotEngineer
