using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.GameObjects;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.TacticalMap.UI;

[GenerateTypedNameReferences]
public sealed partial class TacticalMapOverlayLegendPopup : Popup
{
    private static readonly ResPath AreaInfoRsiPath = new("/Textures/_RMC14/Structures/Machines/ceiling.rsi");

    public TacticalMapOverlayLegendPopup()
    {
        RobustXamlLoader.Load(this);
        var spriteSystem = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();

        if (Background.PanelOverride is StyleBoxFlat box)
        {
            box.BackgroundColor = Color.FromHex("#0B0F14").WithAlpha(0.75f);
            box.BorderColor = Color.FromHex("#0B0F14").WithAlpha(0.1f);
            box.BorderThickness = new Thickness(1);
        }

        Roof0Icon.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(AreaInfoRsiPath, "roof0"));
        Roof1Icon.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(AreaInfoRsiPath, "roof1"));
        Roof2Icon.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(AreaInfoRsiPath, "roof2"));
        Roof3Icon.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(AreaInfoRsiPath, "roof3"));
        Roof4Icon.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(AreaInfoRsiPath, "roof4"));

        UserInterfaceManager.ModalRoot.AddChild(this);
    }
}
