using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.ERT;

[GenerateTypedNameReferences]
/// <summary>
/// Static frame for the admin ERT dispatch window.
/// </summary>
public sealed partial class RMCERTAdminWindow : FancyWindow
{
    public RMCERTAdminWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("rmc-ert-admin-window-title");
        HeaderLabel.Text = Loc.GetString("rmc-ert-admin-window-header");
        Tabs.SetTabTitle(0, Loc.GetString("rmc-ert-admin-tab-requests"));
        Tabs.SetTabTitle(1, Loc.GetString("rmc-ert-admin-tab-force"));
    }
}
