using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Lobby;

[GenerateTypedNameReferences]
public sealed partial class JoinXenoWindow : DefaultWindow
{
    public JoinXenoWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
