- type: job
  parent: RMCSurvivorTyrargoBase
  id: RMCSurvivorTyrargoRifleman
  name: cm-job-name-rifleman
  icon: "RMCJobIconTyrargoRifleman"
  spawnMenuRoleName: UNMC Rifleman (Tyrargo Rift Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetTyrargoTrooper
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: private
    - type: IntelRescueSurvivorObjective
    - type: AssignSquad
      whitelist:
        tags:
        - RMCSquadUNMC
    - type: JobPrefix
      prefix: cm-job-prefix-rifleman
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetTyrargoSurvivorFull
  hidden: true

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointTyrargoRifleman
  name: tyrargo marine rifleman spawn point
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorTyrargoRifleman
  - type: Sprite
    state: marine_spawn

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconTyrargoRifleman
  icon:
    sprite: _RMC14/Interface/job_icons/UNMC/tyrargo.rsi
    state: hudsquad_trpr
