- type: job
  parent: RMCSurvivorTyrargoBase
  id: RMCSurvivorTyrargoMarksman
  name: rmc-job-name-forecon-marksman
  startingGear: RMCGearTyrargoMarksman
  ranks:
    RMCRankCorporal: []
  icon: "RMCJobIconTyrargoMarksman"
  requirements:
  - !type:RoleTimeRequirement
    role: CMJobWeaponsSpecialist
    time: 3600 # 1 hour
  - !type:TotalJobsTimeRequirement
    group: RMCJobsSurvivor
    time: 5400 # 1.5 hours
  spawnMenuRoleName: UNMC Marksman (Tyrargo Rift Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetTyrargoMarksman
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: spec_sniper
    - type: IntelRescueSurvivorObjective
    - type: AssignSquad
      whitelist:
        tags:
        - RMCSquadUNMC
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetTyrargoMarksman
    - type: ScoutWhitelist
    - type: JobPrefix
      prefix: rmc-job-prefix-forecon-marksman
  hidden: true

- type: startingGear
  parent: RMCGearTyrargoBase
  id: RMCGearTyrargoMarksman
  equipment:
    shoes: RMCScoutShoes
    head: RMCHeadBeretSquad
    eyes: RMCGlassesTriMaxBlack

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointTyrargoMarksman
  name: tyrargo marine marksman spawn point
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorTyrargoMarksman
  - type: Sprite
    state: spec_spawn

- type: entity
  parent: RMCSurvivorPresetTyrargoSurvivorNoPrimary
  id: RMCSurvivorPresetTyrargoMarksman
  name: tyrargo marine marksman survivor preset
  categories: [ HideSpawnMenu ]
  components:
  - type: EntityPreset
    randomOutfits:
    - []
    primaryWeapons: # 1/5 M4SPR, 4/5 MK2
    - [ WeaponRifleM4SPRCustom, CMMagazineRifleM4SPR, CMMagazineRifleM4SPR, CMMagazineRifleM4SPRExt ]
    primaryWeaponChance: 1

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconTyrargoMarksman
  icon:
    sprite: _RMC14/Interface/job_icons/UNMC/tyrargo.rsi
    state: hudsquad_tyrargo_snpr
