- type: job
  parent: RMCSurvivorTyrargoBase
  id: RMCSurvivorTyrargoSmartgunOperator
  name: rmc-job-name-tyrargo-heavy-gunner
  startingGear: RMCGearTyrargoSmartgunOperator
  icon: "RMCJobIconTyrargoSmartgunOperator"
  ranks:
    RMCRankCorporal: []
  requirements:
  - !type:RoleTimeRequirement
    role: CMJobSmartGunOperator
    time: 3600 # 1 hour
  spawnMenuRoleName: UNMC Heavy Gunner (Tyrargo Rift Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetTyrargoHeavyGunner
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: smartgunner
    - type: IntelRescueSurvivorObjective
    - type: AssignSquad
      whitelist:
        tags:
        - RMCSquadUNMC
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetTyrargoSurvivorNoPistol
    - type: JobPrefix
      prefix: rmc-job-prefix-tyrargo-heavy-gunner
  hidden: true

- type: startingGear
  parent: RMCGearTyrargoBase
  id: RMCGearTyrargoSmartgunOperator
  equipment:
    belt: RMCBeltSmartGunOperatorPistolSurvivorFilled
    back: RMCSatchelTyrargoSurvivorHeavyGunnerFill

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointTyrargoSmartGunOperator
  name: tyrargo marine heavy gunner spawn point
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorTyrargoSmartgunOperator
  - type: Sprite
    state: smartgunner_spawn

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconTyrargoSmartgunOperator
  icon:
    sprite: _RMC14/Interface/job_icons/UNMC/tyrargo.rsi
    state: hudsquad_mmg
