- type: job
  parent: RMCSurvivorTyrargoBase
  id: RMCSurvivorTyrargoCommander
  name: rmc-job-name-forecon-commander
  description: cm-job-description-commanding-officer
  playTimeTracker: RMCJobSurvivorCO
  ranks:
    RMCRankMajor: []
  accessGroups:
  - ColonistEngi
  startingGear: RMCGearTyrargoCommander
  spawnMenuRoleName: UNMC Commander (Tyrargo Rift Survivor)
  supervisors: cm-job-supervisors-marine-high-command
  roleWeight: 0.25
  icon: "RMCJobIconTyrargoCommander"
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetCommander
    - type: MarineOrders
    - type: RMCPointing
    - type: RMCTrackable
    - type: JobPrefix
      prefix: rmc-job-prefix-forecon-co
    - type: CommandAccent
    - type: InnateCommandSpeech
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: co
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_unmc
    - type: IntelRescueSurvivorObjective
    - type: AssignSquad
      whitelist:
        tags:
        - RMCSquadUNMC
    - type: RMCAwardRecommendation
      maxRecommendations: 4
  hidden: true
  useLoadoutOfJob: RMCSurvivorCommandingOfficer # for inheritance

- type: startingGear
  parent: RMCGearTyrargoBase
  id: RMCGearTyrargoCommander
  equipment:
    belt: RMCMatebaBeltForeconFilled
    head: CMHeadCapCav
    outerClothing: RMCJacketWindbreakerForeconFilled
    back: RMCSatchelTyrargoSurvivorCommanderFill
    id: CMIDCardGold
    ears: RMCHeadsetTyrargoCommander
    eyes: RMCSunglasses

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointTyrargoCommander
  name: tyrargo commander spawn point
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorTyrargoCommander
  - type: Sprite
    state: co_spawn

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconTyrargoCommander
  icon:
    sprite: _RMC14/Interface/job_icons/UNMC/tyrargo.rsi
    state: hudsquad_tyrargo_co
