using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class BlueHorizontalSeparator : Control
{
    public BlueHorizontalSeparator()
    {
        RobustXamlLoader.Load(this);
    }
}
