using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client._RMC14.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class RMCIconLabelRow : BoxContainer
{
    private readonly IResourceCache _resourceCache;

    private string _path = string.Empty;
    private string _whitePath = string.Empty;
    private bool _hovered;

    public RMCIconLabelRow()
    {
        RobustXamlLoader.Load(this);
        _resourceCache = IoCManager.Resolve<IResourceCache>();
    }

    public void SetIcon(string path, string whitePath)
    {
        _path = path;
        _whitePath = whitePath;
        Apply();
    }

    public void SetHovered(bool hovered)
    {
        _hovered = hovered;
        Apply();
    }

    private void Apply()
    {
        Icon.Texture = _resourceCache.GetTexture(_hovered ? _whitePath : _path);
    }
}
