using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class RMCResettableButton : Control
{
    public event Action<BaseButton.ButtonEventArgs>? OnPressed;

    public string? Text
    {
        get => Button.Text;
        set => Button.Text = value;
    }

    public RMCResettableButton()
    {
        RobustXamlLoader.Load(this);
        Button.OnPressed += args => OnPressed?.Invoke(args);
    }

    public void ClearOnPressed()
    {
        OnPressed = null;
    }
}
