using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.UserInterface.FoodProcessorUI
{
    [GenerateTypedNameReferences]
    public sealed partial class ProcessorMenu : FancyWindow
    {
        public bool IsBusy;

        public ProcessorMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

        }

        public void ToggleBusyDisableOverlayPanel(bool shouldDisable)
        {
            DisableCookingPanelOverlay.Visible = shouldDisable;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            if (!IsBusy)
                return;

        }

    }
}
