using Content.Client._CM14.Xenos.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CM14.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class CMSurgeryStepButton : XenoChoiceControl
{
    public EntityUid Step { get; set; }

    public CMSurgeryStepButton()
    {
        RobustXamlLoader.Load(this);
    }
}
