using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Admin.Utility;

[GenerateTypedNameReferences]
public sealed partial class RMCOrbitalDropWindow : DefaultWindow
{
    public RMCOrbitalDropWindow()
    {
        RobustXamlLoader.Load(this);

        PayloadTabs.SetTabTitle(0, Loc.GetString("rmc-orbital-drop-nearby-tab"));
        PayloadTabs.SetTabTitle(1, Loc.GetString("rmc-orbital-drop-player-tab"));
        PayloadTabs.SetTabTitle(2, Loc.GetString("rmc-orbital-drop-prototype-tab"));
    }
}
