using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsWindow : DefaultWindow
{
    public RequisitionsWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
