using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsPendingOrderCard : BoxContainer
{
    public RequisitionsPendingOrderCard()
    {
        RobustXamlLoader.Load(this);
    }
}
