# Provost Inspector
## Outerwear
- type: loadout
  id: ProvostJacketFilledRMC
  cost: 0
  equipment:
    outerClothing: RMCProvostJacketFilled

- type: loadout
  id: ProvostCoatFilledRMC
  cost: 0
  equipment:
    outerClothing: RMCProvostCoatFilled

- type: loadout
  id: RMCProvostJacketBlueFilled
  cost: 0
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: CMJobProvostInspector
      time: 432000 # 120 hrs
  equipment:
    outerClothing: RMCProvostJacketBlueFilled

## Headwear
- type: loadout
  id: RMCHeadBeretProvostGold
  cost: 0
  equipment:
    head: RMCHeadBeretProvostGold

- type: loadout
  id: RMCHeadBeretProvostBlue
  cost: 0
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: CMJobProvostInspector
      time: 432000 # 120 hrs
  equipment:
    head: RMCHeadBeretProvostBlue
