using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Mentor;

[GenerateTypedNameReferences]
public sealed partial class StaffHelpWindow : DefaultWindow
{
    public StaffHelpWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
