
# Survivor skills

- type: entity
  id: RMCSkillPresetSurvivor
  name: Survivor
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillEndurance: 2
      RMCSkillFireman: 1
      RMCSkillFirearms: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorResearcher
  name: Survivor Researcher
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillMedical: 3
      RMCSkillSurgery: 2
      RMCSkillResearch: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorDoctor
  name: Survivor Doctor
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillMedical: 3
      RMCSkillSurgery: 2
      RMCSkillFireman: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorEngineer
  name: Survivor Engineer
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 2
      RMCSkillConstruction: 2
      RMCSkillVehicles: 1
      RMCSkillPowerLoader: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorChaplain
  name: Survivor Chaplain
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillLeadership: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorGangLeader
  name: Survivor Gang Leader
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillCqc: 2
      RMCSkillLeadership: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorPrisoner
  name: Survivor Prisoner
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillCqc: 2
      RMCSkillMeleeWeapons: 1
      RMCSkillVehicles: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorTrucker
  name: Survivor Trucker
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 2
      RMCSkillConstruction: 2
      RMCSkillVehicles: 3

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorMiner
  name: Survivor Miner
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 1
      RMCSkillPowerLoader: 2
      RMCSkillVehicles: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorPizzaGalaxyDriver
  name: Survivor Pizza Galaxy Delivery Driver
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillVehicles: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorCommercialPilot
  name: Survivor Commercial Pilot
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillPilot: 2
      RMCSkillLeadership: 1

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorParamedic
  name: Survivor Paramedic
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillMedical: 3
      RMCSkillSurgery: 2
      RMCSkillVehicles: 1
      RMCSkillFireman: 2

- type: entity
  parent: RMCSkillPresetSurvivor
  id: RMCSkillPresetSurvivorFireProtectionSpecialist
  name: Survivor Fire Protection Specialist
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillEngineer: 2
      RMCSkillMedical: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
