using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.Xenonids.UI;

[GenerateTypedNameReferences]
[Virtual]
public partial class XenoWatchWindow : DefaultWindow
{
    public XenoWatchWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
