using Content.Shared._RMC14.Xenonids.Watch;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Xenonids.Watch;

[GenerateTypedNameReferences]
public sealed partial class XenoWatchWindow : DefaultWindow
{
    public readonly Dictionary<string, bool> _buttons = new();

    public XenoWatchWindow()
    {
        _buttons.Add("Queen", false);
        _buttons.Add("Crusher", false);
        _buttons.Add("Boiler", false);
        _buttons.Add("Ravager", false);
        _buttons.Add("Praetorian", false);
        _buttons.Add("Warrior", false);
        _buttons.Add("Spitter", false);
        _buttons.Add("Carrier", false);
        _buttons.Add("Burrower", false);
        _buttons.Add("Hivelord", false);
        _buttons.Add("Lurker", false);
        _buttons.Add("Drone", false);
        _buttons.Add("Defender", false);
        _buttons.Add("Sentinel", false);
        _buttons.Add("Runner", false);
        _buttons.Add("Parasite", false);
        _buttons.Add("Lesser", false);
        _buttons.Add("Tier0", false);
        _buttons.Add("Tier1", false);
        _buttons.Add("Tier2", false);
        _buttons.Add("Tier3", false);
        _buttons.Add("Tier4", false);
        RobustXamlLoader.Load(this);

    }


}

