using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;

namespace Content.Client._RMC14.Elevators;

[GenerateTypedNameReferences]
public sealed partial class ElevatorPanelWindow : FancyWindow
{
    public ElevatorPanelWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
