- type: entity
  id: RMCSynthAddComponents
  categories: [ HideSpawnMenu ]
  components:
  - type: NightVision
    innate: true
    state: half
    onlyHalf: true
    alert: SynthNightVision
  - type: EyeProtection
  - type: WoundableUntreatable
  - type: Insulated
  - type: ZombieImmune
  - type: ShowHealthIcons
  - type: ShowHealthBars
  - type: ParalyzeImmuneFrom
    whitelist:
      tags:
      - RMCSynthGrabbable
  - type: RMCInfectOnPullAttemptImmune
  - type: RMCAllowSuitStorage
  - type: DemoSpecWhitelist
  - type: GrenadeSpecWhitelist
  - type: ScoutWhitelist
  - type: SniperWhitelist
  - type: PyroWhitelist
  - type: QYJWhitelist

- type: entity
  id: RMCSynthRemoveComponents
  categories: [ HideSpawnMenu ]
  components:
  - type: CMSurgeryTarget
  - type: Infectable
  - type: Hunger
  - type: Thirst
  - type: Perishable
  - type: ThermalRegulator
  - type: Stamina
  - type: DamageForceSay
  - type: Dna
  - type: InjectableSolution
  - type: IVDripTarget
  - type: RMCSuicide
    damage: { }
