using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Intel;

[GenerateTypedNameReferences]
public sealed partial class ViewIntelObjectivesWindow : DefaultWindow
{
    public ViewIntelObjectivesWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
