using Content.Shared._RMC14.Medical.Scanner;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;

namespace Content.Shared._RMC14.RMCMedicalRecords;

/// <summary>
///     Entity-bound medical data taken from the body scanner. Import scan can pre-select surgeries in the autodoc.
///     Static medical data (blood type, disabilities, etc.) lives on <see cref="RMCMedicalRecord"/> in the station record set.
/// </summary>
[RegisterComponent, NetworkedComponent, AutoGenerateComponentState]
[Access(typeof(SharedRMCMedicalRecordsSystem))]
public sealed partial class RMCLastBodyScanResultComponent : Component
{
    /// <summary>
    ///     The formatted world time of the last body scan, or null if never scanned.
    /// </summary>
    [DataField, AutoNetworkedField]
    public string? LastScanTime;

    /// <summary>
    ///     A snapshot of the body scanner state captured at <see cref="LastScanTime"/>.
    /// </summary>
    [DataField, AutoNetworkedField]
    public HealthScanState? LastScanState;

    /// <summary>
    ///     A list of autodoc procedure entries generated by the body scanner.
    ///     Used by the autodoc's "import scan" to pre-select surgeries.
    /// </summary>
    [DataField, AutoNetworkedField]
    public List<RMCAutodocScanData> AutodocScanData = [];
}

/// <summary>
///     A single autodoc procedure record entry, identifying procedures detected by the body scanner.
/// </summary>
[Serializable, NetSerializable, DataRecord]
public sealed record RMCAutodocScanData(string Procedure, string Details);
