using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Vehicle.Supply;

[GenerateTypedNameReferences]
public sealed partial class RMCVehicleSupplyWindow : DefaultWindow
{
    public RMCVehicleSupplyWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
