- type: job
  parent: CMJobBase
  id: CMRoyalParamarinesMedicPVE
  name: rmc-job-name-rcm-pve-medical-assistant
  description: rmc-ghost-role-information-rcm-description
  playTimeTracker: RMCJobRoyalParaMedicPVE
  ranks:
    RMCRankTSECorporal: [ ]
  requirements:
  - !type:TotalJobsTimeRequirement
    group: CMJobsMedical
    time: 10800 # 3 hours
  startingGear: RMCGearRoyalParaMedicPVE
  icon: "RMCJobIconParaMedicPVE"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-royal-tl
  spawnMenuRoleName: Royal Paramarine Medical Assistant (PVE)
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - RoyalMarines
      - TSE
    - type: Language
      spokenLanguages:
      - English
      - Japanese
      understoodLanguages:
      - English
      - Japanese
      currentLanguage: English
      defaultLanguage: English
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillCqc: 3
        RMCSkillEndurance: 3
        RMCSkillEngineer: 1
        RMCSkillFirearms: 1
        RMCSkillFireman: 3
        RMCSkillJtac: 1
        RMCSkillMedical: 2
        RMCSkillMeleeWeapons: 1
        RMCSkillPilot: 1
        RMCSkillSurgery: 2
    - type: JobPrefix
      prefix: rmc-job-prefix-rcm-pve-medical-assistant
    - type: AssignSquad
      squad: SquadPara
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: rmc_medic_pve
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_para
  hidden: true

- type: startingGear
  id: RMCGearRoyalParaMedicPVE
  equipment:
    head: RMCHeadRoyalHelmet
    ears: RMCHeadsetRoyalParaPVE
    jumpsuit: RMCJumpsuitMarinePara
    gloves: RMCHandsVeteranRoyalMarine
    id: RMCIDRoyalMarines
    belt: RMCMedicalL75RCMFilled
    back: RMCSatchelRoyalMOLS
    shoes: RMCBootsRoyalFilled
    pocket1: RMCPouchToolsFilledRCM
    pocket2: RMCPouchMedkitFillRoyal
    outerClothing: RMCArmorParaVest

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointRCMPVEParaMedic
  name: paramarine medical assistant spawn point (PVE)
  components:
  - type: SpawnPoint
    job_id: CMRoyalParamarinesMedicPVE
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Head/Royal/ballistic.rsi
    state: icon

- type: playTimeTracker
  id: RMCJobRoyalParaMedicPVE

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconParaMedicPVE
  icon:
    sprite: _RMC14/Interface/job_icons/TSE/RCM/paramarine.rsi
    state: para_medic
