using Content.Shared._RMC14.Medical.MedicalPods;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Medical.MedicalPods;

[GenerateTypedNameReferences]
public sealed partial class SleeperConsoleWindow : DefaultWindow
{
    private SleeperConsoleBui? _bui;

    public SleeperConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        DialysisToggleButton.OnPressed += _ => _bui?.ToggleFilter();
        EjectButton.OnPressed += _ => _bui?.Eject();
        AutoEjectDeadButton.OnPressed += _ => _bui?.SetAutoEjectDead(!AutoEjectDeadButton.Pressed);
    }

    public void SetBui(SleeperConsoleBui bui)
    {
        _bui = bui;
    }

    public void UpdateState(SleeperBuiState state)
    {
        var hasOccupant = state.Occupant != null;
        EmptyPanel.Visible = !hasOccupant;
        OccupantPanel.Visible = hasOccupant;

        if (!hasOccupant)
            return;

        // Dialysis
        DialysisToggleButton.Pressed = state.Filtering;
        DialysisToggleButton.Text = state.Filtering
            ? Loc.GetString("rmc-sleeper-dialysis-active")
            : Loc.GetString("rmc-sleeper-dialysis-inactive");

        if (state.Filtering && state.ReagentsWhenStarted > 0)
        {
            DialysisProgressBar.Visible = true;
            DialysisProgressBar.Value = (state.TotalReagents / state.ReagentsWhenStarted).Float();
            DialysisStatusLabel.Text = Loc.GetString("rmc-sleeper-dialysis-progress",
                ("current", state.TotalReagents.Int()),
                ("total", state.ReagentsWhenStarted.Int()));
        }
        else
        {
            DialysisProgressBar.Visible = false;
            DialysisStatusLabel.Text = state.TotalReagents <= 0
                ? Loc.GetString("rmc-sleeper-dialysis-no-chemicals")
                : "";
        }

        // Auto-eject and occupant info
        AutoEjectDeadButton.Pressed = state.AutoEjectDead;
        AutoEjectDeadButton.Text = state.AutoEjectDead
            ? Loc.GetString("rmc-sleeper-on")
            : Loc.GetString("rmc-sleeper-off");

        OccupantNameLabel.Text = state.OccupantName ?? "";

        // Health
        var healthPercent = state.OccupantMaxHealth > 0
            ? state.OccupantHealth / state.OccupantMaxHealth
            : 0;
        HealthBar.Value = state.OccupantHealth;
        HealthBar.MaxValue = state.OccupantMaxHealth;
        HealthBar.MinValue = state.OccupantMinHealth;
        HealthBarText.Text = state.OccupantHealth.ToString("F0");

        HealthBar.Modulate = healthPercent switch
        {
            >= 0.5f => Color.FromHex("#00AA00"),
            >= 0 => Color.FromHex("#AAAA00"),
            _ => Color.FromHex("#AA0000")
        };
        StatusLabel.Text = state.OccupantStat switch
        {
            0 => Loc.GetString("rmc-sleeper-status-alive"),
            1 => Loc.GetString("rmc-sleeper-status-critical"),
            2 => Loc.GetString("rmc-sleeper-status-dead"),
            _ => ""
        };
        StatusLabel.Modulate = state.OccupantStat switch
        {
            0 => Color.FromHex("#00AA00"),
            1 => Color.FromHex("#AAAA00"),
            2 => Color.FromHex("#AA0000"),
            _ => Color.White
        };

        // Damage bars
        UpdateDamageBar(BruteBar, BruteBarText, state.BruteLoss);
        UpdateDamageBar(BurnBar, BurnBarText, state.BurnLoss);
        UpdateDamageBar(ToxinBar, ToxinBarText, state.ToxinLoss);
        UpdateDamageBar(OxygenBar, OxygenBarText, state.OxyLoss);

        // Blood level
        BloodSection.Visible = state.HasBlood;
        if (state.HasBlood)
        {
            BloodBar.Value = state.BloodPercent;
            BloodBar.MaxValue = 100;
            BloodBarText.Text = $"{state.BloodPercent:F1}%, {state.BloodLevel}u";

            BloodBar.Modulate = state.BloodPercent switch
            {
                >= 90 => Color.FromHex("#00AA00"),
                >= 60 => Color.FromHex("#AAAA00"),
                _ => Color.FromHex("#AA0000")
            };
        }

        // Chemicals
        ChemicalsContainer.DisposeAllChildren();
        foreach (var (name, chemId, occupantAmount, injectable, overdosing, odWarning) in state.Chemicals)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

            var nameLabel = new Label
            {
                Text = name,
                MinWidth = 120
            };
            row.AddChild(nameLabel);

            var amountBar = new ProgressBar
            {
                MinWidth = 100,
                Value = occupantAmount.Float(),
                MaxValue = state.MaxChem.Float()
            };
            var amountLabel = new Label
            {
                Text = $"{occupantAmount}/{state.MaxChem}u",
                Margin = new Thickness(0, 0, 5, 0),
                HorizontalAlignment = HAlignment.Right
            };
            amountBar.AddChild(amountLabel);

            if (overdosing)
            {
                amountBar.Modulate = Color.FromHex("#AA0000");
                var warningLabel = new Label { Text = " ⚠", Modulate = Color.FromHex("#AA0000") };
                row.AddChild(warningLabel);
            }
            else if (odWarning)
            {
                amountBar.Modulate = Color.FromHex("#AAAA00");
            }

            row.AddChild(amountBar);

            foreach (var amount in state.InjectionAmounts)
            {
                var injectButton = new Button
                {
                    Text = Loc.GetString("rmc-sleeper-inject", ("amount", amount)),
                    Disabled = !injectable || occupantAmount + amount > state.MaxChem || state.OccupantStat == 2,
                    Margin = new Thickness(5, 0, 0, 0)
                };
                var injectAmount = amount;
                injectButton.OnPressed += _ => _bui?.InjectChemical(chemId, injectAmount);
                row.AddChild(injectButton);
            }

            ChemicalsContainer.AddChild(row);
        }
    }

    private static void UpdateDamageBar(ProgressBar bar, Label label, float damage)
    {
        bar.Value = damage;
        bar.MaxValue = 100;
        label.Text = damage.ToString("F0");

        bar.Modulate = damage switch
        {
            < 25 => Color.FromHex("#00AA00"),
            < 50 => Color.FromHex("#AAAA00"),
            _ => Color.FromHex("#AA0000")
        };
    }
}
