using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RMC14.Waypoint;

[GenerateTypedNameReferences]
public sealed partial class ChooseTrackerAlertEntry : PanelContainer
{
    public ChooseTrackerAlertEntry(string name, EntProtoId? entProto)
    {
        RobustXamlLoader.Load(this);

        EntityPrototypeView.SetPrototype(entProto);
        NameLabel.Text = name;
    }
}
