using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Admin.Commendations;

[GenerateTypedNameReferences]
public sealed partial class RMCAdminCommendationWindow : DefaultWindow
{
    public RMCAdminCommendationWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
