# base
- type: ghostRoleRaffleSettings
  id: instant
  settings:
    initialDuration: 0
    joinExtendsDurationBy: 0
    maxDuration: 0
    roundTimeRequirement: 0

- type: playTimeTracker
  id: RMCGhostBarTracker

# recruit
- type: startingGear
  parent: RMCGearRecruit
  id: RMCGearRecruitGhostBar
  equipment:
    ears: RMCHeadsetMarineEmpty

- type: job
  parent: RMCRecruit
  id: RMCRecruitGhostBar
  playTimeTracker: RMCGhostBarTracker
  startingGear: RMCGearRecruitGhostBar

- type: entity
  parent: MarkerBase
  id: RMCGhostBarSpawnerRecruit
  name: ghost bar spawn point
  suffix: recruit
  components:
  - type: Sprite
    layers:
    - state: green
  - type: GhostRole
    name: rmc-ghost-bar-name-recruit
    description: rmc-ghost-bar-description
    rules: rmc-ghost-bar-rules
    raffle:
      settings: instant
    job: RMCRecruitGhostBar
  - type: RMCGhostRole
    remaining: null
