using Content.Client._RMC14.UserInterface;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._RMC14.Overwatch;
using Content.Shared.Mobs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._RMC14.Overwatch;

[GenerateTypedNameReferences]
public sealed partial class OverwatchSquadView : Control
{
    public event Action? OnStop;
    public readonly FloatSpinBox Longitude;
    public readonly FloatSpinBox Latitude;
    public readonly FloatSpinBox OrbitalLongitude;
    public readonly FloatSpinBox OrbitalLatitude;
    public bool HasCrate;
    public bool HasOrbital;
    public TimeSpan NextLaunchAt;
    public TimeSpan NextOrbitalAt;

    private bool _squadInfoHidden;

    public OverwatchSquadView()
    {
        RobustXamlLoader.Load(this);

        // Set up tab button event handlers
        SquadMonitorButton.OnPressed += OnSquadMonitorPressed;
        SupplyDropButton.OnPressed += OnSupplyDropPressed;
        OrbitalBombardmentButton.OnPressed += OnOrbitalBombardmentPressed;

        // Set default tab to Squad Monitor
        ShowTab("SquadMonitor");

        Longitude = UIExtensions.CreateDialSpinBox(buttons: false, minWidth: 100);
        LongitudeContainer.AddChild(Longitude);
        Longitude.SetPositionFirst();

        Latitude = UIExtensions.CreateDialSpinBox(buttons: false, minWidth: 100);
        LatitudeContainer.AddChild(Latitude);
        Latitude.SetPositionFirst();

        Longitude.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.GuiTabNavigateNext ||
                args.Function == EngineKeyFunctions.GuiTabNavigatePrev)
            {
                Latitude.GrabKeyboardFocus();
            }
        };

        Latitude.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.GuiTabNavigateNext ||
                args.Function == EngineKeyFunctions.GuiTabNavigatePrev)
            {
                Longitude.GrabKeyboardFocus();
            }
        };

        OrbitalLongitude = UIExtensions.CreateDialSpinBox(buttons: false, minWidth: 100);
        OrbitalLongitudeContainer.AddChild(OrbitalLongitude);
        OrbitalLongitude.SetPositionFirst();

        OrbitalLatitude = UIExtensions.CreateDialSpinBox(buttons: false, minWidth: 100);
        OrbitalLatitudeContainer.AddChild(OrbitalLatitude);
        OrbitalLatitude.SetPositionFirst();

        OrbitalLongitude.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.GuiTabNavigateNext ||
                args.Function == EngineKeyFunctions.GuiTabNavigatePrev)
            {
                OrbitalLatitude.GrabKeyboardFocus();
            }
        };

        OrbitalLatitude.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.GuiTabNavigateNext ||
                args.Function == EngineKeyFunctions.GuiTabNavigatePrev)
            {
                OrbitalLongitude.GrabKeyboardFocus();
            }
        };

        StopOverwatchButton.OnPressed += OnStopOverwatchPressed;
        HideSquadInfoButton.OnPressed += OnHideSquadInfoPressed;
        LaunchButton.Label.ModulateSelfOverride = Color.Black;
        SaveButton.Label.ModulateSelfOverride = Color.Black;
        OrbitalSaveButton.Label.ModulateSelfOverride = Color.Black;
    }

    private void OnStopOverwatchPressed(ButtonEventArgs obj)
    {
        OnStop?.Invoke();
    }

    private void OnHideSquadInfoPressed(ButtonEventArgs obj)
    {
        _squadInfoHidden = !_squadInfoHidden;
        ApplySquadInfoVisibilityState();
        HideSquadInfoButton.Text = _squadInfoHidden ? "Show Squad Info" : "Hide Squad Info";
    }

    private void MakeAllVisible(Control control)
    {
        foreach (var child in control.Children)
        {
            child.Visible = true;
        }
    }

    private void MakeAllVisible()
    {
        MakeAllVisible(Names);
        MakeAllVisible(Roles);
        MakeAllVisible(States);
        MakeAllVisible(Locations);
        MakeAllVisible(Distances);
        MakeAllVisible(Buttons);
    }

    private void MakeControlVisible(Control control, int index, bool visible)
    {
        if (index >= control.ChildCount)
            return;

        control.GetChild(index).Visible = visible;
    }

    private void MakeViewVisible(int index, bool visible)
    {
        MakeControlVisible(Names, index, visible);
        MakeControlVisible(Roles, index, visible);
        MakeControlVisible(States, index, visible);
        MakeControlVisible(Locations, index, visible);
        MakeControlVisible(Distances, index, visible);
        MakeControlVisible(Buttons, index, visible);
    }

    public void UpdateResults(OverwatchLocation? location, bool showDead, bool showHidden, List<OverwatchMarine> marines, OverwatchConsoleComponent console)
    {
        var text = SearchBar.Text;
        if (string.IsNullOrWhiteSpace(text) &&
            location == null &&
            showDead &&
            showHidden)
        {
            MakeAllVisible();
            ApplySquadInfoVisibilityState();
            return;
        }

        for (var i = 0; i < Names.ChildCount; i++)
        {
            var name = Names.GetChild(i);
            var role = Roles.GetChild(i);
            if (!string.IsNullOrWhiteSpace(text))
            {
                if (!name.ChildrenContainText(text) && !role.ChildrenContainText(text))
                {
                    MakeViewVisible(i, false);
                    continue;
                }
            }

            if (location != null)
            {
                if (i >= marines.Count || marines[i].Location != location)
                {
                    MakeViewVisible(i, false);
                    continue;
                }
            }

            if (!showDead)
            {
                if (i >= marines.Count || marines[i].State != MobState.Alive)
                {
                    MakeViewVisible(i, false);
                    continue;
                }
            }

            if (!showHidden)
            {
                var hidden = console.Hidden;
                if (i >= marines.Count || hidden.Contains(marines[i].Id))
                {
                    MakeViewVisible(i, false);
                    continue;
                }
            }

            MakeViewVisible(i, true);
        }

        ApplySquadInfoVisibilityState();
    }

    private void OnSquadMonitorPressed(ButtonEventArgs obj)
    {
        ShowTab("SquadMonitor");
    }

    private void OnSupplyDropPressed(ButtonEventArgs obj)
    {
        ShowTab("SupplyDrop");
    }

    private void OnOrbitalBombardmentPressed(ButtonEventArgs obj)
    {
        ShowTab("OrbitalBombardment");
    }

    private void ShowTab(string tabName)
    {
        // Hide all content panels
        SquadMonitor.Visible = false;
        SupplyDrop.Visible = false;
        OrbitalBombardment.Visible = false;

        // Reset all button styles to unselected state
        SquadMonitorButton.ModulateSelfOverride = Color.FromHex("#202020");
        SupplyDropButton.ModulateSelfOverride = Color.FromHex("#202020");
        OrbitalBombardmentButton.ModulateSelfOverride = Color.FromHex("#202020");

        // Show the selected panel and highlight the button
        switch (tabName)
        {
            case "SquadMonitor":
                SquadMonitor.Visible = true;
                SquadMonitorButton.ModulateSelfOverride = Color.FromHex("#404040");
                break;
            case "SupplyDrop":
                SupplyDrop.Visible = true;
                SupplyDropButton.ModulateSelfOverride = Color.FromHex("#404040");
                break;
            case "OrbitalBombardment":
                OrbitalBombardment.Visible = true;
                OrbitalBombardmentButton.ModulateSelfOverride = Color.FromHex("#404040");
                break;
        }
    }

    public void ApplySquadInfoVisibilityState()
    {
        // Apply the current local toggle state
        if (RolesContainer.ChildCount > 0)
        {
            // Hide/show all panels except the last one (Total/Living) based on current state
            for (int i = 0; i < RolesContainer.ChildCount - 1; i++)
            {
                RolesContainer.GetChild(i).Visible = !_squadInfoHidden;
            }

            // Always keep the Total/Living panel visible (last panel)
            if (RolesContainer.ChildCount > 0)
            {
                RolesContainer.GetChild(RolesContainer.ChildCount - 1).Visible = true;
            }
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        CrateStatus.Text = Loc.GetString("rmc-overwatch-crate-status",("hasCrate", HasCrate));

        var time = IoCManager.Resolve<IGameTiming>().CurTime;
        var supplyTimeLeft = NextLaunchAt - time;
        if (supplyTimeLeft > TimeSpan.Zero)
        {
            CrateStatus.Text = Loc.GetString("rmc-overwatch-crate-cooldown",("SupplyTimeLeft", (int)supplyTimeLeft.TotalSeconds));
            LaunchButton.Disabled = true;
        }
        else
        {
            LaunchButton.Disabled = false;
        }

        var orbitalTimeLeft = NextOrbitalAt - time;
        if (orbitalTimeLeft > TimeSpan.Zero)
        {
            OrbitalStatus.Text = Loc.GetString("rmc-overwatch-ob-cooldown",("OrbitalTimeLeft", (int)orbitalTimeLeft.TotalSeconds));
            OrbitalFireButton.Disabled = true;
        }
        else
        {
            OrbitalStatus.Text = Loc.GetString("rmc-overwatch-crate-status",("isReady", HasOrbital));
            OrbitalFireButton.Disabled = false;
        }
    }
}
