- type: job
  parent: RMCSyntheticColony
  id: RMCSyntheticColonySorokyneEngineer
  startingGear: RMCGearSyntheticColonistSorokyneEngineer
  spawnMenuRoleName: Reactor Plant Synthetic (Sorokyne Survivor)
  special:
  - !type:RemoveComponentSpecial
    components:
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  - !type:AddComponentSpecial
    components:
    - type: Language
      preset: RMCLanguagePresetSynthColonist
    - type: LanguageLearning
      preset: RMCLanguageLearningPresetSynthColonist
    - type: NpcFactionMember
      factions:
      - SPP
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: Synth
  useLoadoutOfJob: RMCSyntheticColony # for inheritance

- type: startingGear
  parent: RMCGearSyntheticColonistBase
  id: RMCGearSyntheticColonistSorokyneEngineer
  equipment:
    back: RMCSatchelLightpack
    shoes: RMCShoesWhite
    outerClothing: RMCLabcoatShort
    head: RMCHeadCapSPPCivilianPlantWorker
    jumpsuit: RMCJumpsuitNormCivilianWhiteAlt
    ears: RMCHeadsetDistressSPP
  storage:
    back:
    - WeaponNailgun
    - CMSheetMetal20
    - RMCMaskGasSPP
  inhand:
    - RMCFireAxe # todo maintenance jack

