- type: job
  parent: RMCSyntheticColony
  id: RMCSyntheticColonySorokyneDoctor
  startingGear: RMCGearSyntheticColonistSorokyneDoctor
  spawnMenuRoleName: Doctor Synthetic (Sorokyne Survivor)
  special:
  - !type:RemoveComponentSpecial
    components:
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  - !type:AddComponentSpecial
    components:
    - type: Language
      preset: RMCLanguagePresetSynthColonist
    - type: LanguageLearning
      preset: RMCLanguageLearningPresetSynthColonist
    - type: NpcFactionMember
      factions:
      - SPP
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: Synth
  useLoadoutOfJob: RMCSyntheticColony

- type: startingGear
  parent: RMCGearSyntheticColonistBase
  id: RMCGearSyntheticColonistSorokyneDoctor
  equipment:
    head: RMCHeadCapSPPCivilianPlantWorker
    ears: RMCHeadsetDistressSPP
    outerClothing: RMCLabcoatLong
    jumpsuit: CMJumpsuitLiaisonBrown
    shoes: RMCShoesLaceup
    back: CMSatchel
  storage:
    back:
    - RMCMaskGasSPP
  inhand:
    - RMCFireAxe # todo maintenance jack

