- type: job
  parent: RMCSyntheticColony
  id: RMCSyntheticColonySorokyneSecurity
  startingGear: RMCGearSyntheticColonistSorokyneSecurity
  spawnMenuRoleName: Army/PCG Synthetic (Sorokyne Survivor)
  special:
  - !type:RemoveComponentSpecial
    components:
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  - !type:AddComponentSpecial
    components:
    - type: Language
      preset: RMCLanguagePresetSynthColonist
    - type: LanguageLearning
      preset: RMCLanguageLearningPresetSynthColonist
    - type: IntelRescueSurvivorObjective
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetSorokyneSynthSecurity
    - type: Synth
    - type: NpcFactionMember
      factions:
      - SPP
      - Civilian
  useLoadoutOfJob: RMCSyntheticColony # for inheritance

- type: startingGear
  id: RMCGearSyntheticColonistSorokyneSecurity
  equipment:
    id: RMCIDCardSynthColony
    pocket1: RMCPouchSurvivalSynthFill
    pocket2: RMCPouchToolsFill
  inhand:
    - RMCFireAxe # todo maintenance jack

- type: entity
  id: RMCSurvivorPresetSorokyneSynthSecurity
  name: sorokyne security synthetic preset
  suffix: survivor
  categories: [ HideSpawnMenu ]
  components:
  - type: EntityPreset
    randomOutfits:
    # Option 1: Army Reservist
    - [ RMCHeadCapSPPBeretArmy, RMCJumpsuitSPPArmy, RMCOuterClothingExternalWebbingBrown, RMCBootsSPPBlackFilled, RMCHandsVeteran, RMCScabbardMacheteFilled, RMCSatchelLightpackBlack, RMCHeadsetDistressSPP, CMBeltUtilityFilled ]
    # Option 2: PCG
    - [ CMGlassesSecurity, RMCHeadsetSPPPCG, CMHeadCapSPPPeakedPolice, RMCSatchelBlack, RMCCoatPCG, RMCHandsVeteran, RMCBootsSPPBlackFilled, RMCJumpsuitSPPPCG, RMCMaskGasSPP, CMBeltSecuritySPPFilled ]