using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Log;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.UserInterface.Crt;

[GenerateTypedNameReferences]
public sealed partial class RMCCrtActionButton : ContainerButton, IRMCCrtThemedControl
{
    public static readonly ResPath DefaultIconRsiPath = new("/Textures/_RMC14/Interface/CRT/crt_icons.rsi");

    private static readonly ISawmill Log = Logger.GetSawmill("rmc-crt");

    private readonly IResourceCache _resourceCache;
    private readonly StyleBoxFlat _transparentStyle = new() { BackgroundColor = Color.Transparent };
    private RMCCrtContentAlignment _contentAlignment = RMCCrtContentAlignment.Center;
    private string? _iconState;
    private ResPath _iconRsiPath = DefaultIconRsiPath;
    private RMCCrtThemeContext _context = new(
        RMCCrtPalettes.Get(RMCCrtPalettePreset.Blue),
        new RMCCrtAppearanceSettings(true, true));
    private bool _selected;
    private RMCCrtTone _tone = RMCCrtTone.Default;
    private RMCCrtButtonVariant _variant = RMCCrtButtonVariant.Outline;

    public string? Text
    {
        get => TextLabel.Text;
        set => TextLabel.Text = value;
    }

    public string? IconState
    {
        get => _iconState;
        set
        {
            _iconState = value;
            UpdateIcon();
        }
    }

    public ResPath IconRsiPath
    {
        get => _iconRsiPath;
        set
        {
            _iconRsiPath = value;
            UpdateIcon();
        }
    }

    public Texture? IconTexture
    {
        get => IconControl.Texture;
        set => IconControl.Texture = value;
    }

    public RMCCrtButtonVariant Variant
    {
        get => _variant;
        set
        {
            _variant = value;
            UpdateAppearance();
        }
    }

    public RMCCrtTone Tone
    {
        get => _tone;
        set
        {
            _tone = value;
            UpdateAppearance();
        }
    }

    public bool Selected
    {
        get => _selected;
        set
        {
            _selected = value;
            UpdateAppearance();
        }
    }

    public RMCCrtContentAlignment ContentAlignment
    {
        get => _contentAlignment;
        set
        {
            _contentAlignment = value;
            UpdateAlignment();
        }
    }

    public RMCCrtActionButton()
    {
        _resourceCache = IoCManager.Resolve<IResourceCache>();
        RobustXamlLoader.Load(this);
        StyleBoxOverride = _transparentStyle;
        UpdateAlignment();
        UpdateAppearance();
    }

    void IRMCCrtThemedControl.ApplyCrtTheme(RMCCrtThemeContext context)
    {
        ApplyAppearance(context);
    }

    internal void ApplyAppearance(RMCCrtThemeContext context)
    {
        _context = context;
        Background.ApplyAppearance(context);
        UpdateAppearance();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        ApplyAppearance(RMCCrtThemeHelpers.FindContext(this));
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();
        if (NameScope != null)
            UpdateAppearance();
    }

    private void UpdateIcon()
    {
        if (NameScope == null)
            return;

        if (string.IsNullOrWhiteSpace(IconState))
        {
            IconControl.Texture = null;
            return;
        }

        try
        {
            var rsi = _resourceCache.GetResource<RSIResource>(IconRsiPath).RSI;
            if (rsi.TryGetState(new RSI.StateId(IconState), out var state))
            {
                IconControl.Texture = state.Frame0;
                return;
            }

            IconControl.Texture = null;
            Log.Warning($"CRT icon state '{IconState}' does not exist in '{IconRsiPath}'.");
        }
        catch (Exception exception)
        {
            IconControl.Texture = null;
            Log.Error($"Failed to load CRT icon state '{IconState}' from '{IconRsiPath}': {exception}");
        }
    }

    private void UpdateAlignment()
    {
        if (NameScope == null)
            return;

        Layout.Align = ContentAlignment switch
        {
            RMCCrtContentAlignment.Left => BoxContainer.AlignMode.Begin,
            RMCCrtContentAlignment.Right => BoxContainer.AlignMode.End,
            _ => BoxContainer.AlignMode.Center,
        };
        Layout.HorizontalAlignment = HAlignment.Stretch;
        TextLabel.Align = ContentAlignment switch
        {
            RMCCrtContentAlignment.Left => Label.AlignMode.Left,
            RMCCrtContentAlignment.Right => Label.AlignMode.Right,
            _ => Label.AlignMode.Center,
        };
    }

    private void UpdateAppearance()
    {
        if (NameScope == null)
            return;

        if (!_context.ThemeEnabled)
        {
            UpdateNanoAppearance();
            return;
        }

        RemoveStyleClass(ContainerButton.StyleClassButton);
        RemoveStyleClass(StyleBase.ButtonCaution);
        ModulateSelfOverride = null;
        StyleBoxOverride = _transparentStyle;
        TextLabel.AddStyleClass(RMCCrtStyleClasses.Text);
        TextLabel.AddStyleClass("monospace");

        var palette = _context.Palette;
        var isDanger = Tone == RMCCrtTone.Danger || Variant == RMCCrtButtonVariant.Danger;
        Color background;
        Color border;
        Color foreground;

        if (DrawMode == DrawModeEnum.Disabled)
        {
            background = palette.DisabledBackground;
            border = palette.Muted;
            foreground = palette.DisabledForeground;
        }
        else if (isDanger)
        {
            background = DrawMode switch
            {
                DrawModeEnum.Pressed => Color.InterpolateBetween(palette.Background, palette.Danger, 0.65f),
                DrawModeEnum.Hover => Color.InterpolateBetween(palette.Danger, Color.White, 0.18f),
                _ => palette.Danger,
            };
            border = palette.Danger;
            foreground = palette.Background;
        }
        else if (Selected || Variant == RMCCrtButtonVariant.Filled)
        {
            background = DrawMode switch
            {
                DrawModeEnum.Pressed => palette.PressedBackground,
                DrawModeEnum.Hover => Color.InterpolateBetween(palette.Fill, Color.White, 0.2f),
                _ => palette.Fill,
            };
            border = palette.Border;
            foreground = palette.FillForeground;
        }
        else
        {
            background = DrawMode switch
            {
                DrawModeEnum.Pressed => palette.PressedBackground.WithAlpha(0.75f),
                DrawModeEnum.Hover => palette.HoverBackground,
                _ => palette.Background.WithAlpha(0.72f),
            };
            border = palette.Border;
            foreground = Tone switch
            {
                RMCCrtTone.Good => palette.Good,
                RMCCrtTone.Muted => palette.Muted,
                RMCCrtTone.Warning => palette.Warning,
                _ => palette.Foreground,
            };
        }

        Background.SetColorOverrides(background, border);
        IconControl.ModulateSelfOverride = foreground;
        TextLabel.FontColorOverride = foreground;
    }

    private void UpdateNanoAppearance()
    {
        AddStyleClass(ContainerButton.StyleClassButton);
        StyleBoxOverride = null;
        TextLabel.RemoveStyleClass(RMCCrtStyleClasses.Text);
        TextLabel.RemoveStyleClass("monospace");

        var isDanger = Tone == RMCCrtTone.Danger || Variant == RMCCrtButtonVariant.Danger;
        if (isDanger)
            AddStyleClass(StyleBase.ButtonCaution);
        else
            RemoveStyleClass(StyleBase.ButtonCaution);

        ModulateSelfOverride = !isDanger &&
                               (Selected || Variant == RMCCrtButtonVariant.Filled) &&
                               DrawMode != DrawModeEnum.Disabled
            ? DrawMode == DrawModeEnum.Hover
                ? StyleNano.ButtonColorGoodHovered
                : StyleNano.ButtonColorPressed
            : null;

        var foreground = Tone switch
        {
            RMCCrtTone.Good => StyleNano.GoodGreenFore,
            RMCCrtTone.Muted => StyleNano.DisabledFore,
            RMCCrtTone.Warning => StyleNano.ConcerningOrangeFore,
            _ => (Color?) null,
        };

        IconControl.ModulateSelfOverride = foreground;
        TextLabel.FontColorOverride = foreground;
    }
}
