using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Log;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.UserInterface.Crt;

[GenerateTypedNameReferences]
public sealed partial class RMCCrtActionButton : ContainerButton, IRMCCrtThemedControl
{
    public static readonly ResPath DefaultIconRsiPath = new("/Textures/_RMC14/Interface/CRT/crt_icons.rsi");

    private static readonly ISawmill Log = Logger.GetSawmill("rmc-crt");

    private readonly IResourceCache _resourceCache;
    private readonly StyleBoxFlat _transparentStyle = new() { BackgroundColor = Color.Transparent };
    private RMCCrtContentAlignment _contentAlignment = RMCCrtContentAlignment.Center;
    private string? _iconState;
    private ResPath _iconRsiPath = DefaultIconRsiPath;
    private RMCCrtPalette _palette = RMCCrtPalettes.Get(RMCCrtPalettePreset.Blue);
    private bool _selected;
    private RMCCrtTone _tone = RMCCrtTone.Default;
    private RMCCrtButtonVariant _variant = RMCCrtButtonVariant.Outline;

    public string? Text
    {
        get => TextLabel.Text;
        set => TextLabel.Text = value;
    }

    public string? IconState
    {
        get => _iconState;
        set
        {
            _iconState = value;
            UpdateIcon();
        }
    }

    public ResPath IconRsiPath
    {
        get => _iconRsiPath;
        set
        {
            _iconRsiPath = value;
            UpdateIcon();
        }
    }

    public Texture? IconTexture
    {
        get => IconControl.Texture;
        set => IconControl.Texture = value;
    }

    public RMCCrtButtonVariant Variant
    {
        get => _variant;
        set
        {
            _variant = value;
            UpdatePalette();
        }
    }

    public RMCCrtTone Tone
    {
        get => _tone;
        set
        {
            _tone = value;
            UpdatePalette();
        }
    }

    public bool Selected
    {
        get => _selected;
        set
        {
            _selected = value;
            UpdatePalette();
        }
    }

    public RMCCrtContentAlignment ContentAlignment
    {
        get => _contentAlignment;
        set
        {
            _contentAlignment = value;
            UpdateAlignment();
        }
    }

    public RMCCrtActionButton()
    {
        _resourceCache = IoCManager.Resolve<IResourceCache>();
        RobustXamlLoader.Load(this);
        StyleBoxOverride = _transparentStyle;
        UpdateAlignment();
        UpdatePalette();
    }

    public void ApplyCrtTheme(RMCCrtPalette palette)
    {
        _palette = palette;
        Background.ApplyCrtTheme(palette);
        UpdatePalette();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        ApplyCrtTheme(RMCCrtThemeHelpers.FindPalette(this));
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();
        if (NameScope != null)
            UpdatePalette();
    }

    private void UpdateIcon()
    {
        if (NameScope == null || string.IsNullOrWhiteSpace(IconState))
            return;

        try
        {
            var rsi = _resourceCache.GetResource<RSIResource>(IconRsiPath).RSI;
            if (rsi.TryGetState(new RSI.StateId(IconState), out var state))
            {
                IconControl.Texture = state.Frame0;
                return;
            }

            IconControl.Texture = null;
            Log.Warning($"CRT icon state '{IconState}' does not exist in '{IconRsiPath}'.");
        }
        catch (Exception exception)
        {
            IconControl.Texture = null;
            Log.Error($"Failed to load CRT icon state '{IconState}' from '{IconRsiPath}': {exception}");
        }
    }

    private void UpdateAlignment()
    {
        if (NameScope == null)
            return;

        Layout.Align = ContentAlignment switch
        {
            RMCCrtContentAlignment.Left => BoxContainer.AlignMode.Begin,
            RMCCrtContentAlignment.Right => BoxContainer.AlignMode.End,
            _ => BoxContainer.AlignMode.Center,
        };
        Layout.HorizontalAlignment = HAlignment.Stretch;
        TextLabel.Align = ContentAlignment switch
        {
            RMCCrtContentAlignment.Left => Label.AlignMode.Left,
            RMCCrtContentAlignment.Right => Label.AlignMode.Right,
            _ => Label.AlignMode.Center,
        };
    }

    private void UpdatePalette()
    {
        if (NameScope == null)
            return;

        var isDanger = Tone == RMCCrtTone.Danger || Variant == RMCCrtButtonVariant.Danger;
        Color background;
        Color border;
        Color foreground;

        if (DrawMode == DrawModeEnum.Disabled)
        {
            background = _palette.DisabledBackground;
            border = _palette.Muted;
            foreground = _palette.DisabledForeground;
        }
        else if (isDanger)
        {
            background = DrawMode switch
            {
                DrawModeEnum.Pressed => Color.InterpolateBetween(_palette.Background, _palette.Danger, 0.65f),
                DrawModeEnum.Hover => Color.InterpolateBetween(_palette.Danger, Color.White, 0.18f),
                _ => _palette.Danger,
            };
            border = _palette.Danger;
            foreground = _palette.Background;
        }
        else if (Selected || Variant == RMCCrtButtonVariant.Filled)
        {
            background = DrawMode switch
            {
                DrawModeEnum.Pressed => _palette.PressedBackground,
                DrawModeEnum.Hover => Color.InterpolateBetween(_palette.Fill, Color.White, 0.2f),
                _ => _palette.Fill,
            };
            border = _palette.Border;
            foreground = _palette.FillForeground;
        }
        else
        {
            background = DrawMode switch
            {
                DrawModeEnum.Pressed => _palette.PressedBackground.WithAlpha(0.75f),
                DrawModeEnum.Hover => _palette.HoverBackground,
                _ => _palette.Background.WithAlpha(0.72f),
            };
            border = _palette.Border;
            foreground = Tone switch
            {
                RMCCrtTone.Good => _palette.Good,
                RMCCrtTone.Muted => _palette.Muted,
                RMCCrtTone.Warning => _palette.Warning,
                _ => _palette.Foreground,
            };
        }

        Background.SetColorOverrides(background, border);
        IconControl.ModulateSelfOverride = foreground;
        TextLabel.FontColorOverride = foreground;
    }
}
