using System.Numerics;
using Content.Client._RMC14.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._RMC14.Medical.CrewMonitoring;

[GenerateTypedNameReferences]
public sealed partial class RMCPortableCrewMonitorWindow : RMCPopOutWindow
{
    private const float DefaultMinimumWidth = 760;
    private const float RadarMinimumWidth = 420;
    private const float LayoutPadding = 48;

    protected override Control Control => MainContainer;

    public RMCPortableCrewMonitorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void GrowToFitSignals()
    {
        Signals.Measure(Vector2Helpers.Infinity);

        var panelWidth = MathF.Max(SignalsPanel.MinWidth, Signals.DesiredSize.X + LayoutPadding / 2);
        SignalsPanel.MinWidth = panelWidth;

        var minimumWidth = MathF.Max(DefaultMinimumWidth, panelWidth + RadarMinimumWidth + LayoutPadding);
        MinWidth = MathF.Max(MinWidth, minimumWidth);
        SetWidth = MathF.Max(SetWidth, MinWidth);
        MainContainer.MinWidth = MathF.Max(MainContainer.MinWidth, minimumWidth);
    }
}
