using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Access;

[GenerateTypedNameReferences]
public sealed partial class IdModificationConsoleAccessGroupButton : Control
{
    public string Tag = "";

    public IdModificationConsoleAccessGroupButton()
    {
        RobustXamlLoader.Load(this);
    }
}
