using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Access;

[GenerateTypedNameReferences]
public sealed partial class IdModificationConsoleWindow : DefaultWindow
{
    public IdModificationConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
