using Robust.Shared.Map;
using Robust.Shared.Serialization;
using Robust.Shared.Timing;

namespace Content.Shared.Weapons.Ranged.Events;

/// <summary>
/// Raised on the client to indicate it'd like to shoot.
/// </summary>
[Serializable, NetSerializable]
public sealed class RequestShootEvent : EntityEventArgs
{
    public NetEntity Gun;
    public NetCoordinates Coordinates;
    public NetEntity? Target;
    /// <summary>
    /// If true, this shot was generated by hold to click semi auto & needs to rearm
    /// the guns sem iauto shot counter before firing
    /// </summary>
    public bool RearmSemiAuto; //RMC
    public List<int>? Shot;
    public GameTick LastRealTick;
}
