using System.Linq;
using System.Numerics;
using System.Text.RegularExpressions;
using Content.Shared.Ghost;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindow : DefaultWindow
    {
        private const string HeadingIndicatorCollapsed = "+";
        private const string HeadingIndicatorExpanded = "-";
        private record SortOption(string Label, string Tooltip, string TypeLabel);

        private sealed record SortOrderOption(
            string Label,
            string Tooltip,
            Func<IOrderedEnumerable<GhostWarp>, Func<GhostWarp, string>, Comparer<string>, IOrderedEnumerable<GhostWarp>> Apply)
            : SortOption(Label, Tooltip, "ghost-target-window-type-sort-dir-button");

        private record WarpCategory(
            string Label,
            Func<IEnumerable<GhostWarp>, IEnumerable<GhostWarp>> Filter,
            Func<GhostWarp, string> DisplayName,
            bool WarpsToEnd = true);

        private readonly IPrototypeManager _prototypeManager;
        private List<GhostWarp> _warps = new();
        private string _searchText = string.Empty;

        private int _sortOrder;

        private static readonly Regex RoleRegex = new(@"\(([^)]+)\)\s*$", RegexOptions.Compiled);

        private static readonly Comparer<string> OrdinalIgnoreCaseComparer =
            Comparer<string>.Create((x, y) => string.Compare(x, y, StringComparison.OrdinalIgnoreCase));

        private readonly SortOrderOption[] _sortOrderOptions;

        private WarpCategory? _selectedCategory;
        private readonly List<(WarpCategory Category, BaseButton Button)> _categoryButtons = new();
        private readonly string[] _jobXenoTranslations;

        public event Action<NetEntity>? WarpClicked;
        public event Action? OnGhostnadoClicked;

        public GhostTargetWindow()
        {
            RobustXamlLoader.Load(this);
            SearchBar.OnTextChanged += OnSearchTextChanged;

            GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();

            _prototypeManager = IoCManager.Resolve<IPrototypeManager>();

            _jobXenoTranslations = _prototypeManager.EnumeratePrototypes<JobPrototype>()
                .Where(j => j.Parents != null && j.Parents.Contains("CMJobXenoBase"))
                .Select(j => j.LocalizedName)
                .ToArray();

            _sortOrderOptions =
            [
                new("\u2191",
                    "ghost-target-window-type-sort-dir-asc-title",
                    (ordered, key, comp) => ordered.ThenBy(key, comp)),
                new("\u2193",
                    "ghost-target-window-type-sort-dir-desc-title",
                    (ordered, key, comp) => ordered.ThenByDescending(key, comp)),
            ];

            _selectedCategory = null;

            UpdateSortButtonAppearance();

            SortOrderButton.OnPressed += _ =>
            {
                _sortOrder = (_sortOrder + 1) % _sortOrderOptions.Length;
                UpdateSortButtonAppearance();
                Populate();
            };
        }

        private void UpdateSortButtonAppearance()
        {
            ApplyOption(SortOrderButton, _sortOrderOptions[_sortOrder]);
        }

        private static void ApplyOption(Button button, SortOption option)
        {
            button.Text = option.Label;
            button.HideTooltip();
            var tooltip = new Tooltip();
            tooltip.SetMessage(FormattedMessage.FromUnformatted(
                Loc.GetString(option.TypeLabel, ("type", Loc.GetString(option.Tooltip)))));
            button.TooltipSupplier = _ => tooltip;
        }

        private static string PlayerDisplayName(GhostWarp w) =>
            w is PlayerGhostWarp { jobName: { Length: > 0 } job } pgw
                ? $"{pgw.entityName} ({job})"
                : w.entityName;

        private static string WarpPointDisplayName(GhostWarp w) =>
            Loc.GetString("ghost-target-window-current-button", ("name", w.entityName));

        private static string DefaultDisplayName(GhostWarp w) => w switch
        {
            PlayerGhostWarp pgw => PlayerDisplayName(pgw),
            _ => WarpPointDisplayName(w),
        };

        public void UpdateWarps(IEnumerable<GhostWarp> warps)
        {
            _warps = warps.ToList();
            PopulateCategories();

            // Clear selection if the category no longer exists
            if (_selectedCategory != null &&
                !_categoryButtons.Any(cb => cb.Category.Label == _selectedCategory.Label))
            {
                _selectedCategory = null;
            }
        }

        private void PopulateCategories()
        {
            _categoryButtons.Clear();
            CategoryContainer.DisposeAllChildren();

            var players = _warps.OfType<PlayerGhostWarp>().ToList();

            // Marines: players whose job is NOT in xeno translations
            var marineJobs = players
                .Where(p => !_jobXenoTranslations.Any(j =>
                    string.Equals(j, p.jobName, StringComparison.OrdinalIgnoreCase)))
                .Select(p => p.jobName)
                .Distinct(new CaseInsensitiveComparer())
                .OrderBy(j => j, OrdinalIgnoreCaseComparer)
                .ToArray();

            if (marineJobs.Length > 0)
            {
                var jobs = marineJobs;
                var marineCategory = new WarpCategory(
                    "ghost-target-window-type-filter-marines-title",
                    w => w.Where(e => e is PlayerGhostWarp pgw &&
                        jobs.Any(j => string.Equals(j, pgw.jobName, StringComparison.OrdinalIgnoreCase))),
                    PlayerDisplayName);
                AddCollapsibleCategory(marineCategory, marineJobs, _selectedCategory?.Label == marineCategory.Label);
            }

            // Xenos: players whose job IS in xeno translations
            var xenoJobs = players
                .Where(p => _jobXenoTranslations.Any(j =>
                    string.Equals(j, p.jobName, StringComparison.OrdinalIgnoreCase)))
                .Select(p => p.jobName)
                .Distinct(new CaseInsensitiveComparer())
                .OrderBy(j => j, OrdinalIgnoreCaseComparer)
                .ToArray();

            if (xenoJobs.Length > 0)
            {
                var jobs = xenoJobs;
                var xenoCategory = new WarpCategory(
                     "ghost-target-window-type-filter-xeno-title",
                    w => w.Where(e => e is PlayerGhostWarp pgw &&
                        jobs.Any(j => string.Equals(j, pgw.jobName, StringComparison.OrdinalIgnoreCase))),
                    PlayerDisplayName);
                AddCollapsibleCategory(xenoCategory, xenoJobs, _selectedCategory?.Label == xenoCategory.Label);
            }

            if (!_warps.Any(w => w.isWarpPoint))
                return;

            var warpsCategory = new WarpCategory(
                "ghost-target-window-type-filter-warps-title",
                w => w.Where(e => e.isWarpPoint),
                WarpPointDisplayName,
                WarpsToEnd: false);
            AddCategoryButton(warpsCategory, _selectedCategory?.Label == warpsCategory.Label);
        }

        private void SelectCategory(WarpCategory? category)
        {
            _selectedCategory = _selectedCategory?.Label == category?.Label ? null : category;
            UpdateCategorySelection();
            Populate();
        }

        private void UpdateCategorySelection()
        {
            foreach (var (cat, btn) in _categoryButtons)
            {
                if (btn is Button button)
                    button.Pressed = _selectedCategory?.Label == cat.Label;
            }
        }

        private void AddCategoryButton(WarpCategory category, bool selected)
        {
            var button = new Button
            {
                Text = Loc.GetString(category.Label),
                HorizontalExpand = true,
                TextAlign = Label.AlignMode.Left,
                ToggleMode = true,
                Pressed = selected,
            };

            button.OnPressed += _ => SelectCategory(category);

            _categoryButtons.Add((category, button));
            CategoryContainer.AddChild(button);
        }

        private void AddCollapsibleCategory(WarpCategory category, string[] jobs, bool selected)
        {
            var heading = new CollapsibleHeading(Loc.GetString(category.Label));
            // heading.AddStyleClass(ContainerButton.StyleClassButton);
            heading.HorizontalExpand = true;
            heading.Label.HorizontalAlignment = HAlignment.Left;
            heading.Label.HorizontalExpand = true;
            heading.SetHeight = 29;

            heading.ChevronVisible = false;
            var indicator = new Label { Text = HeadingIndicatorCollapsed };
            if (heading.GetChild(0) is BoxContainer box)
                box.AddChild(indicator);

            heading.OnToggled += args =>
            {
                indicator.Text = args.Pressed ? HeadingIndicatorExpanded : HeadingIndicatorCollapsed;
            };

            var body = new CollapsibleBody
            {
                Margin = new Thickness(8, 5, 0, 0),
            };

            var jobList = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 5,
            };

            if (jobs.Length > 1)
            {
                // Group filter button (filters by entire category)
                var groupButton = new Button
                {
                    Text = Loc.GetString("ghost-target-window-type-filter-all-title"),
                    HorizontalExpand = true,
                    TextAlign = Label.AlignMode.Left,
                    ToggleMode = true,
                    Pressed = selected,
                    MaxWidth = 340,
                };
                groupButton.OnPressed += _ => SelectCategory(category);
                _categoryButtons.Add((category, groupButton));
                jobList.AddChild(groupButton);
            }

            // Individual job buttons
            foreach (var job in jobs)
            {
                var capturedJob = job;
                var jobCategory = new WarpCategory(
                    capturedJob,
                    w => w.Where(e => e is PlayerGhostWarp pgw &&
                        string.Equals(pgw.jobName, capturedJob, StringComparison.OrdinalIgnoreCase)),
                    PlayerDisplayName);

                var jobButton = new Button
                {
                    Text = capturedJob,
                    HorizontalExpand = true,
                    TextAlign = Label.AlignMode.Left,
                    ToggleMode = true,
                    Pressed = _selectedCategory?.Label == capturedJob,
                    ClipText = true,
                    MaxWidth = 340,
                };
                jobButton.OnPressed += _ => SelectCategory(jobCategory);
                _categoryButtons.Add((jobCategory, jobButton));
                jobList.AddChild(jobButton);
            }

            body.AddChild(jobList);

            var collapsible = new Collapsible(heading, body)
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            // Restore expanded state if the selected category is within this group
            var shouldExpand = _selectedCategory != null &&
                (_selectedCategory.Label == category.Label ||
                 jobs.Any(j => string.Equals(j, _selectedCategory.Label, StringComparison.OrdinalIgnoreCase)));
            if (shouldExpand)
            {
                collapsible.BodyVisible = true;
                indicator.Text = HeadingIndicatorExpanded;
            }

            CategoryContainer.AddChild(collapsible);
        }

        public void Populate()
        {
            ButtonContainer.DisposeAllChildren();
            AddButtons();
        }

        private IEnumerable<GhostWarp> GetSortedWarps()
        {
            var filtered = _selectedCategory != null
                ? _selectedCategory.Filter(_warps)
                : _warps.AsEnumerable();

            var warpsToEnd = _selectedCategory?.WarpsToEnd ?? true;
            var baseOrder = warpsToEnd
                ? filtered.OrderBy(w => w.isWarpPoint)
                : filtered.OrderBy(_ => 0);

            var sortOrderOption = _sortOrderOptions[_sortOrder];
            return sortOrderOption.Apply(baseOrder, w => w.entityName, OrdinalIgnoreCaseComparer);
        }

        private void AddButtons()
        {
            foreach (var entry in GetSortedWarps())
            {
                var currentButtonRef = new Button
                {
                    Text = (_selectedCategory?.DisplayName ?? DefaultDisplayName)(entry),
                    TextAlign = Label.AlignMode.Right,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    SizeFlagsStretchRatio = 1,
                    MinSize = new Vector2(340, 20),
                    ClipText = true,
                };

                currentButtonRef.OnPressed += _ => WarpClicked?.Invoke(entry.entity);
                currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);

                ButtonContainer.AddChild(currentButtonRef);
            }
        }

        private bool ButtonIsVisible(Button button)
        {
            return string.IsNullOrEmpty(_searchText) || button.Text == null ||
                   button.Text.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
        }

        private void UpdateVisibleButtons()
        {
            foreach (var child in ButtonContainer.Children)
            {
                if (child is Button button)
                    button.Visible = ButtonIsVisible(button);
            }
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text;

            UpdateVisibleButtons();
            GhostScroll.SetScrollValue(Vector2.Zero);
        }

        private sealed class CaseInsensitiveComparer : IEqualityComparer<string>
        {
            public bool Equals(string? x, string? y) =>
                string.Equals(x, y, StringComparison.OrdinalIgnoreCase);

            public int GetHashCode(string obj) =>
                obj.ToUpperInvariant().GetHashCode();
        }
    }
}
