using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.PlayingCards;

[GenerateTypedNameReferences]
public sealed partial class PlayingCardHandMenu : RadialMenu
{
    public PlayingCardHandMenu()
    {
        RobustXamlLoader.Load(this);
    }
}
