- type: department
  parent: CMDepartmentBase
  id: CMFaxResponders
  name: department-CMFaxResponders
  description: cm-department-FaxResponders-description
  color: "#8B4513"
  roles:
  - CMWeYaresponder
  - CMFreePressResponder
  primary: false
  departmentRadio: null
  headOfDepartment: null
