using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Chemistry.Master;

[GenerateTypedNameReferences]
public sealed partial class RMCChemMasterPopupWindow : DefaultWindow
{
    public RMCChemMasterPopupWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
