using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Chemistry.Master;

[GenerateTypedNameReferences]
public sealed partial class RMCChemMasterAllReagentsButton : Control
{
    public RMCChemMasterAllReagentsButton()
    {
        RobustXamlLoader.Load(this);
    }
}
