using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Chemistry.Master;

[GenerateTypedNameReferences]
public sealed partial class RMCChemMasterPresetWindow : DefaultWindow
{
    public RMCChemMasterPresetWindow()
    {
        RobustXamlLoader.Load(this);

        UsePresetNameAsLabelCheckbox.OnToggled += args =>
        {
            // When checkbox is toggled, enable/disable the label input
            BottleLabelInput.Editable = !args.Pressed;
        };
    }

    public void SetUsePresetNameAsLabel(bool value)
    {
        UsePresetNameAsLabelCheckbox.Pressed = value;
        BottleLabelInput.Editable = !value;
    }

    public bool GetUsePresetNameAsLabel()
    {
        return UsePresetNameAsLabelCheckbox.Pressed;
    }
}
