using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Chemistry.Master;

[GenerateTypedNameReferences]
public sealed partial class RMCChemMasterPresetWindow : DefaultWindow
{
    private bool _showQuickAccess = true;
    private bool _showReorder;

    public bool ShowQuickAccess => _showQuickAccess;
    public bool ShowReorder => _showReorder;

    public event Action? OnQuickAccessToggled;
    public event Action? OnReorderToggled;

    public RMCChemMasterPresetWindow()
    {
        RobustXamlLoader.Load(this);
        SetWidth = float.NaN;

        ToggleQuickAccessButton.OnPressed += _ =>
        {
            _showQuickAccess = !_showQuickAccess;
            UpdateToggleButtonText();
            OnQuickAccessToggled?.Invoke();
        };

        ToggleReorderButton.OnPressed += _ =>
        {
            _showReorder = !_showReorder;
            UpdateReorderButtonState();
            OnReorderToggled?.Invoke();
        };

        UpdateToggleButtonText();
        UpdateReorderButtonState();
    }

    private void UpdateToggleButtonText()
    {
        ToggleQuickAccessButton.Text = _showQuickAccess
            ? Loc.GetString("rmc-chem-master-preset-hide-quick-access")
            : Loc.GetString("rmc-chem-master-preset-show-quick-access");
    }

    private void UpdateReorderButtonState()
    {
        if (_showReorder)
        {
            ToggleReorderButton.AddStyleClass("Caution");
            ToggleReorderButton.Text = Loc.GetString("rmc-chem-master-preset-hide");
        }
        else
        {
            ToggleReorderButton.RemoveStyleClass("Caution");
            ToggleReorderButton.Text = Loc.GetString("rmc-chem-master-preset-reorder");
        }
    }

    public void RefreshPresetRows()
    {
        foreach (var child in SavedPresetsContainer.Children)
        {
            if (child is not RMCChemMasterPresetRow row)
                continue;
            row.MoveUpButton.Visible = _showReorder;
            row.MoveDownButton.Visible = _showReorder;
        }
    }
}
