using Content.Shared._RMC14.Chemistry.ChemMaster;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Chemistry.Master;

[GenerateTypedNameReferences]
public sealed partial class RMCChemMasterPresetEditWindow : DefaultWindow
{
    public RMCChemMasterPresetEditWindow()
    {
        RobustXamlLoader.Load(this);

        UsePresetNameAsLabelCheckbox.OnToggled += args =>
        {
            BottleLabelInput.Editable = !args.Pressed;
        };
    }

    public void SetUsePresetNameAsLabel(bool value)
    {
        UsePresetNameAsLabelCheckbox.Pressed = value;
        BottleLabelInput.Editable = !value;
    }

    public bool GetUsePresetNameAsLabel()
    {
        return UsePresetNameAsLabelCheckbox.Pressed;
    }

    public void LoadPreset(RMCChemMasterPreset preset)
    {
        PresetNameInput.Text = preset.Name;
        BottleLabelInput.Text = preset.BottleLabel;
        SetUsePresetNameAsLabel(preset.UsePresetNameAsLabel);
    }

    public RMCChemMasterPreset GetPreset(RMCPillBottleColors bottleColor, uint pillType, int? quickAccessSlot = null, string? quickAccessLabel = null)
    {
        return new RMCChemMasterPreset
        {
            Name = PresetNameInput.Text,
            BottleLabel = BottleLabelInput.Text,
            BottleColor = bottleColor,
            PillType = pillType,
            UsePresetNameAsLabel = GetUsePresetNameAsLabel(),
            QuickAccessSlot = quickAccessSlot,
            QuickAccessLabel = quickAccessLabel ?? string.Empty,
        };
    }

    public void Clear()
    {
        PresetNameInput.Text = string.Empty;
        BottleLabelInput.Text = string.Empty;
        SetUsePresetNameAsLabel(false);
    }
}
