using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Chemistry.Master;

[GenerateTypedNameReferences]
public sealed partial class RMCChemMasterPresetRow : BoxContainer
{
    private int? _selectedQuickAccessSlot;
    private readonly Dictionary<int, Button> _slotButtons = new();

    public event Action<int?>? OnQuickAccessSlotChanged;
    public event Action<string>? OnQuickAccessLabelChanged;

    public RMCChemMasterPresetRow()
    {
        RobustXamlLoader.Load(this);

        QuickAccessLabelInput.OnTextChanged += args =>
        {
            OnQuickAccessLabelChanged?.Invoke(args.Text);
        };
    }

    public void InitializeQuickAccessSlots(int maxSlots, HashSet<int>? usedSlots, int? currentSlot)
    {
        QuickAccessSlotContainer.RemoveAllChildren();
        _slotButtons.Clear();
        _selectedQuickAccessSlot = currentSlot;

        for (var i = 1; i <= maxSlots; i++)
        {
            var slot = i;
            var isUsed = usedSlots?.Contains(slot) ?? false;
            var isCurrent = currentSlot == slot;
            var button = new Button
            {
                Text = slot.ToString(),
                ToggleMode = true,
                MinWidth = 26,
                Pressed = isCurrent,
                Disabled = isUsed && !isCurrent,
                StyleClasses = { "OpenBoth" },
            };
            button.OnPressed += _ => ToggleQuickAccessSlot(slot);
            _slotButtons[slot] = button;
            QuickAccessSlotContainer.AddChild(button);
        }

        QuickAccessLabelRow.Visible = currentSlot != null;
    }

    private void ToggleQuickAccessSlot(int slot)
    {
        if (_selectedQuickAccessSlot == slot)
        {
            _selectedQuickAccessSlot = null;
            _slotButtons[slot].Pressed = false;
        }
        else
        {
            if (_selectedQuickAccessSlot != null && _slotButtons.TryGetValue(_selectedQuickAccessSlot.Value, out var oldButton))
                oldButton.Pressed = false;

            _selectedQuickAccessSlot = slot;
            _slotButtons[slot].Pressed = true;
        }

        QuickAccessLabelRow.Visible = _selectedQuickAccessSlot != null;
        OnQuickAccessSlotChanged?.Invoke(_selectedQuickAccessSlot);
    }

    public void SetQuickAccessLabel(string? label)
    {
        QuickAccessLabelInput.Text = label ?? string.Empty;
    }

    public void ToggleQuickAccessDropdown()
    {
        QuickAccessDropdown.Visible = !QuickAccessDropdown.Visible;
    }

    public void SetHasQuickAccess(bool hasQuickAccess)
    {
        if (hasQuickAccess)
        {
            QuickAccessButton.AddStyleClass(StyleNano.StyleClassButtonColorGreen);
        }
        else
        {
            QuickAccessButton.RemoveStyleClass(StyleNano.StyleClassButtonColorGreen);
        }
    }

    public int? GetSelectedQuickAccessSlot()
    {
        return _selectedQuickAccessSlot;
    }

    public void UpdateSlotAvailability(HashSet<int>? usedSlots)
    {
        foreach (var (slot, button) in _slotButtons)
        {
            var isUsed = usedSlots?.Contains(slot) ?? false;
            var isCurrent = _selectedQuickAccessSlot == slot;
            button.Disabled = isUsed && !isCurrent;
        }
    }
}
