using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Xenonids.Fruit;

[GenerateTypedNameReferences]
public sealed partial class XenoFruitChooseWindow : DefaultWindow
{
    public XenoFruitChooseWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

