using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.ARES;

[GenerateTypedNameReferences]
public sealed partial class ARESExternalTerminalSection : Control
{

    public string? SectionNameText { get => SectionName.Text;  set => SectionName.Text = value; }
    public ARESExternalTerminalSection()
    {
        RobustXamlLoader.Load(this);
    }
}
