- type: jobIcon
  parent: CMJobIconBase
  id: CMJobIconStaffOfficer
  icon:
    sprite: _RMC14/Interface/job_icons/UNMC/command
    state: staff_officer

- type: jobIcon
  parent: CMJobIconBase
  id: CMJobIconSEA
  icon:
    sprite: _RMC14/Interface/job_icons/UNMC/auxiliary_support
    state: senior_enlisted_advisor

- type: jobIcon
  parent: CMJobIconBase
  id: CMJobIconCommandingOfficer
  icon:
    sprite: _RMC14/Interface/job_icons/UNMC/command
    state: hudsquad_co

- type: jobIcon
  parent: CMJobIconBase
  id: CMJobIconExecutiveOfficer
  icon:
    sprite: _RMC14/Interface/job_icons/UNMC/command
    state: hudsquad_xo
