using Content.Shared._RMC14.Language.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client._RMC14.UserInterface.Systems.Language;

[GenerateTypedNameReferences]
public sealed partial class LanguageButton : ContainerButton
{
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;

    private static readonly StyleBoxFlat NormalStyle = new()
    {
        BackgroundColor = Color.FromHex("#1E1E23"),
        BorderColor = Color.FromHex("#383840"),
        BorderThickness = new Thickness(1),
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
        ContentMarginLeftOverride = 0,
        ContentMarginRightOverride = 4,
    };

    private static readonly StyleBoxFlat HoverStyle = new()
    {
        BackgroundColor = Color.FromHex("#26262E"),
        BorderColor = Color.FromHex("#4A4A58"),
        BorderThickness = new Thickness(1),
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
        ContentMarginLeftOverride = 0,
        ContentMarginRightOverride = 4,
    };

    private static readonly StyleBoxFlat SelectedStyle = new()
    {
        BackgroundColor = Color.FromHex("#182818"),
        BorderColor = Color.FromHex("#4CAF50"),
        BorderThickness = new Thickness(3, 1, 1, 1),
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
        ContentMarginLeftOverride = 0,
        ContentMarginRightOverride = 4,
    };

    private static readonly StyleBoxFlat DescriptionStyle = new()
    {
        BackgroundColor = Color.FromHex("#14141A"),
        BorderColor = Color.FromHex("#383840"),
        BorderThickness = new Thickness(1, 0, 1, 1),
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
        ContentMarginLeftOverride = 4,
        ContentMarginRightOverride = 4,
    };

    private static readonly StyleBoxFlat DescriptionSelectedStyle = new()
    {
        BackgroundColor = Color.FromHex("#12201A"),
        BorderColor = Color.FromHex("#4CAF50"),
        BorderThickness = new Thickness(3, 0, 1, 1),
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
        ContentMarginLeftOverride = 4,
        ContentMarginRightOverride = 4,
    };

    private bool _isSelected;
    private bool _descriptionExpanded;
    private readonly bool _hasDescription;
    private bool _xamlLoaded;
    private readonly ProtoId<LanguagePrototype> _languageId;

    public event Action<ProtoId<LanguagePrototype>, bool>? OnDescriptionExpansionChanged;

    public bool IsDescriptionExpanded => _descriptionExpanded;

    public bool IsSelected
    {
        get => _isSelected;
        set
        {
            _isSelected = value;
            UpdateVisualState();
        }
    }

    public LanguageButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Mode = ActionMode.Press;
    }

    public LanguageButton(LanguagePrototype prototype, bool isSelected) : this()
    {
        _languageId = prototype.ID;
        _isSelected = isSelected;

        NameLabel.Text = prototype.LocalizedName;
        LoadLanguageIcon(prototype);

        var description = prototype.LocalizedDescription;
        _hasDescription = !string.IsNullOrWhiteSpace(description);
        if (_hasDescription)
        {
            DescriptionLabel.Text = description;
            DescriptionLabel.FontColorOverride = Color.FromHex("#AAAAAA");
            DescriptionToggle.Visible = true;
            DescriptionToggle.OnPressed += _ => SetDescriptionExpanded(!_descriptionExpanded);
        }

        _xamlLoaded = true;
        UpdateVisualState();
    }

    public void SetDescriptionExpanded(bool expanded)
    {
        if (_descriptionExpanded == expanded)
            return;

        _descriptionExpanded = expanded;
        DescriptionPanel.Visible = _descriptionExpanded;
        UpdateDescriptionPanelStyle();
        OnDescriptionExpansionChanged?.Invoke(_languageId, _descriptionExpanded);
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();
        UpdateVisualState();
    }

    private void LoadLanguageIcon(LanguagePrototype prototype)
    {
        var spriteSystem = _entitySystemManager.GetEntitySystem<SpriteSystem>();
        if (prototype.LanguageIcon is not { } icon)
            return;

        Icon.Texture = spriteSystem.Frame0(icon);
        Icon.Visible = true;
    }

    private void UpdateVisualState()
    {
        if (!_xamlLoaded)
            return;

        if (_isSelected)
        {
            Background.PanelOverride = SelectedStyle;
            NameLabel.FontColorOverride = Color.FromHex("#7DD87F");
        }
        else if (DrawMode == DrawModeEnum.Hover)
        {
            Background.PanelOverride = HoverStyle;
            NameLabel.FontColorOverride = Color.White;
        }
        else
        {
            Background.PanelOverride = NormalStyle;
            NameLabel.FontColorOverride = Color.FromHex("#CCCCCC");
        }

        UpdateDescriptionPanelStyle();
    }

    private void UpdateDescriptionPanelStyle()
    {
        if (!_hasDescription)
            return;

        DescriptionPanel.PanelOverride = _isSelected ? DescriptionSelectedStyle : DescriptionStyle;
    }
}
