- type: rank
  id: RMCRankCLFRebel
  name: Rebel
  prefix: REB.

- type: rank
  id: RMCRankCLFRebelCommander
  name: Rebel Commander
  prefix: REBC.

# PVE
- type: rank
  id: RMCRankPVECLFLeader
  name: Sub-Cell Leader
  prefix: REB LEAD.

- type: rank
  id: RMCRanPVECLFCommander
  name: Cell Commander
  prefix: REB CMDR.
