# Names inspired after police ranks
# Differs from CM - Deputies are Officers, specialists in their field are Corporals/Sergeants, Riot Control unit leaders are Lieutenants, Marshals are Captains. CMB Synthetics are either ranked Detective/Corporal/Sergeant depending on their speciality

# Deputy
- type: rank
  id: RMCRankCMBDeputy
  name: Officer
  prefix: Off.
  paygrade: CMB

- type: rank
  id: RMCRankCMBSeniorDeputy
  name: Senior Officer
  prefix: Sr. Off.
  paygrade: CMB

# Corporal (Specialists/Very senior deputies)
- type: rank
  id: RMCRankCMBCorporal
  name: Corporal
  prefix: Cpl.
  suffix: CMB

# Sergeant (Specialists)
- type: rank
  id: RMCRankCMBSergeant
  name: Sergeant
  prefix: Sgt.
  paygrade: CMB

# Lieutenant (Team Leaders)
- type: rank
  id: RMCRankCMBLieutenant
  name: Lieutenant
  prefix: Lt.
  paygrade: CMB

# Captain (Marshal)
- type: rank
  id: RMCRankCMBMarshal
  name: Captain
  prefix: Capt.
  paygrade: CMB

# Detective
- type: rank
  id: RMCRankCMBDetective
  name: Detective
  prefix: Det.


# ICB ranks
- type: rank
  id: RMCRankICBAgent
  name: Interstellar Commerce Bureau Agent
  prefix: Agent

- type: rank
  id: RMCRankICBCorporateLiaison
  name: Interstellar Commerce Bureau Corporate Liaison
  prefix: ICB Rep.
  paygrade: ICBL

- type: rank
  id: RMCRankIHROObserver
  name: Interstellar Life Rights Observer
  prefix: "Obsv."
  paygrade: ILRO
