- type: job
  parent: CMJobBase
  id: RMCTSEPASATMedicPVE
  name: rmc-job-name-tsepa-pve-medic
  description: rmc-job-description-tsepa-pve-medic
  playTimeTracker: RMCJobSATMedicPVE
  ranks:
    RMCRankSATSeniorOperator: []
  startingGear: RMCGearSATMedicPVE
  icon: "RMCJobIconSATMedicPVE"
  joinNotifyCrew: false
  supervisors: rmc-job-supervisors-sat-tl
  accessGroups:
  - HospitalCorpsman
  - ColonistTSEPABrig
  spawnMenuRoleName: TSEPA SAT Medic (PVE)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Language
      spokenLanguages:
      - English
      - Japanese
      understoodLanguages:
      - English
      - Japanese
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillCqc: 3
        RMCSkillEndurance: 3
        RMCSkillEngineer: 2
        RMCSkillFirearms: 2
        RMCSkillFireman: 3
        RMCSkillJtac: 1
        RMCSkillMedical: 2
        RMCSkillPolice: 1
        RMCSkillMeleeWeapons: 2
        RMCSkillSurgery: 2
    - type: NpcFactionMember
      factions:
      - TSE
    - type: JobPrefix
      prefix: rmc-job-prefix-tsepa-pve-medic
    - type: AssignSquad
      squad: SquadTSEPA
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: rmc_medic_pve
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_nspa
  hidden: true

- type: startingGear
  id: RMCGearSATMedicPVE
  equipment:
    head: RMCHeadCapTSEPA
    ears: RMCHeadsetTSEPAConstable
    jumpsuit: RMCJumpsuitTSEPASAT
    gloves: RMCHandsBlack
    belt: RMCBeltHolsterPistolTSEFilledL54
    shoes: CMBootsBlack
    id: RMCIDTSEPASAT
    back: RMCSatchelTSEPA

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSATMedicPVE
  name: sat medic spawn point
  suffix: PVE
  components:
  - type: SpawnPoint
    job_id: RMCTSEPASATMedicPVE
  - type: Sprite
    layers:
    - sprite: _RMC14/Objects/Clothing/OuterClothing/TSE/TSEPA/jacket.rsi
      state: icon

- type: playTimeTracker
  id: RMCJobSATMedicPVE
  isHumanoid: true

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconSATMedicPVE
  icon:
    sprite: _RMC14/Interface/job_icons/TSE/TSEPA/sat.rsi
    state: sat_medic
