- type: job
  parent: CMJobBase
  id: RMCTSEPASATSniperPVE
  name: rmc-job-name-tsepa-pve-sniper
  description: rmc-job-description-tsepa-pve-sniper
  playTimeTracker: RMCJobSATSniperPVE
  ranks:
    RMCRankSATSeniorOperator: []
  startingGear: RMCGearSATSniperPVE
  icon: "RMCJobIconSATSniperPVE"
  joinNotifyCrew: false
  supervisors: rmc-job-supervisors-sat-tl
  accessGroups:
  - WeaponSpec
  - ColonistTSEPABrig
  spawnMenuRoleName: TSEPA SAT Sniper (PVE)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Language
      spokenLanguages:
      - English
      - Japanese
      understoodLanguages:
      - English
      - Japanese
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillCqc: 3
        RMCSkillEndurance: 3
        RMCSkillEngineer: 2
        RMCSkillFirearms: 2
        RMCSkillFireman: 3
        RMCSkillJtac: 1
        RMCSkillMedical: 2
        RMCSkillPolice: 1
        RMCSkillMeleeWeapons: 2
        RMCSkillSpecialistWeapons: 1
        RMCSkillSurgery: 1
    - type: SniperWhitelist
    - type: NpcFactionMember
      factions:
      - TSE
    - type: JobPrefix
      prefix: rmc-job-prefix-tsepa-pve-sniper
    - type: AssignSquad
      squad: SquadTSEPA
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: rmc_marksman_pve
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_nspa
  hidden: true

- type: startingGear
  id: RMCGearSATSniperPVE
  equipment:
    head: RMCHeadCapTSEPA
    ears: RMCHeadsetTSEPAConstable
    jumpsuit: RMCJumpsuitTSEPASAT
    gloves: RMCHandsBlack
    belt: RMCBeltHolsterPistolTSEFilledL54
    shoes: CMBootsBlack
    id: RMCIDTSEPASAT
    back: RMCSatchelTSEPA

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSATSniperPVE
  name: sat sniper spawn point
  suffix: PVE
  components:
  - type: SpawnPoint
    job_id: RMCTSEPASATSniperPVE
  - type: Sprite
    layers:
    - sprite: _RMC14/Objects/Clothing/OuterClothing/TSE/TSEPA/jacket.rsi
      state: icon

- type: playTimeTracker
  id: RMCJobSATSniperPVE
  isHumanoid: true

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconSATSniperPVE
  icon:
    sprite: _RMC14/Interface/job_icons/TSE/TSEPA/sat.rsi
    state: sat_sniper