- type: job
  parent: CMJobBase
  id: RMCTSEPASATTechnicianPVE
  name: rmc-job-name-tsepa-pve-technician
  description: rmc-job-description-tsepa-pve-technician
  playTimeTracker: RMCJobSATTechnicianPVE
  ranks:
    RMCRankTSEPASeniorConstable: []
  startingGear: RMCGearSATTechnicianPVE
  icon: "RMCJobIconSATTechnicianPVE"
  joinNotifyCrew: false
  supervisors: rmc-job-supervisors-sat-tl
  accessGroups:
  - CombatTech
  - ColonistTSEPABrig
  spawnMenuRoleName: TSEPA SAT Technician (PVE)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Language
      spokenLanguages:
      - English
      - Japanese
      understoodLanguages:
      - English
      - Japanese
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillCqc: 3
        RMCSkillEndurance: 3
        RMCSkillEngineer: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 3
        RMCSkillJtac: 1
        RMCSkillMedical: 2
        RMCSkillPolice: 1
        RMCSkillMeleeWeapons: 2
        RMCSkillSurgery: 1
    - type: NpcFactionMember
      factions:
      - TSE
    - type: JobPrefix
      prefix: rmc-job-prefix-tsepa-pve-technician
    - type: AssignSquad
      squad: SquadTSEPA
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: rmc_engi_pve
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_nspa
  hidden: true

- type: startingGear
  id: RMCGearSATTechnicianPVE
  equipment:
    ears: RMCHeadsetTSEPAConstable
    jumpsuit: RMCJumpsuitTSEPASAT
    gloves: RMCHandsBlack
    belt: RMCBeltHolsterPistolTSEFilledL54
    shoes: CMBootsBlack
    id: RMCIDTSEPASAT
    back: RMCSatchelTSEPA

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSATTechnicianPVE
  name: sat technician spawn point
  suffix: PVE
  components:
  - type: SpawnPoint
    job_id: RMCTSEPASATTechnicianPVE
  - type: Sprite
    layers:
    - sprite: _RMC14/Objects/Clothing/OuterClothing/TSE/TSEPA/jacket.rsi
      state: icon

- type: playTimeTracker
  id: RMCJobSATTechnicianPVE
  isHumanoid: true

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconSATTechnicianPVE
  icon:
    sprite: _RMC14/Interface/job_icons/TSE/TSEPA/sat.rsi
    state: sat_technician