using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.Vehicle.Ui;

[GenerateTypedNameReferences]
public sealed partial class RMCHardpointButton : Button
{
    public static readonly Color DefaultHoveredColor = Color.FromHex("#6AB8FF");
    public static readonly Color DefaultUnhoveredColor = Color.FromHex("#4AA3E8");
    public static readonly Color DefaultDisabledColor = Color.FromHex("#1A3D5C");
    public static readonly Color DefaultTextColor = Color.Black;
    public static readonly Color DefaultDisabledTextColor = Color.FromHex("#4AA3E8");

    private bool _initialized;
    private string? _text;
    private bool _pulse;
    private float _pulseTimer;
    private int _pulseDots = 1;

    public Color HoveredColor { get; set; } = DefaultHoveredColor;
    public Color UnhoveredColor { get; set; } = DefaultUnhoveredColor;
    public Color DisabledColor { get; set; } = DefaultDisabledColor;
    public Color TextColor { get; set; } = DefaultTextColor;
    public Color DisabledTextColor { get; set; } = DefaultDisabledTextColor;

    public string? LabelText
    {
        get => _text;
        set
        {
            _text = value;
            UpdateText();
        }
    }

    public RMCHardpointButton()
    {
        RobustXamlLoader.Load(this);
        UpdateColor();
    }

    public bool Pulse
    {
        get => _pulse;
        set
        {
            _pulse = value;
            _pulseTimer = 0f;
            _pulseDots = 1;
            UpdateText();
        }
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();
        UpdateColor();
    }

    private void UpdateColor()
    {
        ModulateSelfOverride = (Disabled, IsHovered) switch
        {
            (true, _) => DisabledColor,
            (_, true) => HoveredColor,
            _ => UnhoveredColor
        };

        UpdateText();
    }

    private void UpdateText()
    {
        if (NameScope == null)
            return;

        var color = Disabled ? DisabledTextColor : TextColor;
        var text = _text ?? string.Empty;

        if (_pulse && _text != null)
        {
            var dots = new string('.', MathHelper.Clamp(_pulseDots, 1, 3));
            text = $"{_text}{dots}";
        }

        Label.SetMarkup($"[color={color.ToHex()}][bold]{text}[/bold][/color]");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_initialized)
        {
            if (_pulse && _text != null)
            {
                _pulseTimer += args.DeltaSeconds;
                if (_pulseTimer >= 0.3f)
                {
                    _pulseTimer = 0f;
                    _pulseDots = (_pulseDots % 3) + 1;
                    UpdateText();
                }
            }

            return;
        }

        _initialized = true;
        UpdateColor();
    }
}
