using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.Vehicle;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.GameObjects;

namespace Content.Client._RMC14.Vehicle.Ui;

[GenerateTypedNameReferences]
public sealed partial class RMCVehicleWeaponsMenu : FancyWindow
{
    public event Action<string>? OnSelect;
    public event Action<bool>? OnToggleStabilization;
    private readonly IEntityManager _entManager = IoCManager.Resolve<IEntityManager>();
    private bool _suppressStabilization;

    public RMCVehicleWeaponsMenu()
    {
        RobustXamlLoader.Load(this);

        StabilizationToggle.OnToggled += args =>
        {
            if (_suppressStabilization)
                return;

            OnToggleStabilization?.Invoke(args.Pressed);
        };
    }

    public void Update(IReadOnlyList<RMCVehicleWeaponsUiEntry> hardpoints, bool canToggleStabilization, bool stabilizationEnabled)
    {
        _suppressStabilization = true;
        StabilizationToggle.Disabled = !canToggleStabilization;
        StabilizationToggle.Pressed = stabilizationEnabled;
        StabilizationToggle.Text = stabilizationEnabled ? "Stabilization: On" : "Stabilization: Off";
        _suppressStabilization = false;

        WeaponList.DisposeAllChildren();

        foreach (var hardpoint in hardpoints)
        {
            var isTurretChild = RMCVehicleTurretSlotIds.TryParse(hardpoint.SlotId, out var parentSlotId, out var childSlotId);
            var slotLabel = isTurretChild ? childSlotId : hardpoint.SlotId;

            var panel = new ContainerButton
            {
                HorizontalExpand = true,
                MinSize = new Vector2(0, 36),
                Margin = isTurretChild ? new Thickness(14, 0, 0, 0) : default
            };

            var panelBorder = hardpoint.Selected
                ? Color.FromHex("#53D188")
                : isTurretChild ? Color.FromHex("#2A4E73") : Color.FromHex("#2D5E8E");

            panel.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = isTurretChild ? Color.FromHex("#0B1522") : Color.FromHex("#0E1B2B"),
                BorderColor = panelBorder,
                BorderThickness = new Thickness(1.5f)
            };

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 6,
                Margin = new Thickness(6, 6),
                HorizontalExpand = true,
                MouseFilter = MouseFilterMode.Ignore
            };

            panel.AddChild(root);
            panel.OnPressed += _ =>
            {
                if (hardpoint.Selectable)
                    OnSelect?.Invoke(hardpoint.SlotId);
            };

            if (isTurretChild)
            {
                var bar = new PanelContainer
                {
                    MinSize = new Vector2(4, 0),
                    VerticalExpand = true,
                    Margin = new Thickness(0, 4, 0, 4),
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = Color.FromHex("#2D7FB8")
                    }
                };

                root.AddChild(bar);
            }

            var spriteView = new SpriteView
            {
                Stretch = SpriteView.StretchMode.Fill,
                VerticalAlignment = Control.VAlignment.Center,
                MinSize = new Vector2(44, 44),
                OverrideDirection = Direction.South
            };

            if (hardpoint.InstalledEntity.HasValue &&
                _entManager.TryGetEntity(hardpoint.InstalledEntity.Value, out var installed) &&
                installed is { } installedUid &&
                _entManager.EntityExists(installedUid))
            {
                spriteView.SetEntity(installedUid);
            }

            root.AddChild(spriteView);

            var centerColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 1,
                HorizontalExpand = true
            };

            var header = $"{slotLabel} ({hardpoint.HardpointType})";
            var nameText = hardpoint.HasItem
                ? hardpoint.InstalledName ?? header
                : Loc.GetString("rmc-vehicle-weapons-ui-empty-slot");

            centerColumn.AddChild(new Label
            {
                Text = nameText,
                FontColorOverride = Color.FromHex("#E1EEFF")
            });

            var metaParts = new List<string>
            {
                isTurretChild
                    ? Loc.GetString("rmc-vehicle-weapons-ui-turret-slot", ("slot", header))
                    : Loc.GetString("rmc-vehicle-weapons-ui-slot", ("slot", header))
            };

            if (isTurretChild)
                metaParts.Add(Loc.GetString("rmc-vehicle-weapons-ui-mounted-to", ("slot", parentSlotId)));

            if (!string.IsNullOrWhiteSpace(hardpoint.OperatorName))
            {
                var operatorText = hardpoint.OperatorIsSelf
                    ? Loc.GetString("rmc-vehicle-weapons-ui-operator-self")
                    : Loc.GetString("rmc-vehicle-weapons-ui-operator", ("name", hardpoint.OperatorName));

                metaParts.Add(operatorText);
            }

            centerColumn.AddChild(new Label
            {
                Text = string.Join(" | ", metaParts),
                FontColorOverride = Color.FromHex("#8FA7C2")
            });

            var ammoParts = new List<string>();
            if (hardpoint.HasAmmo)
            {
                var chamberMax = hardpoint.MagazineSize > 0 ? hardpoint.MagazineSize : hardpoint.AmmoCapacity;
                ammoParts.Add(Loc.GetString("rmc-vehicle-weapons-ui-chambered", ("current", hardpoint.AmmoCount), ("max", chamberMax)));
            }
            else
            {
                ammoParts.Add(Loc.GetString("rmc-vehicle-weapons-ui-ammo-none"));
            }

            if (hardpoint.HasMagazineData && hardpoint.MaxStoredMagazines > 0)
                ammoParts.Add(Loc.GetString("rmc-vehicle-weapons-ui-stored", ("current", hardpoint.StoredMagazines), ("max", hardpoint.MaxStoredMagazines)));

            centerColumn.AddChild(new Label
            {
                Text = string.Join(" | ", ammoParts),
                FontColorOverride = Color.FromHex("#6BC7FF")
            });

            var rightColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 4,
                VerticalAlignment = Control.VAlignment.Center,
                MinSize = new Vector2(110, 0)
            };

            var statusText = hardpoint.Selected
                ? Loc.GetString("rmc-vehicle-weapons-ui-selected")
                : !hardpoint.Selectable && !string.IsNullOrWhiteSpace(hardpoint.OperatorName)
                    ? Loc.GetString("rmc-vehicle-weapons-ui-in-use")
                    : !hardpoint.Selectable && hardpoint.HasItem
                        ? Loc.GetString("rmc-vehicle-weapons-ui-unavailable")
                        : hardpoint.Selectable
                            ? Loc.GetString("rmc-vehicle-weapons-ui-select")
                            : Loc.GetString("rmc-vehicle-weapons-ui-empty-slot");

            rightColumn.AddChild(BuildTag(statusText));

            root.AddChild(centerColumn);
            root.AddChild(rightColumn);

            WeaponList.AddChild(panel);
        }
    }

    private static PanelContainer BuildTag(string text)
    {
        var panel = new PanelContainer
        {
            MinSize = new Vector2(86, 22),
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
            MouseFilter = MouseFilterMode.Ignore
        };

        panel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#16273A"),
            BorderColor = Color.FromHex("#2D5E8E"),
            BorderThickness = new Thickness(1)
        };

        panel.AddChild(new Label
        {
            Text = text,
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
            FontColorOverride = Color.FromHex("#9DB5D1")
        });

        return panel;
    }
}


