using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.Weapons.Ranged.Ammo.BulletBox;
using Content.Shared._RMC14.Vehicle;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Vehicle.Ui;

[GenerateTypedNameReferences]
public sealed partial class RMCVehicleAmmoLoaderMenu : FancyWindow
{
    public event Action<string, int, RMCVehicleAmmoLoaderSlotAction>? OnSlotSelected;
    private readonly IEntityManager _entManager = IoCManager.Resolve<IEntityManager>();

    public RMCVehicleAmmoLoaderMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(
        IReadOnlyList<RMCVehicleAmmoLoaderUiEntry> hardpoints,
        int ammoAmount,
        int ammoMax,
        EntProtoId? ammoPrototype)
    {
        HardpointList.DisposeAllChildren();

        if (hardpoints.Count == 0)
        {
            HardpointList.AddChild(new Label
            {
                Text = Loc.GetString("rmc-vehicle-ammo-loader-ui-no-hardpoints"),
                FontColorOverride = Color.FromHex("#8FA7C2")
            });
            return;
        }

        foreach (var hardpoint in hardpoints)
        {
            var panel = new PanelContainer
            {
                HorizontalExpand = true,
                MinSize = new Vector2(0, 42)
            };

            panel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#0E1B2B"),
                BorderColor = Color.FromHex("#2D5E8E"),
                BorderThickness = new Thickness(1.5f)
            };

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 12,
                Margin = new Thickness(10, 10),
                HorizontalExpand = true
            };

            panel.AddChild(root);

            var spriteView = new SpriteView
            {
                Stretch = SpriteView.StretchMode.Fill,
                VerticalAlignment = Control.VAlignment.Center,
                MinSize = new Vector2(56, 56),
                OverrideDirection = Direction.South
            };

            if (hardpoint.InstalledEntity.HasValue &&
                _entManager.TryGetEntity(hardpoint.InstalledEntity.Value, out var installed) &&
                installed is { } installedUid &&
                _entManager.EntityExists(installedUid))
            {
                spriteView.SetEntity(installedUid);
            }

            root.AddChild(spriteView);

            var centerColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 8,
                HorizontalExpand = true
            };

            var header = Loc.GetString(
                "rmc-vehicle-ammo-loader-ui-slot",
                ("slot", hardpoint.SlotId),
                ("type", hardpoint.HardpointType));

            var nameText = hardpoint.InstalledName ?? header;

            centerColumn.AddChild(new Label
            {
                Text = nameText,
                FontColorOverride = Color.FromHex("#E1EEFF")
            });

            centerColumn.AddChild(new Label
            {
                Text = header,
                FontColorOverride = Color.FromHex("#8FA7C2")
            });

            var ammoSlots = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                HorizontalExpand = true
            };

            foreach (var ammoSlot in hardpoint.AmmoSlots)
                ammoSlots.AddChild(CreateAmmoSlotButton(hardpoint, ammoSlot, ammoPrototype));

            centerColumn.AddChild(ammoSlots);

            root.AddChild(centerColumn);

            HardpointList.AddChild(panel);
        }
    }

    private Control CreateAmmoSlotButton(
        RMCVehicleAmmoLoaderUiEntry hardpoint,
        RMCVehicleAmmoLoaderUiAmmoSlot ammoSlot,
        EntProtoId? ammoPrototype)
    {
        var ratio = ammoSlot.Capacity > 0
            ? Math.Clamp(ammoSlot.Rounds / (float) ammoSlot.Capacity, 0f, 1f)
            : 0f;

        var canInteract = ammoSlot.CanLoad || ammoSlot.CanUnload;
        var button = new Button
        {
            MinSize = new Vector2(70, 84),
            MaxSize = new Vector2(70, 84),
            Disabled = !canInteract,
            EnableAllKeybinds = true,
            ToolTip = Loc.GetString(
                "rmc-vehicle-ammo-loader-ui-slot-tooltip",
                ("current", ammoSlot.Rounds),
                ("max", ammoSlot.Capacity))
        };

        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = ammoSlot.IsReadySlot
                ? Color.FromHex("#102238")
                : Color.FromHex("#0B1724"),
            BorderColor = GetAmmoSlotBorderColor(ammoSlot, ratio),
            BorderThickness = new Thickness(ammoSlot.IsReadySlot ? 2f : 1.4f)
        };

        button.OnPressed += args =>
        {
            var action = args.Event.Function == EngineKeyFunctions.UIRightClick
                ? RMCVehicleAmmoLoaderSlotAction.Unload
                : ammoSlot.CanLoad
                    ? RMCVehicleAmmoLoaderSlotAction.Load
                    : RMCVehicleAmmoLoaderSlotAction.Unload;

            if (action == RMCVehicleAmmoLoaderSlotAction.Load && !ammoSlot.CanLoad)
                return;

            if (action == RMCVehicleAmmoLoaderSlotAction.Unload && !ammoSlot.CanUnload)
                return;

            OnSlotSelected?.Invoke(hardpoint.SlotId, ammoSlot.SlotIndex, action);
        };

        var column = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 3,
            Margin = new Thickness(6, 5),
            MouseFilter = Control.MouseFilterMode.Ignore
        };

        var header = new Label
        {
            Text = ammoSlot.Label,
            HorizontalAlignment = Control.HAlignment.Center,
            FontColorOverride = ammoSlot.IsReadySlot ? Color.FromHex("#E1EEFF") : Color.FromHex("#8FA7C2"),
            MouseFilter = Control.MouseFilterMode.Ignore
        };
        column.AddChild(header);

        var iconHolder = new Control
        {
            MinSize = new Vector2(42, 34),
            MaxSize = new Vector2(42, 34),
            HorizontalAlignment = Control.HAlignment.Center,
            MouseFilter = Control.MouseFilterMode.Ignore
        };

        if (ammoSlot.Rounds > 0)
        {
            var icon = new BulletBoxPrototypeView(GetBulletBoxVisual(ratio))
            {
                MinSize = new Vector2(42, 34),
                MaxSize = new Vector2(42, 34),
                Stretch = SpriteView.StretchMode.Fill,
                OverrideDirection = Direction.South,
                HorizontalAlignment = Control.HAlignment.Center,
                MouseFilter = Control.MouseFilterMode.Ignore
            };

            if (ammoPrototype is { } prototype)
            {
                icon.SetPrototype(prototype);
            }
            else if (hardpoint.InstalledEntity.HasValue &&
                     _entManager.TryGetEntity(hardpoint.InstalledEntity.Value, out var installed) &&
                     installed is { } installedUid &&
                     _entManager.EntityExists(installedUid))
            {
                icon.SetEntity(installedUid);
            }

            iconHolder.AddChild(icon);
        }

        column.AddChild(iconHolder);

        var bar = new ProgressBar
        {
            MinValue = 0f,
            MaxValue = 1f,
            Value = ratio,
            MinSize = new Vector2(54, 7),
            HorizontalAlignment = Control.HAlignment.Center,
            MouseFilter = Control.MouseFilterMode.Ignore
        };

        bar.BackgroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1E2B3B"),
            BorderColor = Color.Transparent,
            BorderThickness = new Thickness(0f)
        };

        bar.ForegroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = GetAmmoFillColor(ratio),
            BorderColor = Color.Transparent,
            BorderThickness = new Thickness(0f)
        };

        column.AddChild(bar);
        column.AddChild(new Label
        {
            Text = $"{ammoSlot.Rounds}/{ammoSlot.Capacity}",
            HorizontalAlignment = Control.HAlignment.Center,
            FontColorOverride = Color.FromHex("#C7D9ED"),
            MouseFilter = Control.MouseFilterMode.Ignore
        });

        button.AddChild(column);
        return button;
    }

    private static Color GetAmmoSlotBorderColor(RMCVehicleAmmoLoaderUiAmmoSlot slot, float ratio)
    {
        if (slot.CanLoad)
            return Color.FromHex("#6BC7FF");

        if (slot.CanUnload)
            return Color.FromHex("#D6C45A");

        return ratio >= 1f ? Color.FromHex("#53D188") : Color.FromHex("#324B65");
    }

    private static Color GetAmmoFillColor(float ratio)
    {
        if (ratio >= 0.66f)
            return Color.FromHex("#53D188");

        if (ratio >= 0.33f)
            return Color.FromHex("#D6C45A");

        return ratio > 0f ? Color.FromHex("#E1786A") : Color.FromHex("#324B65");
    }

    private static BulletBoxVisuals GetBulletBoxVisual(float ratio)
    {
        return ratio switch
        {
            >= 1f => BulletBoxVisuals.Full,
            >= 0.66f => BulletBoxVisuals.High,
            >= 0.33f => BulletBoxVisuals.Medium,
            > 0f => BulletBoxVisuals.Low,
            _ => BulletBoxVisuals.Empty
        };
    }

    private sealed class BulletBoxPrototypeView : EntityPrototypeView
    {
        private readonly BulletBoxVisuals _visual;

        public BulletBoxPrototypeView(BulletBoxVisuals visual)
        {
            _visual = visual;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ApplyVisual();
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            ApplyVisual();
        }

        private void ApplyVisual()
        {
            if (Entity is not { } entity ||
                !EntMan.TryGetComponent(entity.Owner, out AppearanceComponent? appearance))
            {
                return;
            }

            var appearanceSystem = EntMan.System<AppearanceSystem>();
            appearanceSystem.SetData(entity.Owner, BulletBoxLayers.Fill, _visual, appearance);
            appearanceSystem.OnChangeData(entity.Owner, entity.Comp1, appearance);
        }
    }
}
