using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.Vehicle;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.GameObjects;

namespace Content.Client._RMC14.Vehicle.Ui;

[GenerateTypedNameReferences]
public sealed partial class RMCVehicleWeaponsMenu : FancyWindow
{
    public event Action<string>? OnSelect;
    private readonly IEntityManager _entManager = IoCManager.Resolve<IEntityManager>();

    public RMCVehicleWeaponsMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(IReadOnlyList<RMCVehicleWeaponsUiEntry> hardpoints)
    {
        WeaponList.DisposeAllChildren();

        foreach (var hardpoint in hardpoints)
        {
            var panel = new PanelContainer
            {
                HorizontalExpand = true,
                MinSize = new Vector2(0, 42)
            };

            panel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#0E1B2B"),
                BorderColor = Color.FromHex("#2D5E8E"),
                BorderThickness = new Thickness(1.5f)
            };

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                Margin = new Thickness(8, 8),
                HorizontalExpand = true
            };

            panel.AddChild(root);

            var spriteView = new SpriteView
            {
                Stretch = SpriteView.StretchMode.Fill,
                VerticalAlignment = Control.VAlignment.Center,
                MinSize = new Vector2(56, 56),
                OverrideDirection = Direction.South
            };

            if (hardpoint.InstalledEntity.HasValue &&
                _entManager.TryGetEntity(hardpoint.InstalledEntity.Value, out var installed) &&
                installed is { } installedUid &&
                _entManager.EntityExists(installedUid))
            {
                spriteView.SetEntity(installedUid);
            }

            root.AddChild(spriteView);

            var centerColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 2,
                HorizontalExpand = true
            };

            var header = $"{hardpoint.SlotId} ({hardpoint.HardpointType})";
            var nameText = hardpoint.HasItem
                ? hardpoint.InstalledName ?? header
                : Loc.GetString("rmc-vehicle-weapons-ui-empty-slot");

            centerColumn.AddChild(new Label
            {
                Text = nameText,
                FontColorOverride = Color.FromHex("#E1EEFF")
            });

            centerColumn.AddChild(new Label
            {
                Text = hardpoint.HasItem ? header : $"Slot: {header}",
                FontColorOverride = Color.FromHex("#8FA7C2")
            });

            if (hardpoint.HasAmmo)
            {
                var chamberMax = hardpoint.MagazineSize > 0 ? hardpoint.MagazineSize : hardpoint.AmmoCapacity;
                centerColumn.AddChild(new Label
                {
                    Text = Loc.GetString("rmc-vehicle-weapons-ui-chambered", ("current", hardpoint.AmmoCount), ("max", chamberMax)),
                    FontColorOverride = Color.FromHex("#6BC7FF")
                });
            }
            else
            {
                centerColumn.AddChild(new Label
                {
                    Text = Loc.GetString("rmc-vehicle-weapons-ui-ammo-none"),
                    FontColorOverride = Color.FromHex("#6BC7FF")
                });
            }

            if (hardpoint.HasMagazineData && hardpoint.MaxStoredMagazines > 0)
            {
                centerColumn.AddChild(new Label
                {
                    Text = Loc.GetString("rmc-vehicle-weapons-ui-stored", ("current", hardpoint.StoredMagazines), ("max", hardpoint.MaxStoredMagazines)),
                    FontColorOverride = Color.FromHex("#6BC7FF")
                });
            }

            if (!string.IsNullOrWhiteSpace(hardpoint.OperatorName))
            {
                var operatorText = hardpoint.OperatorIsSelf
                    ? Loc.GetString("rmc-vehicle-weapons-ui-operator-self")
                    : Loc.GetString("rmc-vehicle-weapons-ui-operator", ("name", hardpoint.OperatorName));

                centerColumn.AddChild(new Label
                {
                    Text = operatorText,
                    FontColorOverride = Color.FromHex("#9DB5D1")
                });
            }

            var rightColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 6,
                VerticalAlignment = Control.VAlignment.Center,
                MinSize = new Vector2(130, 0)
            };

            var selectLabel = hardpoint.Selected
                ? Loc.GetString("rmc-vehicle-weapons-ui-selected")
                : !hardpoint.Selectable && !string.IsNullOrWhiteSpace(hardpoint.OperatorName)
                    ? Loc.GetString("rmc-vehicle-weapons-ui-in-use")
                    : Loc.GetString("rmc-vehicle-weapons-ui-select");

            var select = new RMCHardpointButton
            {
                LabelText = selectLabel,
                Disabled = !hardpoint.Selectable,
                MinSize = new Vector2(98, 24)
            };

            if (hardpoint.Selected)
            {
                select.UnhoveredColor = Color.FromHex("#53D188");
                select.HoveredColor = Color.FromHex("#6DE1A0");
            }

            select.OnPressed += _ => OnSelect?.Invoke(hardpoint.SlotId);

            rightColumn.AddChild(select);

            root.AddChild(centerColumn);
            root.AddChild(rightColumn);

            WeaponList.AddChild(panel);
        }
    }
}
