using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Dropship;

[GenerateTypedNameReferences]
public sealed partial class DropshipTerminalWindow : FancyWindow
{
    public DropshipTerminalWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
