- type: job
  parent: CMSurvivor
  id: RMCSurvivorHybrisaTSEPAInspector
  name: rmc-job-name-survivor-tsepa-inspector
  description: cm-job-description-commanding-officer
  spawnMenuRoleName: TSEPA Inspector (Hybrisa Survivor)
  playTimeTracker: RMCJobSurvivorCO
  ranks:
    RMCRankTSEPAInspector: []
  startingGear: RMCGearSurvivorHybrisaTSEPAInspector
  accessGroups:
  - ColonistAllAccessNoArmory
  - ColonistTSEPA
  roleWeight: 0.25
  icon: "RMCJobIconTSEPAInspector"
  hasIcon: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: RMCSurvivor
    - type: Skills
      skills:
        RMCSkillPolice: 2
        RMCSkillCqc: 3
        RMCSkillConstruction: 1
        RMCSkillLeadership: 2
        RMCSkillMedical: 2
        RMCSkillEngineer: 1
        RMCSkillFireman: 2
        RMCSkillFirearms: 2
        RMCSkillMeleeWeapons: 1
        RMCSkillEndurance: 3
    - type: MarineOrders
    - type: RMCPointing
    - type: RMCTrackable
    - type: CommandAccent
    - type: InnateCommandSpeech
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: NpcFactionMember
      factions:
      - TSE
      - Civilian
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetNoGun
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: rmc_commander
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_nspa
    - type: JobPrefix
      prefix: rmc-job-prefix-survivor-tsepa-inspector
  useLoadoutOfJob: RMCSurvivorCommandingOfficer # for inheritance

- type: startingGear
  id: RMCGearSurvivorHybrisaTSEPAInspector
  equipment:
    id: RMCIDCardTSEPAInspectorSurvivor
    jumpsuit: RMCJumpsuitTSEPASurvivorInspector
    outerClothing: RMCArmourM4TSEPAChief
    eyes: RMCGlassesSecurityBlue
    head: RMCHeadCapTSEPAPeakedGold
    suitstorage: RMCWeaponSMGPDW90
    belt: RMCBeltMarinePDW90
    back: RMCSatchelTSEPAFillSurvivorTSEPAInspector
    gloves: RMCHandsVeteran # TODO RMC14: swat gloves
    shoes: RMCShoesLaceup
    ears: RMCHeadsetSurvivorTSEPA
    pocket1: RMCPouchSurvivalBlackFilled
    pocket2: RMCPouchGeneralLargeFilledSurvivorTSEPAInspector

- type: entity
  parent: RMCJumpsuitTSEPA
  id: RMCJumpsuitTSEPASurvivorInspector
  suffix: Webbing
  components:
  - type: WebbingClothing
    startingWebbing: RMCWebbingSurvivorTSEPAInspector

- type: entity
  parent: RMCWebbingHolsterBlack
  id: RMCWebbingSurvivorTSEPAInspector
  suffix: Inspector, Survivor, Filled
  components:
  - type: StorageFill
    contents:
    - id: RMCWeaponPistolL54Tactical
    - id: RMCMagazinePistolL54
    - id: RMCMagazinePistolL54

- type: entity
  parent: RMCPouchGeneralLarge
  id: RMCPouchGeneralLargeFilledSurvivorTSEPAInspector
  suffix: Filled, Survivor, Inspector
  components:
  - type: StorageFill
    contents:
    - id: CMClipboard
    - id: CMPenFountain

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointHybrisaTSEPAInspector
  name: hybrisa tsepa inspector spawn point
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorHybrisaTSEPAInspector
  - type: Sprite
    state: co_spawn
