lore-examinable-verb-text = Lore
lore-examinable-verb-disabled = Recall further detail about this object.

rmc-lore-examinable-trimax-polarized-shades = TriMax's latest 'TactOptix' line comes with advanced polarization and lightweight ballistic lenses capable of shrugging off small shrapnel impacts. A favorite among frontline operators and deep-space scouts, these shades are marketed as 'combat-tested and action-approved.' Rumors abound of lucky users surviving close-range laser shots thanks to the multi-reflective lens coating, though TriMax's official stance is to 'Stop standing in front of lasers'.
rmc-lore-examinable-trimex-personal-shades = Marketed as 'TriMex,' with an 'E' to sidestep copyright, these knockoffs are popular with penny-pinching spacers and wannabe badasses. While the real deal boasts patented mirror refraction for atomic flash, solar radiation, and targeting laser protection, these cut-rate imitations barely keep UV rays at bay. As for that famous story of a laser pistol reflecting off the originals? Good luck finding anyone who believes these could pull it off. But hey, they’re cheap, and their 'Save the Budget and Look Cool Doing It' slogan really sells it.

rmc-lore-examinable-m3-eod-pattern-heavy-armor = This configuration of the iconic armor was developed during the War between the SPP and UNMC - Designed in response to a need for higher protection for ComTechs assigned as EODs during the conflict, this is the pinnacle of protection for your average marine. The shoulders and kneepads have both been expanded upon heavily, covering up the arteries on each limb. A special spall liner was developed for this suit, with the same technology being used in the M70 Flak Jacket being developed at the same time.
rmc-lore-examinable-armor-xm4-pattern-intel-armor = AEGIS Perfection. The XM4 Soldier Awareness System mixes M4-style hard armor and a distributed series of motion sensors clipped onto the breastplate. When connected to any HUD optic, it replicates the effects of an M314 Motion Detector unit, increasing user situational awareness. It is currently undergoing field trials by intelligence operatives.

rmc-lore-examinable-thirteen-loko = A rarity among modern markets, Thirteen Loko is an all-Earth original. With a name coined by the general consensus that only the mildly insane willing to imbibe it, this energy drink has garnered a notorious reputation for itself and a sizeable cult following to match it. After a series of legal proceedings by Weston-Yamada, denatured cobra venom was removed from the recipe, much to the disappointment of the drink's consumers.
rmc-lore-examinable-boda = Designed back in 2109, the advertising campaign for BODA started out as an attempt by the SPP to win the hearts and minds of colonists and settlers across the galaxy. Soon after, the ubiquitous cyan vendors and large supplies of the drink began to crop up in UN warehouses with seemingly no clear origin. Despite some concerns, after initial testing determined that the stored products were safe for consumption and surprisingly popular when blind-tested with focus groups, the strange surplus of BODA was authorized for usage within the UN-associated colonies. Subsequently, it enjoyed a relative popularity before falling into obscurity in the coming decades as supplies dwindled.
rmc-lore-examinable-red-hot-bottle = Supposedly designed as a middle-ground flavor between ketchup and cayenne, this brand of spicy goodness achieved critical acclaim throughout UN space within both colonies and vessels alike. The sudden and widespread adoption was curiously timed with the near-simultaneous shelving of the original 'ULTRA' hot sauce

rmc-lore-examinable-pitchblende = Colonies all over the Sector mine extensively for pitchblende - uranium ore. It finds use in outdated fission reactors, nuclear weapons, and more commonly armor-piercing munitions. A W-Y funded research team determined that radiation poisoning from using these munitions is 'negligible'.

rmc-lore-examinable-bottle-of-bone-gel = Bone gel is a biological synthetic bone-analogue with the consistency of clay. It is capable of fixing hairline fractures and complex fractures alike. Bone gel should not be used to fix missing bone, as it does not replace the body's bone marrow. Overuse in a short period may cause acute immunodeficiency or anemia.

rmc-lore-examinable-fountain-pen = "More than just a tool for writing, AEGIS' fountain pen is a symbol of distinction and authority within the ranks of the United Nations Marine Corps, reffered to as UNMC. It is a legacy item, exclusively handed out to the top-tier command personnel, each pen a tribute to the recipient's leadership and dedication.
                                    AEGIS, renowned for their weapons technology, took a different approach in crafting this piece. The fountain pen, though seemingly a departure from their usual field, is deeply ingrained with the company's engineering philosophy, embodying precision, functionality, and robustness.
                                    The golden accents are not mere embellishments; they're an identifier, setting apart these pens and their owners from the rest. The gold is meticulously alloyed with a durable metallic substance, granting it resilience to daily wear and tear. Such resilience is symbolic of the tenacity and perseverance required of UNMC command personnel.
                                    Each pen is equipped with an intricate color changing mechanism, allowing the user to switch between various ink colors. This feature, inspired by the advanced targeting systems of AEGIS' weaponry, uses miniaturized actuators and precision-ground components to smoothly transition the ink flow. A simple twist of the pen's body activates the change, rotating the internal ink cartridges into place with mechanical grace, ready for the user's command.
                                    The ink colors are not chosen arbitrarily. Each represents a different echelon within the UNMC, allowing the pen's owner to write in the hue that corresponds with their rank or the rank of the recipient of their written orders. This acts as a silent testament to the authority of their words, as if each stroke of the pen echoes through the halls of UNMC authority.
                                    Despite its ornate appearance, the pen is as robust as any AEGIS weapon, reflecting the company's commitment to reliability and durability. The metal components are corrosion-resistant, ensuring the pen's longevity, even under the challenging conditions often faced by UNMC high command.
                                    The fusion of luxury and utility, the blend of gold and metal, is an embodiment of the hard-won elegance of command, of the fusion between power and grace. It's more than a writing instrument - it's an emblem of leadership, an accolade to the dedication and strength of those who bear it. AEGIS' fountain pen stands as a monument to the precision, integrity, and courage embodied by the UNMC's highest-ranking officers."

rmc-lore-examinable-s5-red-dot-sight = An all-weather collimator sight, designated as the AN/PVQ-64 Dot Sight. Equipped with a sunshade to increase clarity in bright conditions and resist weathering. Compact and efficient, a marvel of military design, until you realize that this is actually just an off-the-shelf design that got a military designation slapped on.
rmc-lore-examinable-s6-reflex-sight = A simple folding reflex sight designated as the AN/PVG-72 Reflex Sight, compatible with most rail systems. Bulky and built to last, it can link with military HUDs for limited point-of-aim calculations.
rmc-lore-examinable-s8-4x-telescopic-scope = An intermediate-power Armat scope designated as the AN/PVQ-31 4x Optic. Fairly basic, but both durable and functional... enough. 780 meters is about as far as one can push the 10x24mm cartridge, really.
rmc-lore-examinable-s4-2x-telescopic-mini-scope = A light-duty optic, designated as the AN/PVQ-45 2x Optic. Suited towards short to medium-range engagements. Users are advised to zero it often, as the first mass-production batch had a tendency to drift in one direction or another with sustained use.
rmc-lore-examinable-b8-smart-scope = An experimental fire-control optic capable of linking into compatible IFF systems on certain weapons, designated the XAN/PVG-110 Smart Scope. Experimental technology developed by AEGIS, who have assured that all previously reported issues with false-negative IFF recognitions have been solved. Make sure to check the sight after every deployment, just in case.
rmc-lore-examinable-laser-sight = A standard visible-band laser module designated as the AN/PEQ-42 Laser Sight. Can be mounted onto any firearm that has a lower rail large enough to accommodate it.
rmc-lore-examinable-xm-vesg-1-flamer-nozzle = The Experimental Volatile-Exothermic-Sphere-Generator clip-on nozzle attachment for the M34 incinerator unit was specifically designed to allow marines to launch fireballs into enemy foxholes and bunkers. Despite the gel and resin coating, the flaming ball of naptha tears apart due the drag caused by launching it through the air, leading marines to use the attachment as a makeshift firework launcher during shore leave.

rmc-lore-examinable-hjra-12-extreme-intensity-incendiary-rocket = This incendiary rocket uses an experimental chemical designated 'R-189' by the SPP. It is designed to melt through fortifications and bunkers but is most commonly used in an anti-personnel role due to over-issuing and the tempeartures after use in its intended role leaving behind a cloud of super-heated air, preventing troops' advance.
rmc-lore-examinable-ar10-assault-rifle = The AR10 was initially manufactured by the Armalite corporation (bought by Weston-Yamada in 2002) in the 1950s. It was the first production rifle to incorporate many new and innovative features, such as a gas operated bolt and carrier system. Only 10,000 were ever produced, and the only national entities to use them were Portugal and Sudan. Since the end of the 20th century, these rifles - alongside the far more common M16 and AR15 - have floated around the less civillised areas of space, littering jungles and colony floors with their uncommon cased ammunition - a rarity since the introduction of pulse munitions. This rifle has the word \"Salazar\" engraved on its side.
rmc-lore-examinable-m54c-ap-magazine = Unlike standard HEAP magazines, these reserve bullets do not have depleted uranium tips. Instead, these rounds trade off some of their bullet package for a lighter weight, reducing damage but increasing penetration capabilities and muzzle velocity.

rmc-lore-examinable-xm-88-heavy-rifle = Originally developed by AEGIS Battlefield Armaments for the government of the state of Greater Brazil for use against mechanized infantry. The platform features an onboard computerized targeting system, sensor array, and an electronic autoloader; these features work in tandem to reduce and render inert armor on the users target with successive hits. The Almayer was issued a small amount of XM88s while preparing for Operation Swamp Hopper with the UNS Nan-Shan.
rmc-lore-examinable-type-64-submachine-gun = The Type 64 finds its way into the hands of more than just SPP soldiers, it has an active life with rebel groups, corporate security forces, mercenaries, less well-armed militaries, and just about everything or everyone in between.

rmc-lore-examinable-smart-gun = The ML66A smart gun system was designed to provide UNMC squads with the mobile heavy firepower and raw lead-spitting capacity proven necessary on the modern battlefield. It utilizes groundbreaking technologies originating from Aegis Armaments research and development to rapidly identify its targets in the field, and allows the user to target, or ignore, specific IFF frequencies on the fly.
                                UNMC models are hard-wired to the IFF frequencies used by marine forces, as to avoid friendly fire incidents, and streamline use for the smart gunner in the heat of battle. Additionally, it has several motion tracking sensors built into the gun and accompanying rig able to relay any motion it detects straight to the user's HUD, allowing for even faster target acquisition.
                                Although more advanced smart guns exist, the ML66A has proven to be the perfect balance of affordability and capability for a large scale military such as the UNMC. Research on the IFF technologies required for the smart gun took several decades to complete, an endeavor partially funded by the UN to ensure it was the first nation to get its hands on the promising new technology. Although, the TSE quickly secured its own variants for use with the Royal Crown Marines.

rmc-lore-examinable-m54c-mk2 = The Aegis Armaments M54C Mk2 is the ubiquitous standard issue rifle in the UNMC, and the embodiment of a true space age rifle. The M54 platform was built off of decades of field experience fighting in the newly discovered and varied environments the greater universe had to offer. Withstanding the environments of earth was no longer enough; a true space age rifle had to withstand the extremes of space.
                                The platform dominated in UNMC trials thanks to its innovative design and caseless ammunition usage. The UNMC quickly ordered a large production run of M54C Mk1s to get field feedback before committing to a new standard issue rifle. While still effective, after extended use the flaws of the Mk1 were clear; a lack of modularity combined with bulky magazines contributed to an overall lackluster performance. Aegis, not wanting to lose the contract, swiftly came up with the Mk2.
                                The M54C Mk2 improves upon the Mk1 mainly in its attachment compatibility. While the Mk1 lacked a standardized attachment mounting system, the Mk2 supported nearly every standard attachment mounting system employed by the UNMC. Additionally, the larger bulky magazines of the Mk1 were exchanged for smaller and more ergonomic magazines, improving reload times and ammunition storage efficiency.
                                Because of its effectiveness within the marine corp, the M54C Mk2 has seen adoption by several PMC groups, and even some colonial riot response teams. Its modularity and easily replaceable parts make it extremely adaptable to any given organization's needs, as well as allowing the average soldier to perform even advanced maintenance.

rmc-lore-examinable-ssg-45 = Developed in response to persistent complaints from Weston Yamada’s internal security and PMC divisions, the SSG45 is a direct result of field dissatisfaction with the UNMC-standard M54C Mk2.
                            While the M54C was lightweight and easy to mass-produce, it lacked the stopping power and durability required for the kind of off-grid, high-intensity operations typically assigned to WeYa corporate teams.
                            Several units began modifying their standard-issue rifles into custom variants, unofficially dubbed M54C/2s, to improve handling, penetration, and reliability. These field modifications drew enough attention that Weston Yamada’s R&D division launched a formal weapons program to design a purpose-built rifle based on actual combat feedback.
                            The result was the SSG45: a heavy-caliber, caseless assault rifle designed for harsh environments and close-quarters superiority. It features an integrated recoil mitigation system, hardened internal components, and support for smart optics and upgraded attachments. Though still technically in field testing, the SSG45 has seen wide adoption across multiple WeYa security teams operating in high-threat zones.
                            Reports suggest the rifle performs well in sustained engagements, with only minor overheating issues during prolonged automatic fire. The R&D team is already addressing these issues in ongoing iterations.

rmc-lore-examinable-un-flag = The United Nations. The most prosperous nation in the universe. Through trials and tribulations, insurgencies and wars, the United Nations has united the people of earth, the people of the galaxy, all together under one banner. This banner.
                            This is a nation worth dying for. You will triumph, you will fail, you will live, and you will die, but this flag will stand through it all. Glory to the United Nations.

rmc-lore-examinable-ceremonial-sabre = Standard issue to commanding officers of the United Nations Marine Corps, the ceremonial sabre is more than a relic, it’s a rite. Forged from composite alloy and polished to a mirror gleam, each sabre is engraved with the Marine’s name and unit upon promotion to command.
                                        While primarily used in formal ceremonies and change-of-command rituals, the blade is combat-capable, a silent reminder that in the UNMC, even tradition draws blood when necessary.
                                        Veteran officers are known to carry their sabres into battle, not for the weapon’s edge, but for what it represents: unwavering leadership in the unforgiving cold dark void of space. The sabre’s design dates back to the Old Earth naval traditions, carried forward into the stars with grim pride.
                                        Some say that if you die with it in your hand, your name is forever etched deeper into UNMC history.

rmc-lore-examinable-fax-machine =  The fax machine, although of archaic origin, is surprisingly apt to the modern spacefaring nations of today.
                                    It utilizes the preexisting groundbreaking interstellar phone system to transmit documents as audio signals, which can then be decoded into the original document at the receiving fax machine.
                                    Weston-Yamada has patented the technology, resulting in other models of fax machines being far slower, and far less common.
                                    Security concerns have been raised as to the security of using the telephone system for sensitive documents, but Weston-Yamada has promised their infrastructure is extremely secure.

rmc-lore-examniable-orbital-cannon = After repeated use of nuclear weapons during UNMC operations involving civilian colonies resulted in both unnecessary civilian casualties and long term ecological disasters in affected areas, the UNMC determined an intermediate weapon between conventional artillery and nuclear explosives was necessary to avoid further nuclear incidents and public ill-will.
                                    Several companies offered various prototypes to help solve this issue, including anti-ship missiles modified to target laser designations on the ground, and large low altitude conventional bombs intended to be delivered via a standard AUD-25 dropship. In the end, the UNMC decided Aegis Armament’s proposal to be most practical; a large, 400mm ship mounted artillery cannon designed to fire a variety of specially made ammunition.
                                    A vast majority of troop carrying UNMC starships were outfitted with these cannons, giving each and every marine company the capability of orbital bombardment. After widespread success in the field, several new models of orbital cannon were created to address a few major concerns with the weapon, namely the concerningly high rate of blue on blue incidents.
                                    Most notably, new models of Aegis orbital cannons are able to effectively target and fire both laser and precision GPS guided shells, vastly increasing the accuracy and reducing the risk of friendly fire. Unfortunately, these new models have yet to reach the poorly funded frontier fleets, and friendly fire incidents involving orbital bombardments are all too common.

rmc-lore-examinable-lady-fingers = A bold experiment in marketing, these brutal, unfiltered menthol cigarettes come in dusty rose packaging aimed at the women of the UNMC. The scent is so overpowering that they are sometimes used to keep bugs out of field tents. Despite the effort, they are rarely chosen and mostly sit untouched in vending machines, quietly daring someone to try. Whether anyone actually likes them is another question.
rmc-lore-examinable-kierland-electro-golds = Popularized by Novaris workers during the construction of its premier station, these cigarettes lit easily, burned evenly, and offered a straightforward, dependable smoke. The flat, dusty flavor and steady draw quickly made them a colonial staple. Kierlan later scaled production on frontier farming worlds and locked in exclusive trade deals with the UNMC.
rmc-lore-examinable-emerald-greens = Instantly recognizable by their price that undercuts even water, these cigarettes have become a fixture wherever budgets and morale run low. Nobody is quite sure what goes into the blend, but most agree you don't buy Emerald Greens for the flavor.

rmc-lore-examinable-boots-07 = A large portion of the magazine describes the B18 Defensive Armor, how it is designed to make the modern marine invincible and that it has recently finished trials, raising the expectations of the brass for this new piece of gear.
rmc-lore-examinable-boots-45 = The first part of the article explains basic sidearm maintenance and includes a small advertisement for a well-known gunsmith on Gateway Station. The second describes the best positions to sleep with your sidearm under the pillow in case of unexpected seditious activity.
rmc-lore-examinable-boots-58 = The article contained within describes the experience of the 1st FORECON Battalion veterans in the Tientsin campaign and the harsh jungle environment they had to go through when dealing with SPP and Local Guerrillas.
rmc-lore-examinable-boots-113 = The article details the fierce urban combat the marines had to face against human colonists on Mars during the early days of its colonization. As Weston Yamada was expanding on the red frontier, they faced armed resistance from colonists who refused the corporate expansion. Weston Yamada PMCs with the help of nearby UNMC forces fought off the insurrectionists. The article also mentions a few accounts from tankers on the effectiveness of their new main battle tanks, and recent sightings of MARSOC operators in the AO. This conflict marked one of the first recorded uses of orbital bombardments in active combat by the UNMC, with the UNS Omaha involved.
rmc-lore-examinable-boots-150 = A large portion of this issue explains SPP field rations aren't standardized and are produced at a local level. Because of this, captured and confiscated SPP rations have included some odd choices such as duck liver, century eggs, lutefisk, pickled pig snout, canned tripe, and dehydrated candied radish snacks.

rmc-lore-examinable-orrery-65 = Half of this issue is taken up by rumors of a Senior Executive misfiling his Quarterly Profit Report for Danton's Perch with the PMC Dispatch Division. After it is a debate article between two Executives from Special Services, regarding the creation of a colony in the Mu Arae system. The debate is centered around the location of the colony: one Executive thinks the colony should be a sub-orbital gas harvester around a gas giant, while the other thinks it should be located on the gas giant's verdant moon. Halfway through the debate, both Executives appear to lose their composure, and start slinging insults. The rest of the article appears to be heavily censored after that point.
rmc-lore-examinable-orrery-175 = The centrepiece of this issue is a story regarding the creation of a new vessel for the Navy, designed to be not only withstand all sorts of damage and attacks, but also contain enough firepower to destroy a city. The article explains that this is a joint project between the TSE and Weston-Yamada, and interviews the various WeYa and Imperial Engineers working on the ship. Although no confidential information is contained within, the repeated mention of railguns, triple point-defence lasers, and a suite of missile tubes gives you a good idea as to the strength of the vessel.
rmc-lore-examinable-orrery-184 = This special issue covers a few the various projects being undertaken by the Weston-Yamada Corporation which have been cleared for a press release by the Shareholders and the Division Director. Notable projects include the UY-21 Weston-Yamada Blending Unit (Which fixes the UY-20's tendency to explode under heat), a 'prototype portable heavy mining laser' designed to cut through rock like butter, and a Weston-Yamada MANPADS system (Designated the TYPHOON EK-403) designed for PMC usage. Halfway through the issue, the magazine offers a 'Buy one, get one free' coupon for a pack of Sequoia beer; it appears to have expired the day after the issue was published.
rmc-lore-examinable-orrery-34 = A large portion of this issue is dedicated to wide-assortment of different clothing options which are currently in-style for Weston-Yamada executives across the galaxy by region. It displays the clothing choices of the inner rim to be somewhat conspicuous, but stylish and attractive. Sleek suits with price tags in the quadruple digits dominate much of this section, along with snappy ties. However, closer to the frontier the common choices branch out, from thick jackets able to rebuff cold fronts with ease, to fashionable shorts able to keep hard-working executives cool in sweltering climates. The article also mentions R&D's efforts towards redefining and improving the classic 'We-Ya Stompers'.
rmc-lore-examinable-orrery-202 = The main focus of this issue is on Weston-Yamada's synthetic programm specifically how the rollout of Generation 3 synthetics has been massively successful by all accounts. It contrasts the flaws of the previous Generation 2s, such as their somewhat fragile build, as well as their habit of suffering malfunctions with the advancements made by the Generation 3 program which claims to amend the afformentioned issues, raising the bar for future synthetic projects. It also explains how the rollout has increased WEYA's stock price by 4%, and that many nations and organizations have invested in Gen 3 synths, such as the TSE, UN, and policing agencies such as the CMP and ZSPA.
rmc-lore-examinable-orrery-217 = This issue focuses on Weston-Yamada's Silverguard Private Military Company assets, such as AZURE-15. Deployed to various zones to secure, protect, or acquire corporate assets, these mercenaries work entirely on Weston-Yamada's payroll, and are trained and provided with gear on the level of many formal militaries. Weapons such as the SSG-45 and M80 are mentioned, as well as state-of-the-art armour. It goes on to discuss the success of PMC deployment in putting down CLF agitator cells, as well as making sure WEYA's assets are secure from hostile forces. Midway through the magazine, a smaller article talks about the potential demotion of a Special Services Executive Supervisor after they failed to disclose a large-scale industrial accident they oversaw to their superiors.
rmc-lore-examinable-orrery-220 = Much of this issue is centered on recent issues faced by Weston-Yamada's Logistics Division, specifically on the frontier in Zypheron. It speaks of how recent tensions between the UN/TSE and SPP, as well as riots caused by the CLF have impacted the Company's supply chain, such as increased cost of consumer goods, as well as the reduced number of viable ports for restock and refuel. However, it does discuss current plans to fix this issue and minimize costs, such as constructing additional supply depots in key locations, such as OCP-583, and deepening trade tides with Stakeholder organizations such as the UN and TSE. It also discusses the newest options in bulk transport vessels, able to freight fifty-thousand shipping containers across the galaxy.
rmc-lore-examinable-orrery-258 = This issue discusses the efforts made to establish a colony in the mid-rim, on the temperate world of LV-676. Initially scouted as a possible colony location, it was only in recent times that plans to colonize the planet were considered. Following a 2102 Shareholder meeting, Weston-Yamada Special Services were given the go ahead to begin colonization. Initially consisting of 234 personnel and 2 synthetics, they staked their claim, and named the planet 'Fort Denst'. Initial efforts proved difficult; challenging terrain, broken water purifiers, and heavy winds resulted in casualties and injuries. However, the people of Fort Denst held on and persevered; nowadays, the colony hosts a population of 1430 personnel, and is famed for its cheese exports.

rmc-lore-examinable-weya-windbreaker = A result of a 7-year R&D program, this windbreaker features advanced temperature regulation, comfortable design, and a hydrophobic exterior, making it perfect for almost all weather. Unfortunately, nobody thought to give it a hood.
rmc-lore-examinable-atmospheric-composition-scanner = A handheld piece of heavy-duty equipment able to collect information about the local atmospheric data and information using advanced tech which WEYA R&D is keen on keeping secret. Utilized across the galaxy for a multitude of purposes, such as searching for gas leaks, ensuring terraforming efforts are making progress, and gathering scientific data on exoplanet environs. This device has seen use with WEYA, TSE, and UN since 2078 with very few changes, and is renowned for it's reliability, especially in harsher conditions.
