using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CM14.Admin;

[GenerateTypedNameReferences]
public sealed partial class CMTransformTab : Control
{
    public CMTransformTab()
    {
        RobustXamlLoader.Load(this);
    }
}
